### PR TITLE
Move external qtesla folders into a common external one

### PR DESCRIPTION
**Pull request by christianpaquin**
Also removed SPDX statement from external qtesla files.

### CODE REVIEW

**Comment by christianpaquin** [comment]
@xvzcf, I modified the qtesla directory and the CMakeList file, and I get a build error I don't understand. Can you look at the error and my changes to that file to see if I did something wrong?

```
FAILED: src/sig/qtesla/CMakeFiles/qtesla.dir/sig_qtesla.c.o
/usr/bin/cc -D_AMD64_ -Dexternal/portable -Iinclude -I../src/sig/qtesla/external -fPIC -fvisibility=hidden   -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,--gc-sections -std=gnu11 -MD -MT src/sig/qtesla/CMakeFiles/qtesla.dir/sig_qtesla.c.o -MF src/sig/qtesla/CMakeFiles/qtesla.dir/sig_qtesla.c.o.d -o src/sig/qtesla/CMakeFiles/qtesla.dir/sig_qtesla.c.o   -c ../src/sig/qtesla/sig_qtesla.c
<command-line>:0:9: error: ISO C99 requires whitespace after the macro name [-Werror]
cc1: all warnings being treated as errors
```

**Comment by christianpaquin** [comment]
I think I found the issue, @xvzcf. You can hold off for now.

**Comment by christianpaquin** [comment]
Works now, @xvzcf, can you take a look?

**Comment by xvzcf** [comment]
Looks good to me.

**Pull request merged**
