### PR TITLE
Fix linking of test programs on msys

### PR DESCRIPTION
**Pull request by d0p1s4m4**
Mostly related to: #1749 and #1751 

* [**NO**] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [**NO**] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Review by dstebila — APPROVED** [review]

**Review by baentsch — APPROVED** [review]
Thanks for this improvement to the `msys` toolchain!

**Comment by SWilson4** [comment]
Thank you very mcuh for the contribution @d0p1s4m4! Sorry to cause trivial work for you, but would you please address the failing DCO check? It should just be a matter of committing with the `-s` option.

**Review by SWilson4 — APPROVED** [review]

**Comment by d0p1s4m4** [comment]
@SWilson4 done

**Comment by SWilson4** [comment]
Thank you very much!

**Pull request merged**
