### PR TITLE
SIKE March 2021 bug fix

### LINKED ISSUE #979: Update SIKE (March 5th bug fix)
Integrate commit [679814](https://github.com/microsoft/PQCrypto-SIDH/commit/67981447d36dfdcfc849d8d88963f727a31ba772).

([Diff since v3.4](https://github.com/microsoft/PQCrypto-SIDH/compare/v3.4...679814))

### PR DESCRIPTION
**Pull request by christianpaquin**
Integrates SIKE March 2021 bug fix. Fixes #979.

### CODE REVIEW

**Review by dstebila — APPROVED** [review]

**Comment by thomwiggers** [comment]
I'm still seeing spurious failures for at least SIKEp434Compressed (probably unrelated to just this PR — in KEMTLS experiments the experiments including SIKEp434Compressed have always been a bit unstable): 

https://github.com/open-quantum-safe/liboqs-rust/runs/2490266273#step:15:209

**Comment by jschanck** [comment]
@thomwiggers how often does that happen? And can you tell me the type of CPU it's running on?

**Comment by thomwiggers** [comment]
I ran the simple encapsulate/decapsulate test in my Rust wrapper for all SIKE variants in a tight loop: it happened in P503-compressed as well. That took a while though. I'm now adding a loop to `test_kem` to see if I can reproduce it directly in liboqs...

**Comment by jschanck** [comment]
Maybe try with the nist drbg and output a seed if you catch a failure. I've done about 50k iterations with my fuzzing tools and haven't seen anything yet.

**Comment by thomwiggers** [comment]
I modified `test_kem.c` to be multithreaded and use NIST-KAT's RNG:  https://gist.github.com/thomwiggers/c23e2c4e01971ccfd5496466b72a89c6


```
Configuration info
==================
Target platform:  x86_64-Linux-5.11.16-arch1-1
Compiler:         gcc (10.2.0)
Compile options:  [-march=native;-Werror;-Wall;-Wextra;-Wpedantic;-Wstrict-prototypes;-Wshadow;-Wformat=2;-Wfloat-equal;-Wwrite-strings;-O3;-fomit-frame-pointer;-fdata-sections;-ffunction-sections;-Wl,--gc-sections;-Wbad-function-cast]
OQS version:      0.6.0-rc1
Git commit:       8f8bb44c2fb8ce4b65aca2889ca2b8c11861f2cb
OpenSSL enabled:  Yes (OpenSSL 1.1.1k  25 Mar 2021)
AES:              OpenSSL
SHA-2:            OpenSSL
SHA-3:            C
CPU exts compile-time:  ADX AES AVX AVX2 AVX512 BMI1 BMI2 POPCNT SSE SSE2 SSE3

ERROR: shared secrets are not equal
entropy_input        (  48 bytes):  8B9E5F79BB0EE397C7DF04C0D6593280ADD0A92CB6F9D046738C7C0846A340529B28F78FC7CFBCE732C0C0E1031114F4
shared_secret_e      (  16 bytes):  119D4BBA6CC7A3196B6CB11EDC2C5331
shared_secret_d      (  16 bytes):  8BBA5DD161F22661502BE27C603B5CE4
ERROR: shared secrets are not equal
entropy_input        (  48 bytes):  6BA56E8703B104A29E1F20D8A3D64FD9EB36CDE9A49E921B462178A86D1D8FB677902F8C61B4C488B11AD879F5FDDA67
shared_secret_e      (  16 bytes):  911A05EA62C8CE15F8E88F107C810284
shared_secret_d      (  16 bytes):  B6B6926F523F575BFE9C4864D6506C57
ERROR: shared secrets are not equal
entropy_input        (  48 bytes):  FCC52CBE74090A719C44655B99623B89DE1D39C09286FCA28F7A21B468CD43A7249166DA370D68E445F1CE7F4FDB365A
shared_secret_e      (  16 bytes):  F717246F5062F3C571A85ED7BB5ACC98
shared_secret_d      (  16 bytes):  B8C0FC2D380DBF78338D7DFD425448AF
ERROR: shared secrets are not equal
entropy_input        (  48 bytes):  BF65977D2084F980670C2BDC36544A486E4394944342DD09EF308D5F004732C4D15D5799F1B34FF730CF76C22BC0865F
shared_secret_e      (  16 bytes):  35B19B9E4B0B8B08ECA644143B917EE7
shared_secret_d      (  16 bytes):  C63B716E1640D7CB9E50099F32727F89
ERROR: shared secrets are not equal
entropy_input        (  48 bytes):  509867683AF7141564E58616740CADEA09E127F3B688E4BC478B82E5BB6D3FFEBA5EB23C086D04098B67477C32725749
shared_secret_e      (  16 bytes):  0028DA44B2E61F170421B97499D1F84B
shared_secret_d      (  16 bytes):  F00B568402CAC17896EAC96F721C9DB4
ERROR: shared secrets are not equal
entropy_input        (  48 bytes):  4C47590C30F81A7F3269B1D84673357300C3FA8C320D7EB5536F35FE90C6E806CCBDCB58F12636DB11AAA5AC18CFC5DA
shared_secret_e      (  16 bytes):  A2DC81A27CB5D52B9E009C1BB0108DB9
shared_secret_d      (  16 bytes):  12A2EECB020B2F36578EA5FA1B975FA0
ERROR: shared secrets are not equal
entropy_input        (  48 bytes):  7AB5700CAF8CAC1616A1D035B8D11BE99FB9F2C86CE59D2B2EF8DBC86487388474AB54A2380D9D18B3A8BACAE1F5D939
shared_secret_e      (  16 bytes):  84F16BEF4CEA85F1D6180558E12F4D75
shared_secret_d      (  16 bytes):  01768B20F51CBCBEAFE00C2389717BB4
ERROR: shared secrets are not equal
entropy_input        (  48 bytes):  62CD496D391D7FE6447A417F4466C2D9424B2DCEC6F8787D0132F33BB97EAE1CC0FF08C63A789433D98DE2BED09855AA
shared_secret_e      (  16 bytes):  16733BB49A09248179772B18FD282DC6
shared_secret_d      (  16 bytes):  2907E88CD3FD5BDF5AE82AC945366318
```

I've not yet entirely figured out how to feed the seed back in to get a reproducible-every-time version.

**Pull request merged**
