### PR TITLE
Updated SIKE implementation with latest changes.

### PR DESCRIPTION
**Pull request by christianpaquin**
This PR includes:
- Optimizations changes from PR #558, adapted to cmake
- New changes from the [SIDH library](https://github.com/microsoft/PQCrypto-SIDH), moving from commit [ebd1c8](https://github.com/microsoft/PQCrypto-SIDH/commit/ebd1c80a8ac35e9ca2ef9680291a8a43b95a3bfa) to [fde210](https://github.com/microsoft/PQCrypto-SIDH/commit/fde210a7cf03e835cceb1d5ff34ccf58625d0311).

### CODE REVIEW

**Comment by christianpaquin** [comment]
@xvzcf, the circleci build for ubuntu and centos8 fail because the `add_compile_definitions` cmake command is unsupported in `src/kem/sike/CMakeLists.txt`. I took this from your optimized branch; could you recommend an alternative way to set compilation macros? Thanks.

**Comment by christianpaquin** [comment]
> @xvzcf, the circleci build for ubuntu and centos8 fail because the `add_compile_definitions` cmake command is unsupported in `src/kem/sike/CMakeLists.txt`. I took this from your optimized branch; could you recommend an alternative way to set compilation macros? Thanks.

Nevermind @xvzcf, I replaced the problematic statement with `add_compile_options` (as seen in the bike cmakelist) and it seems to have fixed the problem.

**Comment by christianpaquin** [comment]
@xvzcf, @dstebila; test_style fails on some circleci OS. What's the equivalent to `make prettyprint` with our new cmake build system?

**Comment by dstebila** [comment]
`cd build ; ninja prettyprint`

**Comment by xvzcf** [comment]
> > @xvzcf, the circleci build for ubuntu and centos8 fail because the `add_compile_definitions` cmake command is unsupported in `src/kem/sike/CMakeLists.txt`. I took this from your optimized branch; could you recommend an alternative way to set compilation macros? Thanks.
> 
> Nevermind @xvzcf, I replaced the problematic statement with `add_compile_options` (as seen in the bike cmakelist) and it seems to have fixed the problem.

Actually, could you change it to use `target_compile_definitions` as done [here](https://github.com/open-quantum-safe/liboqs/blob/master/src/sig/picnic/CMakeLists.txt)?

**Comment by christianpaquin** [comment]
This PR (opened originally in October!) is finally passing. @dstebila, @xvzcf, can one of you take a look?

**Comment by dstebila** [comment]
@christianpaquin shall we merge this?

**Comment by christianpaquin** [comment]
Yes, ready. Sorry, I had forgotten to not make it a draft PR.

**Pull request merged**
