### PR TITLE
Sync with PQClean

### PR DESCRIPTION
**Pull request by dstebila**
Sync with PQClean https://github.com/PQClean/PQClean/commit/6c1ea921ee4a06a6b50c742ca540bb9b5e51aee2. 

Related to #1058.

### CODE REVIEW

**Review by baentsch — CHANGES_REQUESTED** [review]
The contents look good, but the documentation didn't get updated (git commit hash unchanged in docs/algorithms/sig/falcon.XXX): It seems to be necessary to manually run `update_pqclean_alg_docs.py` -> would it be an idea to trigger this when running `copy_from_upstream.py`?

**Comment by dstebila** [comment]
> The contents look good, but the documentation didn't get updated (git commit hash unchanged in docs/algorithms/sig/falcon.XXX): It seems to be necessary to manually run `update_pqclean_alg_docs.py` -> would it be an idea to trigger this when running `copy_from_upstream.py`?

Good catch, Michael. Fixed now.

**Review by baentsch — APPROVED** [review]

**Comment by xvzcf** [comment]
It would be nice to trigger the documentation update in `copy_from_upstream.py`. 

My thought was to first extend `update_pqclean_alg_docs.py` to also support non-PQClean algorithms (such as using the META.yml at https://github.com/pq-crystals/dilithium), and subsequently fold this script into `copy_from_upstream.py`.

**Comment by baentsch** [comment]
Makes sense. Now tracked in #1064.

**Pull request merged**
