### PR TITLE
Add Windows ARM64 support

### LINKED ISSUE #1264: Compiling on Windows ARM64 / ARMv7 with OQS_DIST_BUILD fails
Hello!

I am trying to compile liboqs for Windows ARM64 and ARMv7 with OQS_DIST_BUILD enabled, but both fail because the `src/common/common.c` does not provide implementations for ARM64/ARMv7 CPU feature detection on Windows. The build fails by failing to find the "<sys/auxv.h>" header, which only exists on Linux.

### PR DESCRIPTION
**Pull request by res0nance**
Allows liboqs to compile on Windows ARM64

Fixes #1264 

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Review by baentsch — APPROVED** [review]
Thanks for these improvements (incl CI)! LGTM. 

Have you tested the resultant binary on a Windows ARM64 box? Or do you see a way to test/run this emulated in CI?

**Comment by res0nance** [comment]
> Thanks for these improvements (incl CI)! LGTM.
> 
> Have you tested the resultant binary on a Windows ARM64 box? Or do you see a way to test/run this emulated in CI?

I unfortunately do not have access to a Windows ARM64 box. There isn't any CI tool that provides ARM windows runners as well. There isn't an emulator option for windows either.

Perhaps the original issue reporter @darktohka could test and see if this works for them. Which unfortunately would mean we have no way of continuously testing this.

**Comment by dstebila** [comment]
I noticed that the new Github Windows job didn't actually run, is that because it's a new file or possibly because it's in a fork rather than the main repo?  Also our other existing AppVeyor CI didn't run, again I believe because it's in a fork. @baentsch, am I right in remembering that we can trigger the jobs in our CI by pushing this branch into our repo?

**Comment by baentsch** [comment]
> > Thanks for these improvements (incl CI)! LGTM.
> > Have you tested the resultant binary on a Windows ARM64 box? Or do you see a way to test/run this emulated in CI?
> 
> I have a aarch64 windows vm on my personal m1 mac that I can test this on if you want me to give it a sanity check. Won't be able to until a bit later this week though. :)

That would be very much appreciated! It's definitely not urgent but would be the next best thing to a regular CI test. Let's call it "induction CI": Builds, tests and runs OK the 1st time; if it builds the next time, we'll assume it'll also run the next time and ever after :-) Will merge after you confirm things are good for you.

**Comment by res0nance** [comment]
> I noticed that the new Github Windows job didn't actually run, is that because it's a new file or possibly because it's in a fork rather than the main repo? Also our other existing AppVeyor CI didn't run, again I believe because it's in a fork. @baentsch, am I right in remembering that we can trigger the jobs in our CI by pushing this branch into our repo?

I realized the issue here, we don't run the github actions on pull_request. I've fixed it for this PR and corrected the remaining platforms in #1546

**Review by dstebila — APPROVED** [review]

**Comment by baentsch** [comment]
Merge done. Thanks for the contribution!

**Pull request merged**
