### PR TITLE
Additional comments on limitations for use in production environments

### PR DESCRIPTION
**Pull request by dstebila**
I thought we had this type of disclaimer in all our subproject READMEs, but apparently it's not in the liboqs README.  Based on the text in the OQS-OpenSSL README.

* [No] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [No] Does this PR change the the list of algorithms available -- either adding or removing?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

### CODE REVIEW

**Comment by dstebila** [comment]
@xvzcf, @christianpaquin, @baentsch Motivated in part by our discussion in this week's call.  Feedback welcome.

**Comment by baentsch** [comment]
I fully concur with the second addition; the first is a bit strong in my opinion: "[...] advisable to wait on deploying quantum-safe algorithms until further guidance [...]" could be understood as discouraging people from using this at all at this time. What about 

> While at the time of this writing there are no vulnerabilities known in any of the quantum-safe algorithms used in this library, caution is advised when deploying quantum-safe algorithms as most of the code has not yet been subject to the full rigour of classic cryptographic implementations. Particular attention should be paid to guidance  provided by the standards community, especially from the NIST standardization project.

**Comment by christianpaquin** [comment]
> I fully concur with the second addition; the first is a bit strong in my opinion: "[...] advisable to wait on deploying quantum-safe algorithms until further guidance [...]" could be understood as discouraging people from using this at all at this time. What about
> 
> > While at the time of this writing there are no vulnerabilities known in any of the quantum-safe algorithms used in this library, caution is advised when deploying quantum-safe algorithms as most of the code has not yet been subject to the full rigour of classic cryptographic implementations. Particular attention should be paid to guidance  provided by the standards community, especially from the NIST standardization project.

Part of the "don't use this in production" is our OQS statement; I feel comfortable stating this as we are indeed a research project. A commercial org could put some time to review the project code and underlying algs, and lift this disclaimer as part of their offering...

**Review by christianpaquin — APPROVED** [review]

**Comment by dstebila** [comment]
Thanks!  I've updated the wording based on your suggestion, @baentsch.

**Review by xvzcf — APPROVED** [review]

**Pull request merged**
