### PR TITLE
CircleCI testing for Windows

### PR DESCRIPTION
**Pull request by baentsch**
Adds windows to the CCI test matrix. All tests passed on my CCI account. 

@dstebila: Could you please touch base with CircleCI that they also activate this for the OpenQuantumSafe account? 

@xvzcf I could rebase PR #683 to this to demonstrate that the `CPUFEATURES_LIBRARY` fix has no negative implications to Windows-Building and we can finally merge it in. OK?

@christianpaquin Given I'm a sorry but confessing Windows-noob, could you please check that I didn't do something utterly silly here? Also, one question: How can it be that build+test on Linux takes 1.5 minutes while testing on Windows takes more than 15 minutes alone? Observing the test run, it's mostly the "SPHINCS" family running ultra-slow on Win. Side note: Win-build is a few seconds slower than Linux, but not much, so the CircleCI VMs for Windows are not _that_ much worse than the Linux VMs; in other words, there's something weird in the Windows test run that I don't understand.

### CODE REVIEW

**Comment by gadoofou87** [comment]
@baentsch I understand correctly that you want to use this instead of Appveyor?

**Comment by baentsch** [comment]
@gadoofou87 For the time being, I see this as a complement to AppVeyor. It would be good to understand why the testing there takes even longer and then fails (unlike at CircleCI), though. @xvzcf also wants to look into that...

**Comment by xvzcf** [comment]
> @xvzcf I could rebase PR #683 to this to demonstrate that the `CPUFEATURES_LIBRARY` fix has no negative implications to Windows-Building and we can finally merge it in. OK?

Sounds good.

**Comment by dstebila** [comment]
> @dstebila: Could you please touch base with CircleCI that they also activate this for the OpenQuantumSafe account?

I've submitted a request.

**Comment by christianpaquin** [comment]
The Windows-specific "stuff" looks ok, but being a CircleCI-noob (to reuse your label :)) makes it difficult to competently review this. Was AppVeyor as slow as the CircleCI Windows build?

**Comment by baentsch** [comment]
@christianpaquin AppVeyor was a factor of 4 slower and often did not complete testing at all. That was the reason why we looked at using CircleCI for Windows at all.

**Comment by dstebila** [comment]
I got a response from CircleCI that they do not currently offer Windows support on their open source plans.  The response says they intend to do so in the future, but don't have a timeline.

**Comment by baentsch** [comment]
@dstebila Thanks for letting me know. I'll enquire from my side why this is so: It seems a bit of a step-down from what they promised me.
But in the light of this, can I ask to consider [this issue](https://github.com/open-quantum-safe/liboqs/issues/698) as an alternative for this PR?
Alternatively/in addition: Is there anything speaking against merging this PR as it won't change anything in the OQS account (it simply won't run if I'm not mistaken) -- but would ensure I get a minimum of quick sanity checking regarding Windows when my trial AppVeyor account terminates (by April 9).

**Comment by dstebila** [comment]
> Alternatively/in addition: Is there anything speaking against merging this PR as it won't change anything in the OQS account (it simply won't run if I'm not mistaken) -- but would ensure I get a minimum of quick sanity checking regarding Windows when my trial AppVeyor account terminates (by April 9).

I suppose that's fine.

**Pull request merged**
