### PR TITLE
extend weekly run timeout [skip ci]

### PR DESCRIPTION
**Pull request by baentsch**
Extending maximum weekly constant runtime test time to 2h.

### CODE REVIEW

**Review by dstebila — APPROVED** [review]

**Comment by baentsch** [comment]
This change allowed the constant time tests to proceed from [71%](https://github.com/open-quantum-safe/liboqs/runs/4676886314?check_suite_focus=true) (1h timeout) to [76%](https://github.com/open-quantum-safe/liboqs/runs/4745481918?check_suite_focus=true) (2h timeout) -> How many hours do we want to allow? Any algorithms to prune instead?

**Comment by dstebila** [comment]
> This change allowed the constant time tests to proceed from [71%](https://github.com/open-quantum-safe/liboqs/runs/4676886314?check_suite_focus=true) (1h timeout) to [76%](https://github.com/open-quantum-safe/liboqs/runs/4745481918?check_suite_focus=true) (2h timeout) -> How many hours do we want to allow? Any algorithms to prune instead?

We could probably prune SPHINCS and Rainbow?

**Comment by baentsch** [comment]
> We could probably prune SPHINCS and Rainbow?

Completely ditching some families sounds not right. The more I think about it, we should keep all (until NIST prunes :) and extend the permitted runtime to 10 hours. Alternatively we should clearly state (in the docs, e.g.) that we do (not) test some algorithms at the same level as others (because they're prohibitively expensive -- which may possibly be of interest to NIST).

**Comment by dstebila** [comment]
> > We could probably prune SPHINCS and Rainbow?
> 
> Completely ditching some families sounds not right. The more I think about it, we should keep all (until NIST prunes :) and extend the permitted runtime to 10 hours. Alternatively we should clearly state (in the docs, e.g.) that we do (not) test some algorithms at the same level as others (because they're prohibitively expensive -- which may possibly be of interest to NIST).

Are we allowed 10 hour jobs?  If so then yes let's do that.  At least we do a full constant time test run prior to release as per our [release process](https://github.com/open-quantum-safe/liboqs/wiki/Release-process).

**Comment by baentsch** [comment]
> Are we allowed 10 hour jobs? If so then yes let's do that. 

I don't know, but why not: #1175 . If that fails, we'll prune SPHINCS and Rainbow as per your suggestion, @dstebila

**Pull request merged**
