### PR TITLE
Updated Windows build (added sig, fixed warnings, 2017 update)

### PR DESCRIPTION
**Pull request by christianpaquin**
Updated Visual Studio solution to 2017 version, fixed build warnings (issue #159), added signature and Picnic support.

### CODE REVIEW

**Comment by christianpaquin** [comment]
Travis has an error with a link ref to Picnic. The branch compiles on my Linux system, can someone else repro?

**Comment by christianpaquin** [comment]
I verified the PR: Windows build still works. I merged with master. I get the same failure as in Travis; I don't know why; I can't see the difference with the master branch. Can someone see what's wrong?

**Comment by christianpaquin** [comment]
OK, I found a bug in the sig_picnic makefile that prevented the ENABLE_PICNIC macro to work. Works now, both on Windows and Linux on my system. Travis fails because of prettyprint (I tried to clean up one file by removing a \r, but that might have broken the prettyprint rules). Prettyprint doesn't work on my machine, can someone run it (@vsoftco , @dstebila ?) That should take care of the problem, and we'll finally be able to merge that branch. Thanks

**Comment by christianpaquin** [comment]
I don't understand the Travis error on osx. @dstebila, can you reproduce?

**Comment by vsoftco** [comment]
@christianpaquin I cannot reproduce on my side...

**Comment by vsoftco** [comment]
@christianpaquin Related: https://github.com/Homebrew/brew/issues/3299

**Pull request merged**
