### PR TITLE
Add loongarch64 support

### PR DESCRIPTION
**Pull request by zhaixiaojuan**
This PR does the following:
Add loongarch64 support in CMakeLists.txt and src/common/common.c

The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.
Documentations:
ISA:
https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
ABI:
https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
More docs can be found at:
https://loongson.github.io/LoongArch-Documentation/README-EN.html

### CODE REVIEW

**Review by baentsch — CHANGES_REQUESTED** [review]
Thanks for adding support for this platform, @zhaixiaojuan . IMO the PR should also contain a suitable entry in the PLATFORM.md file, at least listing it in the proper tier, ideally also providing explanatory pointers to the platform and the software it supports (Linux distro, e.g.). Final question: Are you willing to serve as a contact for possible future questions regarding OQS issues on this platform? I'm asking as I have 0 experience/exposure to this platform so far and thus could not do that.

**Comment by zhaixiaojuan** [comment]
>  Final question: Are you willing to serve as a contact for possible future questions regarding OQS issues on this platform? I'm asking as I have 0 experience/exposure to this platform so far and thus could not do that.

I am happy to accept this, it is my honor. I will continue to improve liboqs on the LoongArch platform and improve its tier.

**Review by dstebila — APPROVED** [review]

**Comment by dstebila** [comment]
Thanks for the contribution!  I've triggered the CI tests.  @zhaixiaojuan would you be able to follow the instructions at https://github.com/open-quantum-safe/liboqs/pull/2010/checks?check_run_id=34128510566 to do the Developer Certificate of Origin sign-off?

Will hold off on merging this until after 0.12.0 is released.

**Comment by zhaixiaojuan** [comment]
Thank you very much. When is 0.12.0 expected to be released?

**Comment by dstebila** [comment]
> Thank you very much. When is 0.12.0 expected to be released?

It has just been released. And now I've landed this PR on the main branch after the release.

**Comment by SmartisanR1** [comment]
可以的，以前我都是手动加上，这次算是支持龙芯了

**Pull request merged**
