### PR TITLE
Fix unknown pseudo-op: .global under macOS

### PR DESCRIPTION
**Pull request by vsoftco**
replaced .global with .globl in all .S files due to ancient “as” tool
in macOS

### CODE REVIEW

**Comment by dstebila** [comment]
Thanks Vlad!

**Comment by vsoftco** [comment]
@dstebila That's something odd going on, all test seem to pass, however Travis Build #498.5 spits out an Illegal Instruction on line 1789. It seems that `./test_rand --quiet` is spitting out this. I compiled and checked on my side (osX clang), everything works fine

**Comment by dstebila** [comment]
Very weird.  Not sure why that makes a difference.

Google didn't help me much, the only partial explanation I could find was here, but it doesn't seem to offer a clear solution: https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10

I've submitted a new PR #154 which switches the Xcode version to the same one on my desktop.  If that works, that seems like a bit of a cheat, but I don't really know how else to diagnose since we don't have old versions of macOS sitting around.

**Comment by dstebila** [comment]
I'm trying to install an older version of OS X in a virtual machine to try to diagnose as well.

**Pull request merged**
