### PR TITLE
Algorithm selection clarification

### LINKED ISSUE #1781: What are STD algs?
As per https://github.com/open-quantum-safe/oqs-provider/discussions/407 it may be sensible to provide a mechanism to overrule the "STD" algorithm filter (and/or to augment it with other algs). This issue to discuss whether this is a feature we may want to add.

### PR DESCRIPTION
**Pull request by beldmit**
Fixes #1781

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Comment by beldmit** [comment]
Feel free to adjust my best English :)

**Comment by baentsch** [comment]
> Feel free to adjust my best English :)

Telling this to a Swiss/German sounds futile :-)

Thanks for the doc improvement! In the future, may I (or rather mother Earth) ask to tag documentation-only fixes with "[skip ci]" in the commit message to avoid some servers doing pointless tests?

**Review by baentsch — APPROVED** [review]

**Comment by beldmit** [comment]
@baentsch sure. Probably it's worth adding to the PR checklist? And I also can fail the `md` syntax (and regularly do)

**Comment by baentsch** [comment]
> can fail the md syntax

Good point. Are you aware of a (CI) tool catching this?

**Comment by beldmit** [comment]
AFAIK openssl uses some ruby tool for this purpose

**Comment by beldmit** [comment]
https://github.com/openssl/openssl/blob/master/Configurations/unix-Makefile.tmpl#L1172-L1179

**Review by praveksharma — APPROVED** [review]

**Pull request merged**
