### PR TITLE
add define indicating cpu_feature use

### PR DESCRIPTION
**Pull request by baentsch**
`OQS_ENABLE_CPUFEATURES` if set indicates support for CPU feature (runtime) detection. Now only activated when `.CMake/cpu_extensions.cmake` executes OK. If not activated, eliminates the need for the `cpu_features` symbols/library. Resolves build issues when building without `Optimized` CMAKE_BUILD_TYPE set.

### CODE REVIEW

**Comment by xvzcf** [comment]
Could you rebase with master? And I assume the CircleCI tests are running in your account? I'll take a look at why it doesn't run here ...

**Comment by baentsch** [comment]
Merged current master and pushed again. And Yes, the CCI tests run in my account.

**Comment by xvzcf** [comment]
Could you post a link to the CCI build here?

**Comment by baentsch** [comment]
Those CCI runs are visible [here](https://circleci.com/gh/baentsch/liboqs/tree/rt-protect)

**Pull request merged**
