### PR TITLE
added Singh/Chopra algorithms from local copy

### PR DESCRIPTION
**Pull request by simonpgit**
Hi,

I've been working on liboqs in my spare time and have added an algorithm I found mentioned on the Wikipedia RLWE-KEX page (i.e. the work of Singh at https://github.com/vscrypto/ringlwe).  Would you consider it for inclusion in the main liboqs project?  I hope I did the "git" part of this correctly!

Thanks,

Simon

### CODE REVIEW

**Comment by dstebila** [comment]
Hi Simon.  I'll take a look at it after the holidays.  Can you tell me if Singh's paper has been published anywhere?

**Comment by phanimahesh** [comment]
Quoting from the linked project's README, it appears these have been published.
> The algorithm for the power-of-two case is described in the paper "A Practical Key Exchange for the Internet using Lattice Cryptography" by Vikram Singh, available at http://eprint.iacr.org/2015/138, and the algorithm for the prime case is described in "Even More Practical Key Exchanges for the Internet using Lattice Cryptography" by Vikram Singh and Arjun Chopra, available at http://eprint.iacr.org/2015/1120. These in turn are a version of the passively secure key exchange described in the paper "Lattice Cryptography for the Internet" by Chris Peikert, available at http://eprint.iacr.org/2014/070.
>
> Substantial parts of this code are copied from the software published by Joppe W. Bos, Craig Costello, Michael Naehrig, and Douglas Stebila at https://github.com/dstebila/rlwekex, and described in their paper "Post-quantum key exchange for the TLS protocol from the ring learning with errors problem", available at http://eprint.iacr.org/2014/599.

**Comment by simonpgit** [comment]
Hi, I've been replying by email but I think that's gone into a black hole!  Sorry if so (please let me know though, am new to github).

You're correct, phanimahesh, that's the paper and code I used.  My code differs from the "vscrypto/ringlwe" code in that it's much more compact and it has a much more efficient way of doing uniform sampling.

Shall I try to do something about the "travis" errors?  There was a style check that I can probably fix, but you might want to deal with the Makefile issue yourselves.

**Comment by dstebila** [comment]
What I mean is, has the paper been published in a refereed conference/journal?  Not a prerequisite for inclusion in OQS, but if it's already been vetted from that perspective then we don't have to do as much vetting ourselves.

**Comment by simonpgit** [comment]
Hi, I searched around with Google a bit and found some other mentions of the "Even More Practical ..." paper, but didn't notice any refereed stuff.

**Comment by simonpgit** [comment]
Think I'm done now.

**Comment by dstebila** [comment]
Okay, @simonpgit, I'll try to take a look at it next week.  Any further information on peer-reviewed publication of the papers?

**Comment by simonpgit** [comment]
@dstebila, no further info on peer-reviewed publication - I was just going by what I found on Wikipedia + github a while back.

**Pull request closed without merging**
