### PR TITLE
Update to Picnic 3.0.9

### PR DESCRIPTION
**Pull request by sebastinas**
WIP for a 32 bit build fix

* [No] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [No] Does this PR change the the list of algorithms available -- either adding, removing, or renaming?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

### CODE REVIEW

**Comment by sebastinas** [comment]
@baentsch How can I trigger the cygwin tests for this PR?

**Comment by baentsch** [comment]
> @baentsch How can I trigger the cygwin tests for this PR?

Very good question. I've already been puzzled why they don't run by default on a PR. Just to be sure: Did you follow [all steps to set up AppVeyor OK?](https://www.appveyor.com/docs/). Beyond that I've got to admit only passing knowledge of AppVeyor or Windows, so tagging @christianpaquin for further input; or maybe @dstebila or @xvzcf have an idea, too?

**Comment by christianpaquin** [comment]
> Beyond that I've got to admit only passing knowledge of AppVeyor or Windows, so tagging @christianpaquin for further input

I'm afraid I'm no expert either; I'm not sure why it doesn't get triggered.

**Comment by baentsch** [comment]
> I'm afraid I'm no expert either; I'm not sure why it doesn't get triggered.

My assumption by now is that it works/gets triggered in the repo the commit originates with. Hence it would be necessary to have an AppVeyor account properly registered to one's own/"originating" github id.

**Comment by christianpaquin** [comment]
We can create a branch in the oqs repo with Sebastian's changes, as a workaround, if it gets too complicated. That should trigger the appveyor tests, then (?)

**Comment by dstebila** [comment]
I've just pushed a copy of this to a [picnic-3.0.9](https://github.com/open-quantum-safe/liboqs/tree/picnic-3.0.9) branch in the liboqs repository, which should trigger the Appveyor tests.

**Comment by baentsch** [comment]
> I've just pushed a copy of this to a picnic-3.0.9 branch in the liboqs repository, which should trigger the Appveyor tests.

Thanks. That worked and (re)confirmed #1163.

**Comment by christianpaquin** [comment]
What's the impact of #1171 on this? Doesn't it skip picnic on cygwin?

**Comment by baentsch** [comment]
> What's the impact of #1171 on this? Doesn't it skip picnic on cygwin?

If "this" refers to this PR, then the answer is "No": This branch doesn't contain the code of #1171. Accordingly it still tests picnic on cygwin. A true fix for #1163 (either this if amended or another one) should revert #1171 so cygwin on `main` does test picnic again.

**Comment by dstebila** [comment]
I confirm I'm able to build with clang on Apple M1, thanks @sebastinas!  

I do notice that the description of your latest commit mentions Picnic 3.0.10 but the contents of the PR still only contain references to 3.0.9.  Is there now a Picnic 3.0.10?

**Review by dstebila — APPROVED** [review]

**Comment by sebastinas** [comment]
Good to hear!

I hope to get 3.0.10 released on Monday. I'll update the references to the tags once I'm done.

**Comment by dstebila** [comment]
> Good to hear!
> 
> I hope to get 3.0.10 released on Monday. I'll update the references to the tags once I'm done.

Okay, I'll wait for an update before merging this.

**Comment by sebastinas** [comment]
3.0.10 is now available and the PR is ready. It also includes a fix for #1163. I don't yet know why the SSE2/AVX2 code doesn't work on Cygwin when executed on Appveyor. With the included change SSE2/AVX2 support on Cygwin is reverted to the state before #1158.

**Comment by christianpaquin** [comment]
Fantastic, thanks @sebastinas!

**Pull request merged**
