### PR TITLE
Sync with PQClean

### LINKED ISSUE #953: Pull HQC code from PQClean once stack issue is fixed (https://github.com/PQClean/PQClean/issues/390)
MacOS Catalina 10.15.7, Xcode-12.4. Current master.

```
.  .  .  .  .
======================================================= FAILURES ========================================================
___________________________________________________ test_kem[HQC-128] ___________________________________________________
[gw16] darwin -- Python 3.9.2 /opt/local/bin/python3

kem_name = 'HQC-128'

    @helpers.filtered_test
    @pytest.mark.parametrize('kem_name', helpers.available_kems_by_name())
    def test_kem(kem_name):
        if not(helpers.is_kem_enabled_by_name(kem_name)): pytest.skip('Not enabled')
>       helpers.run_subprocess(
            [helpers.path_to_executable('test_kem'), kem_name],
        )

tests/test_cmdline.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = ['./build/tests/test_kem', 'HQC-128'], working_dir = '.'
env = {'ANT_OPTS': '-Dhttp.proxyHost=llproxy.llan.ll.mit.edu -Dhttp.proxyPort=8080', 'AS': 'yasm -m amd64 -f macho64 -p gas -X gnu ', 'AS_INTEGRATED_ASSEMBLER': '1', 'BASH_SILENCE_DEPRECATION_WARNING': '1', ...}
expected_returncode = 0, input = None, ignore_returncode = False

    def run_subprocess(command, working_dir='.', env=None, expected_returncode=0, input=None, ignore_returncode=False):
        """
        Helper function to run a shell command and report success/failure
        depending on the exit status of the shell command.
        """
        env_ = os.environ.copy()
        if env is not None:
            env_.update(env)
        env = env_
    
        # Note we need to capture stdout/stderr from the subprocess,
        # then print it, which pytest will then capture and
        # buffer appropriately
        print(working_dir + " > " + " ".join(command))
    
        result = subprocess.run(
                command,
                input=input,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                cwd=working_dir,
                env=env,
            )
    
        if not(ignore_returncode) and (result.returncode != expected_returncode):
            print(result.stdout.decode('utf-8'))
>           assert False, "Got unexpected return code {}".format(result.returncode)
E           AssertionError: Got unexpected return code -10

tests/helpers.py:41: AssertionError
------------------------------------------------- Captured stdout call --------------------------------------------------
. > ./build/tests/test_kem HQC-128

___________________________________________________ test_kem[HQC-192] ___________________________________________________
[gw17] darwin -- Python 3.9.2 /opt/local/bin/python3

kem_name = 'HQC-192'

    @helpers.filtered_test
    @pytest.mark.parametrize('kem_name', helpers.available_kems_by_name())
    def test_kem(kem_name):
        if not(helpers.is_kem_enabled_by_name(kem_name)): pytest.skip('Not enabled')
>       helpers.run_subprocess(
            [helpers.path_to_executable('test_kem'), kem_name],
        )

tests/test_cmdline.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

command = ['./build/tests/test_kem', 'HQC-192'], working_dir = '.'
env = {'ANT_OPTS': '-Dhttp.proxyHost=llproxy.llan.ll.mit.edu -Dhttp.proxyPort=8080', 'AS': 'yasm -m amd64 -f macho64 -p gas -X gnu ', 'AS_INTEGRATED_ASSEMBLER': '1', 'BASH_SILENCE_DEPRECATION_WARNING': '1', ...}
expected_returncode = 0, input = None, ignore_returncode = False

    def run_subprocess(command, working_dir='.', env=None, expected_returncode=0, input=None, ignore_returncode=False):
        """
        Helper function to run a shell command and report success/failure
        depending on the exit status of the shell command.
        """
        env_ = os.environ.copy()
        if env is not None:
            env_.update(env)
        env = env_
    
        # Note we need to capture stdout/stderr from the subprocess,
        # then print it, which pytest will then capture and
        # buffer appropriately
        print(working_dir + " > " + " ".join(command))
    
        result = subprocess.run(
                command,
                input=input,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                cwd=working_dir,
                env=env,
            )
    
        if not(ignore_returncode) and (result.returncode != expected_returncode):
            print(result.stdout.decode('utf-8'))
>           assert False, "Got unexpected return code {}".format(result.returncode)
E           AssertionError: Got unexpected return code -10

tests/helpers.py:41: AssertionError
------------------------------------------------- Captured stdout call --------------------------------------------------
. > ./build/tests/test_kem HQC-192

================================================ short test summary info ================================================
FAILED tests/test_cmdline.py::test_kem[HQC-128] - AssertionError: Got unexpected return code -10
FAILED tests/test_cmdline.py::test_kem[HQC-192] - AssertionError: Got unexpected return code -10
====================================== 2 failed, 502 passed, 254 skipped in 44.37s ===============
```

### PR DESCRIPTION
**Pull request by dstebila**
Fixes #953.

* [No] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [No] Does this PR change the the list of algorithms available -- either adding, removing, or renaming?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

### CODE REVIEW

**Review by jschanck — APPROVED** [review]

**Comment by mouse07410** [comment]
This PR does **not** fix the #953 problem, at least not on MacOS:
```
================================================== FAILURES ==================================================
_____________________________________________ test_kem[HQC-128] ______________________________________________
[gw16] darwin -- Python 3.9.2 /opt/local/bin/python3

kem_name = 'HQC-128'

    @helpers.filtered_test
    @pytest.mark.parametrize('kem_name', helpers.available_kems_by_name())
    def test_kem(kem_name):
        if not(helpers.is_kem_enabled_by_name(kem_name)): pytest.skip('Not enabled')
>       helpers.run_subprocess(
            [helpers.path_to_executable('test_kem'), kem_name],
        )

tests/test_cmdline.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

command = ['./build/tests/test_kem', 'HQC-128'], working_dir = '.'
env = {'ANT_OPTS': '-Dhttp.proxyHost=llproxy.llan.ll.mit.edu -Dhttp.proxyPort=8080', 'AS': 'yasm -m amd64 -f macho64 -p gas -X gnu ', 'AS_INTEGRATED_ASSEMBLER': '1', 'BC_HOME': '/Users/ur20980/src/bc-java', ...}
expected_returncode = 0, input = None, ignore_returncode = False

    def run_subprocess(command, working_dir='.', env=None, expected_returncode=0, input=None, ignore_returncode=False):
        """
        Helper function to run a shell command and report success/failure
        depending on the exit status of the shell command.
        """
        env_ = os.environ.copy()
        if env is not None:
            env_.update(env)
        env = env_
    
        # Note we need to capture stdout/stderr from the subprocess,
        # then print it, which pytest will then capture and
        # buffer appropriately
        print(working_dir + " > " + " ".join(command))
    
        result = subprocess.run(
                command,
                input=input,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                cwd=working_dir,
                env=env,
            )
    
        if not(ignore_returncode) and (result.returncode != expected_returncode):
            print(result.stdout.decode('utf-8'))
>           assert False, "Got unexpected return code {}".format(result.returncode)
E           AssertionError: Got unexpected return code -11

tests/helpers.py:41: AssertionError
-------------------------------------------- Captured stdout call --------------------------------------------
. > ./build/tests/test_kem HQC-128

_____________________________________________ test_kem[HQC-192] ______________________________________________
[gw17] darwin -- Python 3.9.2 /opt/local/bin/python3

kem_name = 'HQC-192'

    @helpers.filtered_test
    @pytest.mark.parametrize('kem_name', helpers.available_kems_by_name())
    def test_kem(kem_name):
        if not(helpers.is_kem_enabled_by_name(kem_name)): pytest.skip('Not enabled')
>       helpers.run_subprocess(
            [helpers.path_to_executable('test_kem'), kem_name],
        )

tests/test_cmdline.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

command = ['./build/tests/test_kem', 'HQC-192'], working_dir = '.'
env = {'ANT_OPTS': '-Dhttp.proxyHost=llproxy.llan.ll.mit.edu -Dhttp.proxyPort=8080', 'AS': 'yasm -m amd64 -f macho64 -p gas -X gnu ', 'AS_INTEGRATED_ASSEMBLER': '1', 'BC_HOME': '/Users/ur20980/src/bc-java', ...}
expected_returncode = 0, input = None, ignore_returncode = False

    def run_subprocess(command, working_dir='.', env=None, expected_returncode=0, input=None, ignore_returncode=False):
        """
        Helper function to run a shell command and report success/failure
        depending on the exit status of the shell command.
        """
        env_ = os.environ.copy()
        if env is not None:
            env_.update(env)
        env = env_
    
        # Note we need to capture stdout/stderr from the subprocess,
        # then print it, which pytest will then capture and
        # buffer appropriately
        print(working_dir + " > " + " ".join(command))
    
        result = subprocess.run(
                command,
                input=input,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                cwd=working_dir,
                env=env,
            )
    
        if not(ignore_returncode) and (result.returncode != expected_returncode):
            print(result.stdout.decode('utf-8'))
>           assert False, "Got unexpected return code {}".format(result.returncode)
E           AssertionError: Got unexpected return code -11

tests/helpers.py:41: AssertionError
-------------------------------------------- Captured stdout call --------------------------------------------
. > ./build/tests/test_kem HQC-192

========================================== short test summary info ===========================================
FAILED tests/test_cmdline.py::test_kem[HQC-128] - AssertionError: Got unexpected return code -11
FAILED tests/test_cmdline.py::test_kem[HQC-192] - AssertionError: Got unexpected return code -11
================================ 2 failed, 502 passed, 254 skipped in 56.15s =================================
FAILED: tests/CMakeFiles/run_tests
```

**Comment by jschanck** [comment]
Ah. This is not related to the alignment bug, but is due to your stack size limit (512KB?). Turns out the upstream code asks for quite a lot of stack space that it doesn't use. I'll fix it in PQClean.

**Comment by mouse07410** [comment]
> Ah. This is not related to the alignment bug, but is due to your stack size limit (512KB?). 

Interesting...

> Turns out the upstream code asks for quite a lot of stack space that it doesn't use.

And it's only HQC that does it, right?

> I'll fix it in PQClean.

Yes please! Looking forward to the fix.

**Comment by mouse07410** [comment]
Here's the complete crash report - it looks like the stack *size* that my compiler allocates is reasonable, and the problem remains with alignment:
```
Process:               test_kem [56831]
Path:                  /Users/USER/*/test_kem
Identifier:            test_kem
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        Python [55732]
Responsible:           Terminal [7870]
User ID:               501

Date/Time:             2021-04-01 12:22:18.528 -0400
OS Version:            Mac OS X 10.15.7 (19H524)
Report Version:        12
Bridge OS Version:     5.2 (18P4346)
Anonymous UUID:        BD844EB9-9C6F-867E-78EB-1ACDA55970A0


Time Awake Since Boot: 790000 seconds

System Integrity Protection: enabled

Crashed Thread:        1

Exception Type:        EXC_BAD_ACCESS (SIGBUS)
Exception Codes:       KERN_PROTECTION_FAILURE at 0x0000700008919ff8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Bus error: 10
Termination Reason:    Namespace SIGNAL, Code 0xa
Terminating Process:   exc handler [56831]

VM Regions Near 0x700008919ff8:
    __LINKEDIT             000000010bca6000-000000010bcde000 [  224K] r--/r-- SM=COW  /usr/lib/dyld
--> STACK GUARD            0000700008919000-000070000891a000 [    4K] ---/rwx SM=NUL  stack guard for thread 1
    Stack                  000070000891a000-000070000899c000 [  520K] rw-/rwx SM=COW  thread 1

Application Specific Information:
dyld2 mode

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6dda055e __ulock_wait + 10
1   libsystem_pthread.dylib       	0x00007fff6de635c2 _pthread_join + 347
2   test_kem                      	0x000000010550b8e4 main + 740 (test_kem.c:241)

Thread 1 Crashed:
0   libsystem_pthread.dylib       	0x00007fff6de5dbc7 ___chkstk_darwin + 55
1   liboqs.0.6.0-dev.dylib        	0x0000000105910908 PQCLEAN_HQCRMRS128_AVX2_hqc_pke_keygen + 392
2   liboqs.0.6.0-dev.dylib        	0x0000000105910d26 PQCLEAN_HQCRMRS128_AVX2_crypto_kem_keypair + 6 (kem.c:34)

Thread 1 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000123660  rbx: 0x00007000089982c0  rcx: 0x000070000891a000  rdx: 0x00007000089982c0
  rdi: 0x00007000089970c0  rsi: 0x0000700008998bc0  rbp: 0x0000700008997090  rsp: 0x0000700008997050
   r8: 0x00000000000008a0   r9: 0x0000000000000114  r10: 0x00000000000008a0  r11: 0xffffffffffffd230
  r12: 0x00007000089994c0  r13: 0x0000700008999dc0  r14: 0x0000700008998bc0  r15: 0x00007000089970c0
  rip: 0x00007fff6de5dbc7  rfl: 0x0000000000010206  cr2: 0x000070000899a000
  
Logical CPU:     0
Error Code:      0x02000203
Trap Number:     133


Binary Images:
       0x105508000 -        0x10550bff7 +test_kem (0) <745316FC-F4FE-3853-B85B-BEE8205CF55F> /Users/USER/*/test_kem
       0x10551f000 -        0x1061aefcf +liboqs.0.6.0-dev.dylib (0) <85B0B5E3-09A8-3289-9854-4D0DE0CF45B5> /Users/USER/*/liboqs.0.6.0-dev.dylib
       0x106425000 -        0x1065d1b67 +libcrypto.1.1.dylib (0) <0A00315E-F246-3A1C-9E5A-469D46286DB9> /opt/local/lib/libcrypto.1.1.dylib
       0x106667000 -        0x106677ff3 +libz.1.dylib (0) <8553893B-8E4E-3E2C-A558-6EBD9669DF47> /opt/local/lib/libz.1.dylib
       0x10bbd9000 -        0x10bc6af47  dyld (750.6) <326C6480-04F4-3164-A363-53079A148E2F> /usr/lib/dyld
    0x7fff6ac42000 -     0x7fff6ac43fff  libSystem.B.dylib (1281.100.1) <C49167AD-722B-3DF3-9031-7D6B59FC2A06> /usr/lib/libSystem.B.dylib
    0x7fff6af28000 -     0x7fff6af7afff  libc++.1.dylib (902.1) <59A8239F-C28A-3B59-B8FA-11340DC85EDC> /usr/lib/libc++.1.dylib
.  .  .  .  .
    0x7fff6de95000 -     0x7fff6decaffe  libxpc.dylib (1738.140.2) <54EEF402-42C7-3995-BADE-93C48EFC4452> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 104646998
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=410.3M resident=0K(0%) swapped_out_or_unallocated=410.3M(100%)
Writable regions: Total=284.9M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=284.9M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Kernel Alloc Once                    8K        1 
MALLOC                            36.2M       14 
MALLOC guard page                   24K        4 
MALLOC_MEDIUM (reserved)         240.0M        2         reserved VM address space (unallocated)
STACK GUARD                       56.0M        2 
Stack                             8712K        3 
__DATA                             896K       45 
__DATA_CONST                       220K        5 
__LINKEDIT                       391.4M        8 
__OBJC_RO                         32.3M        1 
__OBJC_RW                         1908K        2 
__TEXT                            19.0M       43 
shared memory                        8K        2 
===========                     =======  ======= 
TOTAL                            786.3M      132 
TOTAL, minus reserved VM space   546.3M      132
```

**Comment by mouse07410** [comment]
With the latest commits pushed by @dstebila the build succeeds, and the tests pass. Thank you!

**Comment by jschanck** [comment]
@dstebila If you add `--maxprocesses=10` after `--numprocesses=auto` on line 310 of .circleci/config.yml then the address-sanitizer job should run. Address sanitizer increases memory by a factor of 3.4 and the basic tests run w/o issue with ~35 parallel instances.

**Pull request merged**
