### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jameshoweee**
In order to install liboqs-python I needed to install this package in order to run setup.py on my Mac M1

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Review by baentsch — COMMENTED** [review]
Wouldn't it be more reasonable to add this to [liboqs-python](https://github.com/open-quantum-safe/liboqs-python) instead? Maybe with a suitable requirements.txt for automatic execution? Arguably this README.md should document only items that `liboqs` itself needs.

**Comment by jameshoweee** [comment]
I agree but the python installation instructions link to this repo for the installing

**Comment by jameshoweee** [comment]
Just to be clear, shall I create a requirements.txt file and push all the packages to install liboqs-python there instead?

**Comment by baentsch** [comment]
> shall I create a requirements.txt file 

that would be great -- maybe showing in the text how to use it

> and push all the packages to install liboqs-python there instead?

Now I'm surprised: Are there more packages needed than `setuptools` to run `python3 setup.py install`? I'd have thought all that's missing on https://github.com/open-quantum-safe/liboqs-python/blob/main/README.md is a hint to pip3-install `setuptools` prior to running the install command (or utilize the new requirements.txt in it) . Am I wrong there?

**Comment by jameshoweee** [comment]
The reason I thought about using a `requirements.txt` was to combine the other packages required to install liboqs (i.e.,  `pip3 install pytest pytest-xdist pyyaml` from the liboqs README). But yeah it might be easier to just edit the python-liboqs README and add a line to install `setuptools` for MacOS, does that work?

**Comment by baentsch** [comment]
> does that work?

For me, sure it does/would (Thanks in advance!). 

Just in case you'd feel like contributing more, have a look at https://github.com/open-quantum-safe/liboqs-python/issues/57 (and pardon any possible "obviousness": I'm not a "pythonist").

**Comment by baentsch** [comment]
Replaced by https://github.com/open-quantum-safe/liboqs-python/pull/58

**Pull request closed without merging**
