### PR TITLE
switching to dev mode again

### PR DESCRIPTION
**Pull request by baentsch**
Moving version number forward. Also tests MacOS CI dependencies.

### CODE REVIEW

**Review by dstebila — APPROVED** [review]

**Comment by dstebila** [comment]
In my own dev environment I've been getting annoying python3 failure messages from brew that mention pipx, but I haven't figured out what I'm actually supposed to do.  Is it as simple as using pipx instead of pip3 everywhere?

**Comment by baentsch** [comment]
> In my own dev environment I've been getting annoying python3 failure messages from brew that mention pipx, but I haven't figured out what I'm actually supposed to do. Is it as simple as using pipx instead of pip3 everywhere?

No clue yet. Without local MacOS environment, I'm trying remote CI debugging right now. Turnaround sucks. If you'd have time and a local environment with the same problem, please give it a go.

**Comment by baentsch** [comment]
> since it doesn't do proper package management.

Do we need to care about this in a temporary CI environment? Just giving the option a go....

**Comment by dstebila** [comment]
> > since it doesn't do proper package management.
> 
> Do we need to care about this in a temporary CI environment? Just giving the option a go....

Probably it's fine, give it a try.

**Comment by baentsch** [comment]
> Probably it's fine, give it a try.

Just done -- without DCO/`-s` option, though :-( That anyway makes me wonder: Why did we activate that? Wouldn't it be more reasonable that maintainers add this to commits while reviewing and not contributors? Any documentation how LF wants us to use this feature?

**Comment by baentsch** [comment]
> > Probably it's fine, give it a try.
> 
> Just done -- without DCO/`-s` option, though :-( That anyway makes me wonder: Why did we activate that? Wouldn't it be more reasonable that maintainers add this to commits while reviewing and not contributors? Any documentation how LF wants us to use this feature?

Tagging @ryjones also here: Any documentation that'd help us understand what you want us to do wrt DCO?

**Comment by baentsch** [comment]
For now, I try to remember adding "-s" to commit messages. Not exactly rocket science, but I'm not sure what this buys us (or any other committer). But again, suggest to add this new LF formalism "HowTo" also to https://openquantumsafe.org/about/#getting-started.

**Comment by baentsch** [comment]
@SWilson4 please provide second review and approval to this "quick fix". I think this is acceptable at this time as [OQS did not agree to provide "production grade" software](https://github.com/open-quantum-safe/tsc/issues/1), so an addition like `--break-system-packages` seems "OK" for now.

**Review by praveksharma — APPROVED** [review]

**Pull request merged**
