### PR TITLE
Add NTRU-Prime from PQClean

### PR DESCRIPTION
**Pull request by dstebila**
Commit b4078aae55f9efbc7b3ab7b3c702be376f7a7987

Partially addresses #833 

* [No] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [Yes] Does this PR change the the list of algorithms available -- either adding or removing?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

### CODE REVIEW

**Comment by baentsch** [comment]
@xvzcf Shall we split work to get this ready-for-merge? I'd volunteer to add the new algs to OpenSSL. Could you do Boring and SSH?

**Comment by xvzcf** [comment]
> @xvzcf Shall we split work to get this ready-for-merge? I'd volunteer to add the new algs to OpenSSL. Could you do Boring and SSH?

Sure, will do.

**Review by xvzcf — APPROVED** [review]

**Comment by baentsch** [comment]
openssl is ready for this. Any chance to do openssh (and boringssl) soon, too, @xvzcf ? Reason: Getting closure on this & opportunity to rename master with no open PR. Also, the team doing openssh Docker image are rebasing their stuff right now and might appreciate getting the latest and greatest (openssh) and not adapt again -- but then again, what's life without constant change? :-)

**Comment by xvzcf** [comment]
> openssl is ready for this. Any chance to do openssh (and boringssl) soon, too, @xvzcf ? Reason: Getting closure on this & opportunity to rename master with no open PR. Also, the team doing openssh Docker image are rebasing their stuff right now and might appreciate getting the latest and greatest (openssh) and not adapt again -- but then again, what's life without constant change? :-)

Both BoringSSL and OpenSSH are ready as well.

**Pull request merged**
