### PR TITLE
Patch mechanism for copy from upstream

### PR DESCRIPTION
**Pull request by jschanck**
Opening this PR for discussion around whether we want a patch mechanism for copy from upstream.

This PR contains a functioning patch mechanism. The documentation is here:
https://gist.github.com/jschanck/c67d37551da2a5f6e06c640816d2c99f

### CODE REVIEW

**Comment by bhess** [comment]
The changes look good to me. It's a useful extension for copy_from_upstream when integrating upstream implementations.

Perhaps we could briefly describe in https://gist.github.com/jschanck/c67d37551da2a5f6e06c640816d2c99f the alternatives to (big) patches, such as
- Adding shim API (similar to `src/common/pqclean_shims`) to avoid having to patch namespaces, function names and incompatible API. 
- Offer the patch to upstream, if it is not only for OQS-internal reasons.

**Review by bhess — COMMENTED** [review]
he changes look good to me. It's a useful extension for copy_from_upstream when integrating upstream implementations.

Perhaps we could briefly describe in https://gist.github.com/jschanck/c67d37551da2a5f6e06c640816d2c99f the alternatives to (big) patches, such as

Adding shim API (similar to `src/common/pqclean_shims`) to avoid having to patch namespaces, function names and incompatible API.
Offer the patch to upstream, if it is not only for OQS-internal reasons.

**Comment by baentsch** [comment]
Conceptually, a patch mechanism for upstream code is a good thing, particularly for quick fixes we fully understand. 

My key concern doing this on a regular and long-term basis is this: `liboqs` changes from being an independent maintainer of a collection of unchanged upstream code bases into being the active maintainer (taking responsibility of the internal operations) of certain (such patched) algorithms.

I thus fully agree with @bhess comments
> - Adding shim API (similar to src/common/pqclean_shims) to avoid having to patch namespaces, function names and incompatible API.
> - Offer the patch to upstream, if it is not only for OQS-internal reasons.

and would amend them as follows
- all patches need to be designed such that they can be taken up by upstream
- if the upstream maintainers don't take up the patch by the next run of `copy_from_upstream` and provide their own implementation for the function in question, the patch shall be removed again from liboqs.

This way we can introduce quick improvements without moving into the position of becoming a long-term maintainer of upstream patches. 

If we agree and document all of this, I'm all for this (PR).

**Review by baentsch — APPROVED** [review]

**Comment by baentsch** [comment]
Suggest to update https://github.com/open-quantum-safe/liboqs/wiki/Contributing-guide#automated-inclusion after merge, capturing the jist of the conversation above: Would you want to do this, @jschanck or shall I give it a try after you merged?

**Comment by jschanck** [comment]
> Suggest to update https://github.com/open-quantum-safe/liboqs/wiki/Contributing-guide#automated-inclusion after merge, capturing the jist of the conversation above: Would you want to do this, @jschanck or shall I give it a try after you merged?

I added https://github.com/open-quantum-safe/liboqs/wiki/Patching-upstream-sources and a brief note to https://github.com/open-quantum-safe/liboqs/wiki/Contributing-guide#automated-inclusion

**Pull request merged**
