### PR TITLE
Update to Picnic 3.0.17

### PR DESCRIPTION
**Pull request by sebastinas**
This is the Picnic update for #1278.

* [no] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Comment by sebastinas** [comment]
@christianpaquin Unless I am missing something, the following update should be sufficient for the suppression files. Please double check.

```
diff --git a/tests/constant_time/sig/passes/picnic b/tests/constant_time/sig/passes/picnic
index 2b6b9fd8..bb70481e 100644
--- a/tests/constant_time/sig/passes/picnic
+++ b/tests/constant_time/sig/passes/picnic
@@ -1,3 +1,9 @@
+{
+   The return value of "timingsafe_bcmp" is declassified
+   Memcheck:Cond
+   fun:oqs_sig_picnic_picnic_impl_sign
+   fun:oqs_sig_picnic_sign
+}
 {
    Public, declassified hash
    Memcheck:Cond
diff --git a/tests/constant_time/sig/passes/picnic3 b/tests/constant_time/sig/passes/picnic3
index f2c7b192..62483a53 100644
--- a/tests/constant_time/sig/passes/picnic3
+++ b/tests/constant_time/sig/passes/picnic3
@@ -49,7 +49,7 @@
    fun:keccak_inc_absorb
    fun:OQS_SHA3_shake*_inc_absorb
    fun:hash_update
-   src:picnic3_impl.c:106 # fun:commit
+   src:picnic3_impl.c:109 # fun:commit
    fun:sign_picnic3
 }
 {
@@ -60,23 +60,14 @@
    fun:keccak_inc_absorb
    fun:OQS_SHA3_shake*_inc_absorb
    fun:hash_update
-   src:picnic3_impl.c:106 # fun:commit
-   fun:sign_picnic3
-}
-{
-   use of unitialized value (hash context init in commit)
-   Memcheck:Value8
-   fun:KeccakP1600_AddBytes
-   fun:OQS_SHA3_shake*_inc_absorb
-   fun:hash_update
-   src:picnic3_impl.c:106 # fun:commit
+   src:picnic3_impl.c:109 # fun:commit
    fun:sign_picnic3
 }
 {
    challengeC is declassified
    Memcheck:Cond
    fun:contains
-   src:picnic3_impl.c:673 # fun:sign_picnic3
+   fun:sign_picnic3
    fun:oqs_sig_picnic_impl_sign_picnic3
    fun:oqs_sig_picnic_sign
 }
@@ -84,28 +75,28 @@
    challengeC is declassified
    Memcheck:Cond
    fun:indexOf
-   src:picnic3_impl.c:675 # fun:sign_picnic3
+   src:picnic3_impl.c:741 # fun:sign_picnic3
    fun:oqs_sig_picnic_impl_sign_picnic3
    fun:oqs_sig_picnic_sign
 }
 {
    challengeP is declassified
    Memcheck:Cond
-   src:picnic3_impl.c:686 # fun:sign_picnic3
+   src:picnic3_impl.c:752 # fun:sign_picnic3
    fun:oqs_sig_picnic_impl_sign_picnic3
    fun:oqs_sig_picnic_sign
 }
 {
    challengeP is declassified
    Memcheck:Value8
-   src:picnic3_impl.c:691 # fun:sign_picnic3
+   src:picnic3_impl.c:757 # fun:sign_picnic3
    fun:oqs_sig_picnic_impl_sign_picnic3
    fun:oqs_sig_picnic_sign
 }
 {
    Index of the unopened party is declassified
    Memcheck:Cond
-   src:picnic3_impl.c:695 # fun:sign_picnic3
+   src:picnic3_impl.c:761 # fun:sign_picnic3
    fun:oqs_sig_picnic_impl_sign_picnic3
    fun:oqs_sig_picnic_sign
 }
@@ -113,15 +104,7 @@
    Index of the unopened party is declassified
    Memcheck:Cond
    fun:oqs_sig_picnic_getLeaf
-   src:picnic3_impl.c:696 # fun:sign_picnic3
-   fun:oqs_sig_picnic_impl_sign_picnic3
-   fun:oqs_sig_picnic_sign
-}
-{
-   Index of the unopened party is declassified
-   Memcheck:Value8
-   fun:oqs_sig_picnic_getLeaf
-   src:picnic3_impl.c:696 # fun:sign_picnic3
+   src:picnic3_impl.c:762 # fun:sign_picnic3
    fun:oqs_sig_picnic_impl_sign_picnic3
    fun:oqs_sig_picnic_sign
 }
@@ -129,15 +112,7 @@
    Index of the unopened party is declassified
    Memcheck:Cond
    fun:oqs_sig_picnic_getLeaf
-   src:picnic3_impl.c:699 # fun:sign_picnic3
-   fun:oqs_sig_picnic_impl_sign_picnic3
-   fun:oqs_sig_picnic_sign
-}
-{
-   Index of the unopened party is declassified
-   Memcheck:Value8
-   fun:oqs_sig_picnic_getLeaf
-   src:picnic3_impl.c:699 # fun:sign_picnic3
+   src:picnic3_impl.c:765 # fun:sign_picnic3
    fun:oqs_sig_picnic_impl_sign_picnic3
    fun:oqs_sig_picnic_sign
 }
@@ -152,8 +127,7 @@
 {
    The return value of "timingsafe_bcmp" is declassified
    Memcheck:Cond
-   src:picnic3_simulate.c.i:44 # fun:lowmc_simulate_online_s128_129_43
-   fun:sign_picnic3
+   src:picnic3_impl.c:682 # fun:sign_picnic3
    fun:oqs_sig_picnic_impl_sign_picnic3
    fun:oqs_sig_picnic_sign
 }
```

**Comment by christianpaquin** [comment]
> @christianpaquin Unless I am missing something, the following update should be sufficient for the suppression files. Please double check.

I typically update the suppression files using the suggested output of the tool, so if that's what you did it should be good.

**Comment by christianpaquin** [comment]
Ran this branch locally and I still see the errors
```
tests/test_constant_time.py::test_constant_time_sig[picnic_L1_FS] FAILED                                                     [ 42%]
tests/test_constant_time.py::test_constant_time_sig[picnic_L1_UR] FAILED                                                     [ 43%]
tests/test_constant_time.py::test_constant_time_sig[picnic_L1_full] FAILED                                                   [ 44%]
tests/test_constant_time.py::test_constant_time_sig[picnic_L3_FS] FAILED                                                     [ 45%]
tests/test_constant_time.py::test_constant_time_sig[picnic_L3_UR] FAILED                                                     [ 46%]
tests/test_constant_time.py::test_constant_time_sig[picnic_L3_full] FAILED                                                   [ 47%]
tests/test_constant_time.py::test_constant_time_sig[picnic_L5_FS] FAILED                                                     [ 48%]
tests/test_constant_time.py::test_constant_time_sig[picnic_L5_UR] FAILED                                                     [ 49%]
tests/test_constant_time.py::test_constant_time_sig[picnic_L5_full] FAILED                                                   [ 50%]
tests/test_constant_time.py::test_constant_time_sig[picnic3_L1] FAILED                                                       [ 50%]
tests/test_constant_time.py::test_constant_time_sig[picnic3_L3] FAILED                                                       [ 51%]
tests/test_constant_time.py::test_constant_time_sig[picnic3_L5] FAILED                                                       [ 52%]
```

I'll take a look at the updated exclusion files.

**Comment by christianpaquin** [comment]
I've updated the valgrind constant time exceptions on this PR (feel free to document them better, @sebastinas). The `python3 tests/test_constant_time.py  --verbose` test passes on my machine.

**Comment by baentsch** [comment]
Anything missing to make this Ready for Review (and merge)? With this done, 0.7.2-rc2 should be possible...

**Review by christianpaquin — APPROVED** [review]

**Comment by christianpaquin** [comment]
> Anything missing to make this Ready for Review (and merge)? With this done, 0.7.2-rc2 should be possible...

Ready, as far as I'm concerned.

**Comment by sebastinas** [comment]
It's also ready from my side.

**Comment by baentsch** [comment]
Thanks, @sebastinas @christianpaquin . Merged. Constant-time tests also triggered. If they should pass, OK for RC2, @dstebila (or anything still open in #1281?)?

**Pull request merged**
