### PR TITLE
Add 12 XMSS and 16 XMSSMT parameters.

### PR DESCRIPTION
**Pull request by ducnguyen-sb**
1. All XMSS parameters are separated by namespace.
2. After discussion with Andreas Huelsing, he recommends using the `fast` approach. This approach improved the performance of `signing` at the cost of larger `sk`. 
3. The `_fast` parameters is **incompatible** with the general version. At first, I couldn't believe it, I went back and generate original KATs file from [original Github repo](https://github.com/ducnguyen-sb/xmss-reference-original-kat/pull/1/files). And I confirm that the `_fast` and general version, given the same message and same randomness, it will generate different signatures. Given the signature of `_fast`, the general version cannot verify using `_fast` parameter public key. 

Similar issue in xmss-reference: https://github.com/XMSS/xmss-reference/issues/17

4. All parameters are tested with pre-generated KAT files and SHA256 hashes of the KAT. 

All the parameters added to XMSS. https://github.com/ducnguyen-sb/xmss-reference/blob/master/external/xmss_liboqs_params.md

| Algorithms                    | oid  | sk     | pk  | sig  | n  |
|-------------------------------|------|--------|-----|------|----|
| XMSS-SHA2_10_256              | 0x01 |  1373 |  64 |  2500 | 32 |
| XMSS-SHA2_16_256              | 0x02 |  2093 |  64 |  2692 | 32 |
| XMSS-SHA2_20_256              | 0x03 |  2573 |  64 |  2820 | 32 |
| XMSS-SHAKE_10_256             | 0x07 |  1373 |  64 |  2500 | 32 |
| XMSS-SHAKE_16_256             | 0x08 |  2093 |  64 |  2692 | 32 |
| XMSS-SHAKE_20_256             | 0x09 |  2573 |  64 |  2820 | 32 |
| XMSS-SHA2_10_512              | 0x04 |  2653 | 128 |  9092 | 64 |
| XMSS-SHA2_16_512              | 0x05 |  4045 | 128 |  9476 | 64 |
| XMSS-SHA2_20_512              | 0x06 |  4973 | 128 |  9732 | 64 |
| XMSS-SHAKE_10_512             | 0x0a |  2653 | 128 |  9092 | 64 |
| XMSS-SHAKE_16_512             | 0x0b |  4045 | 128 |  9476 | 64 |
| XMSS-SHAKE_20_512             | 0x0c |  4973 | 128 |  9732 | 64 |
| XMSSMT-SHA2_20/2_256          | 0x01 |  5998 |  64 |  4963 | 32 |
| XMSSMT-SHA2_20/4_256          | 0x02 | 10938 |  64 |  9251 | 32 |
| XMSSMT-SHA2_40/2_256          | 0x03 |  9600 |  64 |  5605 | 32 |
| XMSSMT-SHA2_40/4_256          | 0x04 | 15252 |  64 |  9893 | 32 |
| XMSSMT-SHA2_40/8_256          | 0x05 | 24516 |  64 | 18469 | 32 |
| XMSSMT-SHA2_60/3_256          | 0x06 | 16629 |  64 |  8392 | 32 |
| XMSSMT-SHA2_60/6_256          | 0x07 | 24507 |  64 | 14824 | 32 |
| XMSSMT-SHA2_60/12_256         | 0x08 | 38095 |  64 | 27688 | 32 |
| XMSSMT-SHAKE_20/2_256         | 0x11 |  5998 |  64 |  4963 | 32 |
| XMSSMT-SHAKE_20/4_256         | 0x12 | 10938 |  64 |  9251 | 32 |
| XMSSMT-SHAKE_40/2_256         | 0x13 |  9600 |  64 |  5605 | 32 |
| XMSSMT-SHAKE_40/4_256         | 0x14 | 15252 |  64 |  9893 | 32 |
| XMSSMT-SHAKE_40/8_256         | 0x15 | 24516 |  64 | 18469 | 32 |
| XMSSMT-SHAKE_60/3_256         | 0x16 | 16629 |  64 |  8392 | 32 |
| XMSSMT-SHAKE_60/6_256         | 0x17 | 24507 |  64 | 14824 | 32 |
| XMSSMT-SHAKE_60/12_256        | 0x18 | 38095 |  64 | 27688 | 32 |

7. The upstream of the current code: https://github.com/ducnguyen-sb/xmss-reference

* [x] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [x] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Comment by ducnguyen-sb** [comment]
image

All test pass in local. CI/CD are time out in many platforms.

**Comment by ducnguyen-sb** [comment]
@dstebila I got CI timeout, what can I do to extend the test time longer?

**Comment by ducnguyen-sb** [comment]
Hi @baentsch , 

I think the test is too big, when it reaches to XMSS it's almost out of time. 
On my local machine: Apple M1, all test for XMSS took 1.13 second.

I assume CI is slower, if I multiply my local number by 100x, then it's about ~100 seconds. Still below the 600 seconds (10 minutes). 

Yes, I think the choice of parameters Sign/Verify (we don't test keygen here, because it's very very long) is reasonable. (again, 1 seconds for 28 Sign/Verify test in my local). 

Should I go ahead and modify the timeout? 
Or, How can I just test XMSS to iterate my code quicker?

**Comment by ducnguyen-sb** [comment]
@baentsch I realize that the `test_cmdline.py` actually run the key pair generation. 
So I write a helper so at certain parameters, it should read pre-generated keypair instead of generating one. 

You can see the idea in this section of the code:


https://github.com/open-quantum-safe/liboqs/blob/d7972213947d38e9fa35251f1c95ceec0ef49977/tests/test_sig_stfl.c#L179-L245

Now I don't know why my test on `arm_emulated` return different hash output. That's strange.

**Comment by baentsch** [comment]
> Am I allowed to modify the reference code (as long as same KAT output) to fix the scan_build?

I'd personally say "Yes, of course" -- if that corrects code otherwise containing flaws. Now, on second consideration the question is this: How did you import this reference code? If it's a fully automated process, please consider doing something similar to what we already do in `scripts` with `copy_from_upstream` and `copy_from_xkcp`: In both cases there's the concept of "copy-then-patch". In this case, the patch of course should contain the changes to fix "scan_build" (and you may want to consider contributing those changes upstream such as to eventually completely get rid of them here -- and improve the reference code). If you did the import manually, well, please consider automation: It'll save all of us a lot of problems in the future (that upstream changes or we harden our own tests).

**Comment by ducnguyen-sb** [comment]
>  How did you import this reference code?  

Unfortunately, I import this code manually. The original reference does not: 
1. Separate message and signature
2. Type confusion (unsigned long) 

And it was not [updated for years](https://github.com/XMSS/xmss-reference), due to this I think automation from upstream is a bit overkill. I think my code is a little far ahead of reference implementation. 

I will look into the code to fix `scan_build`.

**Comment by baentsch** [comment]
> I think my code is a little far ahead of reference implementation

Good: That then IMO gives you a clear answer to 

> Am I allowed to modify the reference code

Yes -- by all means: Make this code base the new (better) code base of reference.

**Comment by ducnguyen-sb** [comment]
Scan build is happy. This branch is ready to be merged.

**Review by baentsch — APPROVED** [review]
LGTM to merge to "stateful-sigs". Thanks for the latest code enhancements, @ducnguyen-sb ! For a "main" branch merge, I'm personally missing quite a bit of documentation -- but that's arguably another separate task/PR.

**Pull request merged**
