### PR TITLE
0.10.0 release

### PR DESCRIPTION
**Pull request by dstebila**
Release of liboqs 0.10.0.

Completes https://github.com/open-quantum-safe/liboqs/milestone/23.

* [Yes] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [Yes] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Review by baentsch — APPROVED** [review]
LGTM. Further looks like you ought to commit with "-s", though, as our new LinuxFoundation masters seem to now [enforce DCO](https://github.com/apps/dco): They probably decided this "openly" in one of their members-only chat groups :-)

**Review by bhess — APPROVED** [review]
Thank you Douglas, LGTM! (just one small typo)

**Comment by dstebila** [comment]
Thanks Michael for the typo fix!  If you are willing to do the merge and release, go ahead, not sure I'll get to it in the next few days.

**Comment by baentsch** [comment]
> Thanks Michael for the typo fix! If you are willing to do the merge and release, go ahead, not sure I'll get to it in the next few days.

Done. I hope I got everything right. Good luck with RWC24!

**Comment by dstebila** [comment]
> > Thanks Michael for the typo fix! If you are willing to do the merge and release, go ahead, not sure I'll get to it in the next few days.
> 
> Done. I hope I got everything right. Good luck with RWC24!

Thanks Michael!

**Pull request merged**
