### PR TITLE
fix documentation generation

### LINKED ISSUE #1711: Documentation fails to build corrrectly
**Describe the bug**
```text
Generate XML output for dir /Users/ur20980/src/liboqs/src/sig/
Generate XML output for dir /Users/ur20980/src/liboqs/src/
Generating XML output for the main page
/Users/ur20980/src/liboqs/README.md:17: error: unable to resolve reference to 'linuxmacos' for \ref command
Running plantuml with JAVA...
type lookup cache used 152/65536 hits=476 misses=152
symbol lookup cache used 186/65536 hits=566 misses=186
finished...
Exiting...
FAILED: CMakeFiles/gen_docs /Users/ur20980/src/liboqs/build/CMakeFiles/gen_docs 
cd /Users/ur20980/src/liboqs && /Users/ur20980/src/liboqs/scripts/run_doxygen.sh /opt/local/bin/doxygen /Users/ur20980/src/liboqs/docs/.Doxyfile /Users/ur20980/src/liboqs/build
ninja: build stopped: subcommand failed.
```

**To Reproduce**
Clone and run the build.

**Expected behavior**
Successful generation of docs, of course.

Like
```text
Generating XML output for page options-for-configuring-liboqs-builds
Generate XML output for dir /Users/ur20980/src/liboqs/src/common/
Generate XML output for dir /Users/ur20980/src/liboqs/src/kem/
Generate XML output for dir /Users/ur20980/src/liboqs/src/common/rand/
Generate XML output for dir /Users/ur20980/src/liboqs/src/sig/
Generate XML output for dir /Users/ur20980/src/liboqs/src/
Generating XML output for the main page
Running plantuml with JAVA...
type lookup cache used 152/65536 hits=476 misses=152
symbol lookup cache used 186/65536 hits=566 misses=186
finished...

real	0m0.698s
user	0m0.159s
sys	0m0.108s

Built Doxygen documentation
```

**Fix**
_Note: fix includes updating `.Doxygen` to conform to v1.9.8._

```diff
diff --git a/README.md b/README.md
index 7a51186fe..f9b49615d 100644
--- a/README.md
+++ b/README.md
@@ -14,7 +14,7 @@ liboqs is an open source C library for quantum-safe cryptographic algorithms.
                - [Limitations and Security](#limitations-and-security)
                        - [Platform limitations](#platform-limitations)
        - [Quickstart](#quickstart)
-               - [Linux/macOS](#linuxmacos)
+               - [Linux/macOS](#linux/macOS)
                - [Windows](#windows)
                - [Cross compilation](#cross-compilation)
        - [Documentation](#documentation)
```

and please do
```sh
$ cd docs
$ doxygen -u .Doxyfile
```

### PR DESCRIPTION
**Pull request by baentsch**
Fixes #1711.

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Comment by baentsch** [comment]
This PR does not impact the Travis files, so I'm assuming that stuff if broken asking for someone more knowledgeable regarding those platforms to take a look (@bhess?).

**Review by Martyrshot — APPROVED** [review]

**Comment by baentsch** [comment]
> asking for someone more knowledgeable 

disregard. Travis passes after requesting a re-run.

**Review by bhess — APPROVED** [review]
> This PR does not impact the Travis files, so I'm assuming that stuff if broken asking for someone more knowledgeable regarding those platforms to take a look (@bhess?).

Seems there was a glitch with Travis, I've re-run it and it works now.

**Comment by bhess** [comment]
Looks like Travis errored again after the merge, I've created a ticket with them about the issue.

**Pull request merged**
