### PR TITLE
Adding sig to nist-branch

### PR DESCRIPTION
**Pull request by christianpaquin**
Added sig API with Picnic as first scheme

### CODE REVIEW

**Comment by christianpaquin** [comment]
@dstebila; you can look at this PR. As always, the prettyprint doesn't work on my machine, and it's blocking the first Travis test; could you "make prettyprint" for me, please?

**Comment by manvari** [comment]
Looking at the API changes in `src/sig/sig.h`, it appears that the `OQS_SIG` structure still uses a maximum signature size parameter (namely, `length_signature`).

Similarly to #297, this is a limitation when dealing with variable length signatures. In order to facilitate the integration of schemes with variable length signatures into liboqs, I suggest replacing this with something similar to the NIST API's `CRYPTO_BYTES` parameter. Since it quantifies the maximal amount of "bytes of overhead in a signed message compared to the original message", it makes it that much easier to deal with variable length signatures.

Should we do this, we also get to stick closer to the NIST API, which -- from my understanding -- is @dstebila's intention.

**Comment by christianpaquin** [comment]
@manvari, the `length_signature` value actually uses the `CRYPTO_BYTES` value directly from the upstream implementations, so it is meant to achieve what you say. The name is not very clear, so perhaps I should rename it to `length_signature_overhead` (I find "crypto bytes" to be also confusing :)).

As you noticed, I didn't have time to work on #297; still in the queue...

**Comment by manvari** [comment]
@christianpaquin Thanks for pointing this out! I initially thought `length_signature` matched NIST's `CRYPTO_BYTES`, but the comment above the declaration `size_t signature length` (in `src/sig/sig.h`) reads: 
> /** The (maximum) length, in bytes, of signatures for this signature scheme. */

Along with your suggestion of renaming the value, this could be swapped out for something along the line of:

> /** The length, in bytes, of the maximum overhead in a signed message compared to the original message for this signature scheme. */

I could have looked at Picnic further to see that `#define OQS_SIG_picnic_L1_FS_length_signature 34004` (`src/sig/picnic/sig_picnic.h`) does match `#define CRYPTO_BYTES (4 + 34000)` (`src/sig/picnic/.../picnicl1fs/api.h`). Alas :)

**Comment by christianpaquin** [comment]
Marked no ready for merged. I'm adding qTesla on this PR.

**Comment by christianpaquin** [comment]
Now ready for merged; modulo the Travis checks. Added qTESLA, fixed a few things. @dstebila, I don't know why the first Travis test fails; I don't get an error locally when running make pre-push. I also don't know why the third Travis test fails (on macOS). Perhaps you can identify the problem while reviewing; if not, I can pull out my macOS machine and investigate.

**Comment by dstebila** [comment]
I've got the build fixed for Ubuntu but the build fails on my Mac and on Travis' Mac build, with the same error about `aligned_alloc`.  I see that there are some macros in Picnic's macros.h files that is trying to auto-detected `aligned_alloc`, but they seem to not be working with clang on macOS.  I played around for a bit but couldn't figure out how to get it to work.

**Comment by christianpaquin** [comment]
OK, thanks, I'll investigate.

**Comment by christianpaquin** [comment]
The original Picnic code compiles on macOS (as integrated in the master branch), but the NIST package doesn't out of the box. We can either disable Picnic (and other such packages) in Travis, or integrate more code from Picnic (although this wouldn't be the package as submitted to NIST).

**Comment by dstebila** [comment]
It's fine if we use the authors' preferred version, even if that differs slightly from the NIST submission.  For several of the KEMs on nist-branch already, we're using versions from the authors' websites rather than the exact NIST submission.

**Comment by christianpaquin** [comment]
@dstebila, I disabled picnic and made qtesla the new default, in order to pass merge this PR. Picnic is still available and works on Linux. I'll fix the macOS build in a different PR, in order not to block further progress on sig API.

**Comment by christianpaquin** [comment]
I got an update from the picnic team and integrated the new bits to fix the failing macOS build. One last issue however: aligned_alloc and aligned_free are internal functions that only appear in the macOS build (they are ifdef'ed out in the Linux build). If I had them to symbols_local.txt the build works on macOS and fails on Linux; if I omit them, we have the opposite situation (see last two commits).

@dstebila, do you have a suggestions to deal with that situation?

**Comment by dstebila** [comment]
Oh, that's annoying.  Next week I'll take a look at the scripts that use symbols_local.txt and see if there is way to make them so that they don't fail if they are applied with name that isn't present, should be solvable.

**Comment by christianpaquin** [comment]
I can disable Picnic once more if you want to merge this PR now; and we can fix this on a separate one.

**Comment by dstebila** [comment]
Well maybe let's disable Picnic on macOS for now so we can land this and resolve the issue later.

**Comment by christianpaquin** [comment]
Done; I disabled Picnic and left a comment in the Makefile. Ready to merge again.

**Comment by dstebila** [comment]
BTW @manvari will you be able to resubmit your PR for Falcon against the landed version now on nist-branch?

**Pull request merged**
