### PR TITLE
Added Android CircleCI config

### PR DESCRIPTION
**Pull request by nicholasfulton**
Adds Android CI/CD config for the CircleCI pipeline. Tests whether building library is successful.

Partially addresses Android cross-compilation (#594)

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the the list of algorithms available -- either adding or removing?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

### CODE REVIEW

**Comment by baentsch** [comment]
At first glance I see nothing wrong with these configs. What is the reason they're not added to the active jobs/didn't get run in CCI?

**Comment by nicholasfulton** [comment]
I had added them to the build workflow. I see now that that's explicitly not called on the main branch. What's the reason that the build workflow isn't called when committing to main? In light of this, should I move/copy the Android jobs to "commit-to-main"?

**Comment by baentsch** [comment]
Our preference is to run all tests before new code is committed to main. For some reason I'm not seeing _any_ CCI runs as part of your PR... Are those runs maybe executed within your personal CCI account instead? If so, could you please share a link to those runs?

**Comment by dstebila** [comment]
I've created a copy of this PR as #877 which is inside the OQS repositories so it should trigger the CI.

**Comment by baentsch** [comment]
@nicholasfulton Thanks again for your PR and sorry for the delay. Would you be OK withdrawing this PR when #877 gets merged? Future PRs should be more smooth as we've relaxed the use of docker authentication for CCI.

**Pull request closed without merging**
