### PR TITLE
Sync with PQClean

### LINKED ISSUE #839: NTRU sample.c requires update
The following bug is not fixed here. It applies to all of the NTRU `sample.c` files:
```diff
+++ b/crypto_kem/ntruhps2048677/avx2/sample.c
@@ -24,7 +24,7 @@ void PQCLEAN_NTRUHPS2048677_AVX2_sample_fixed_type(poly *r, const unsigned char
         s[4 * i + 0] =                              (u[15 * i + 0] << 2) + (u[15 * i + 1] << 10) + (u[15 * i + 2] << 18) + ((uint32_t) u[15 * i + 3] << 26);
         s[4 * i + 1] = ((u[15 * i + 3] & 0xc0) >> 4) + (u[15 * i + 4] << 4) + (u[15 * i + 5] << 12) + (u[15 * i + 6] << 20) + ((uint32_t) u[15 * i + 7] << 28);
         s[4 * i + 2] = ((u[15 * i + 7] & 0xf0) >> 2) + (u[15 * i + 8] << 6) + (u[15 * i + 9] << 14) + (u[15 * i + 10] << 22) + ((uint32_t) u[15 * i + 11] << 30);
-        s[4 * i + 3] =  (u[15 * i + 11] & 0xfc)       + (u[15 * i + 12] << 8) + (u[15 * i + 13] << 15) + ((uint32_t) u[15 * i + 14] << 24);
+        s[4 * i + 3] =  (u[15 * i + 11] & 0xfc)       + (u[15 * i + 12] << 8) + (u[15 * i + 13] << 16) + ((uint32_t) u[15 * i + 14] << 24);
     }
 
     for (i = 0; i < NTRU_WEIGHT / 2; i++) {
```

See https://github.com/PQClean/PQClean/issues/342
I believe https://github.com/jschanck/ntru.git has it fixed already.

### PR DESCRIPTION
**Pull request by dstebila**
Syncs with PQClean commit b4078aae55f9efbc7b3ab7b3c702be376f7a7987, excluding HQC

Obsoletes #835

Fixes #839

* [Yes] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [No] Does this PR change the the list of algorithms available -- either adding or removing?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

### CODE REVIEW

**Review by baentsch — COMMENTED** [review]
KAT-changing indicated but version number still at 0.4.0 seems confusing: Wouldn't it be sensible to bump to 0.5.0 the moment a first KAT-change is indicated (as in this PR) since the last release (and not do further version bumps until the next release)?

**Review by baentsch — APPROVED** [review]
> KAT-changing indicated but version number still at 0.4.0 seems confusing: Wouldn't it be sensible to bump to 0.5.0 the moment a first KAT-change is indicated (as in this PR) since the last release (and not do further version bumps until the next release)?

Commenting my own comment: Downstream testing just successfully completed -- incl. a test against all test server ports: That confuses me a bit as the server is 0.4.0 and you indicated KAT-changing changes. (How) can this be? Is there an error in (interop) testing? Anyway I don't see a reason not to merge.

**Comment by dstebila** [comment]
I've bumped to 0.5.0-dev.

It is KAT changing (NTRU changed KATs) but that doesn't necessarily mean incompatibility with previous versions; they could have changed how some randomness is used which would mean keygen doesn't output the same values, but they could still be interoperable.  I suppose that wouldn't force a 0.5.0 bump, but we are planning such a bump anyway.

**Comment by jschanck** [comment]
> I've bumped to 0.5.0-dev.
> 
> It is KAT changing (NTRU changed KATs) but that doesn't necessarily mean incompatibility with previous versions; they could have changed how some randomness is used which would mean keygen doesn't output the same values, but they could still be interoperable. I suppose that wouldn't force a 0.5.0 bump, but we are planning such a bump anyway.

That's right, NTRU-HPS changed KATs because of a small change to randomness expansion: https://github.com/jschanck/ntru/commit/6d1f44f53670b917c3bec9c93a17c43ea806df3d.

**Comment by baentsch** [comment]
Thanks @dstebila @jschanck for addressing/resolving my concerns!

**Pull request merged**
