### PR TITLE
Clear sanitizer warnings

### PR DESCRIPTION
**Pull request by dstebila**
Depends on #633

Before merging:
- [ ] Remove `ubuntu-bionic-x86_64-asan` from build jobs in `.circleci/config.yml`

### CODE REVIEW

**Comment by dstebila** [comment]
@thomwiggers Any idea why we're getting errors in some SPHINCS+ schemes when we run with AddressSanitizer enabled?  Curiously I don't get those errors when I run locally with AddressSanitizer enabled.

**Comment by christianpaquin** [comment]
I'll take a look tomorrow

**Comment by thomwiggers** [comment]
No clue, maybe #641 will help?

**Comment by dstebila** [comment]
I rebased after #641 landed and we're still getting failures with return code `-9` on some CircleCI executions of the AddressSanitizer version.  Annoyingly, I cannot reproduce with `circleci local execute --job ubuntu-bionic-x86_64-asan`.

**Pull request closed without merging**
