### PR TITLE
Update Falcon & McEliece (adding AVX)

### LINKED ISSUE #896: Missing AVX2 version of Classic McEliece
We only pull in the vec (vectorized plain C) implementation of Classic McEliece from PQClean; we should also pull in the avx2 implementation.

### PR DESCRIPTION
**Pull request by baentsch**
Could fix #896 and #917 

Please review initial commit to see changes that led to full PR (running `copy_from_upstream`)

### CODE REVIEW

**Comment by baentsch** [comment]
@jschanck, @dstebila As the code is now building (improving on https://github.com/open-quantum-safe/liboqs/issues/896#issuecomment-780596304 ) would you have time/interest to take a look as to what's happening here with address-sanitizer in (newly added) McEliece-AVX code ?

@bhess Are you OK with the changes done to `copy_from_upstream` (in https://github.com/open-quantum-safe/liboqs/pull/920/commits/d0fc088b6b9a4226ba130e97bcbb5cb326cb738a)

Anyone, maybe @xvzcf (as I have no experience whatsoever with this): Any idea what this is?

> /usr/bin/ld: src/kem/classic_mceliece/CMakeFiles/classic_mceliece_348864_avx.dir/pqclean_mceliece348864_avx/transpose_64x256_sp_asm.S.o: relocation R_X86_64_PC32 against symbol `PQCLEAN_MCELIECE348864_AVX_MASK5_0' can not be used when making a shared object; recompile with -fPIC

**Comment by bhess** [comment]
> @bhess Are you OK with the changes done to `copy_from_upstream` (in [d0fc088](https://github.com/open-quantum-safe/liboqs/commit/d0fc088b6b9a4226ba130e97bcbb5cb326cb738a))

Looks good.

**Comment by dstebila** [comment]
> @jschanck, @dstebila As the code is now building (improving on [#896 (comment)](https://github.com/open-quantum-safe/liboqs/issues/896#issuecomment-780596304) ) would you have time/interest to take a look as to what's happening here with address-sanitizer in (newly added) McEliece-AVX code ?

It seems like one of the keywords used in this file is a language extension, which clang with `-Wpendatic` [doesn't like](https://github.com/RIOT-OS/RIOT/issues/4560).

One fix is to add the following to `.CMake/compiler_opts.cmake` in the AddressSanitizer section:

```
add_compile_options(-Wno-language-extension-token)
```

I verified locally that the CircleCI AddressSanitizer workflow passes with that option.

**Review by dstebila — APPROVED** [review]

**Review by bhess — APPROVED** [review]

**Comment by dstebila** [comment]
Oh, don't forget to update the algorithm data sheets in the docs folder.

**Review by dstebila — APPROVED** [review]

**Pull request merged**
