### PR TITLE
Add AES using AES-NI.

### PR DESCRIPTION
**Pull request by dstebila**
Based on #28.

### CODE REVIEW

**Comment by aparent** [comment]
I noticed you dropped `monte_test` functions.  The equivalence test is probably ok.  I added the `monte_test` functions because they were specified in http://csrc.nist.gov/groups/STM/cavp/documents/aes/AESAVS.pdf.

**Comment by aparent** [comment]
I can add in the validation file and a check that the test generates it exactly.

**Comment by dstebila** [comment]
That would be great, thanks Alex!

**Comment by dstebila** [comment]
I didn't realize that there were tests like that specified by the standard, so it would be good to have them in as well.

**Pull request merged**
