### PR TITLE
Remove kex_ntru (issue #370).

### PR DESCRIPTION
**Pull request by truth-quark**
1st shot at removing kex_ntru.
https://github.com/open-quantum-safe/liboqs/issues/370

References to ntru exist in the visual studio project files. I don't have windows at all, so didn't touch that part.

### CODE REVIEW

**Comment by truth-quark** [comment]
This also needs a new example algorithm in the docs for kex_bench_memory.sh

**Comment by dstebila** [comment]
All of the KEX stuff is going away as part of #372 so maybe it's easier to do that here?

**Comment by truth-quark** [comment]
> All of the KEX stuff is going away as part of #372 so maybe it's easier to do that here?

Yes, I don't mind if someone continues Win work on this branch.

Who is handling the windows/VS stuff again?

**Comment by dstebila** [comment]
This will need to be updated from master since the merges have landed for removing kex\_code\_mcbits, kex\_sidh\_msr, and removing all kex stuff from VisualStudio.

**Comment by truth-quark** [comment]
UPDATE: work moved to https://github.com/open-quantum-safe/liboqs/pull/390

**Pull request closed without merging**
