### PR TITLE
Fix build failure on Visual Studio x86

### PR DESCRIPTION
**Pull request by christianpaquin**
This fixes a build failure on Visual Studio x86 (SIKE wasn't recognizing this as a valid platform). Also adds x86 as an appveyor test platform.

### CODE REVIEW

**Comment by dstebila** [comment]
CircleCI and AppVeyor builds didn't get triggered.  I just changed a setting which I think should cause CircleCI to get properly triggered for PRs from forks.  Not sure what went wrong with AppVeyor.  Any thoughts, @vsoftco?

**Comment by vsoftco** [comment]
@dstebila I'll take a look asap

**Comment by christianpaquin** [comment]
I changed the appveyor script to add x86. Did I screw it up? Anyway to check locally, @vsoftco?

**Comment by vsoftco** [comment]
@christianpaquin No idea what's going on that appveyor is not triggered. That's the way to add more platforms, so nothing wrong with the appveyor.yml

**Comment by dstebila** [comment]
I backed this out because it was causing build failures.  We'll need to revisit.

**Pull request merged**
