### PR TITLE
Update OpenSSH downstream branch to OQS-v9

### PR DESCRIPTION
**Pull request by SWilson4**
As per https://github.com/open-quantum-safe/openssh/issues/166.

~* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)~
~* [ ] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for review and merge by the time this is merged.)~

### CODE REVIEW

**Comment by SWilson4** [comment]
@geedo0 You'll need to set the workflow in OpenSSH to be triggered on `workflow_dispatch` events.

**Comment by geedo0** [comment]
Ack, added the trigger to the [PR here](https://github.com/open-quantum-safe/openssh/pull/168).

**Comment by SWilson4** [comment]
Apparently the GitHub trigger won't do anything unless the downstream workflow is on the default branch: see https://github.com/open-quantum-safe/openssh/pull/168#issuecomment-2302614810 for discussion.

**Comment by SWilson4** [comment]
Trigger tested on commit [caea971](https://github.com/open-quantum-safe/liboqs/pull/1898/commits/caea9711f3df758c9a7b109d7e879e9056bd8b05): see the [upstream](https://github.com/open-quantum-safe/liboqs/actions/runs/10495474375) and and [downstream](https://github.com/open-quantum-safe/openssh/actions/runs/10495477066) runs. For testing, I disabled the other downstream triggers and set the workflow to be triggered on pushes to this branch; the most recent commit reverts these changes.

**Review by dstebila — APPROVED** [review]

**Review by geedo0 — APPROVED** [review]

**Review by praveksharma — APPROVED** [review]

**Pull request merged**
