### PR TITLE
Refactored CI.

### PR DESCRIPTION
**Pull request by xvzcf**
Refactored CI configuration to:

- Use CircleCI 2.1 syntax
- Remove nightly jobs and build all jobs in PRs by default
- Reorganize the execution of jobs
- Trigger downstream CI in OpenSSL, OpenSSH, BoringSSL upon a merge to master

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the the list of algorithms available -- either adding or removing?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

### CODE REVIEW

**Review by baentsch — APPROVED** [review]
Looks good to me incl. the "win-" removal (relying on AppVeyor instead) and more simple shared lib namespace testing. One question/suggestion for improvement if I may: What about a mechanism (e.g., based on checkin message or branch name) to trigger downstream tests even before merge to master?

**Review by dstebila — APPROVED** [review]

**Comment by xvzcf** [comment]
> What about a mechanism (e.g., based on checkin message or branch name) to trigger downstream tests even before merge to master?

This is on my TODO list. The ideal way would've been to differentiate between draft/non-draft PRs in CircleCI, but it seems like that functionality isn't available yet.

**Comment by baentsch** [comment]
> This is on my TODO list. The ideal way would've been to differentiate between draft/non-draft PRs in CircleCI, but it seems like that functionality isn't available yet.

Agree. Until then, what about the ability to trigger this with a PR for a(ny) branch ending with "-rft" (request full test) or the like? This could alleviate manual/local testing efforts and eliminate merge-only "surprises".

**Comment by xvzcf** [comment]
> Agree. Until then, what about the ability to trigger this with a PR for a(ny) branch ending with "-rft" (request full test) or the like? This could alleviate manual/local testing efforts and eliminate merge-only "surprises".

Let me think about this a little bit more.

**Pull request merged**
