### PR TITLE
Added Picnic to the Windows build

### PR DESCRIPTION
**Pull request by christianpaquin**
Added Picnic to the Visual Studio project. 
 - Modified AppVeyor to add test_sig
 - Modified VS projects and solution to include Picnic (both as static and dynamic lib, depending on project)
 - Removed x86 projects (unused, and unsupported by Picnic)
 - Added sig functions to DLL exports

### CODE REVIEW

**Comment by christianpaquin** [comment]
@dstebila; ready for merge.

**Comment by dstebila** [comment]
I'll look at resolving the conflict tonight, unless someone gets to it first.

**Comment by vsoftco** [comment]
It's just the "oqs.h" header that I've added and Christian did not in his VS solution. I'll take care of it.

**Comment by vsoftco** [comment]
@dstebila @christianpaquin Ready to merge, we have lots of warnings from Picnic though

**Comment by christianpaquin** [comment]
I'll also add some defines to enable all KEX schemes; they are not run by the test since the addition of the per-scheme ifdef in test_kex.

**Comment by vsoftco** [comment]
@christianpaquin Can you please add minimal_kex(sig)_oqs into the build as well? Thanks!

**Comment by christianpaquin** [comment]
@vsoftco, I'll add the minimal test projects in a different PR.

**Pull request merged**
