### PR TITLE
bug fix on return value

### PR DESCRIPTION
**Pull request by vsoftco**

### CODE REVIEW

**Comment by dstebila** [comment]
In fact we have long-standing issue #474 about potentially changing this behaviour.  Thoughts on how to proceed?  We could add a function like `bool OQS_KEM_is_enabled(const char *method_name)`, and keep `OQS_KEM_new` returning NULL both when the KEM is disabled or when an allocation error occurs.

**Comment by vsoftco** [comment]
> In fact we have long-standing issue #474 about potentially changing this behaviour. Thoughts on how to proceed? We could add a function like `bool OQS_KEM_is_enabled(const char *method_name)`, and keep `OQS_KEM_new` returning NULL both when the KEM is disabled or when an allocation error occurs.

But definitely we shouldn't `return OQS_SUCCESS;`, right?

**Comment by christianpaquin** [comment]
A different return value for "error" and "not enabled" would make sense. Perhaps even add a 3rd option "not supported", like we do in the wrappers.

**Comment by vsoftco** [comment]
@christianpaquin Agree, I'll think about it and propose a fix soon

**Comment by dstebila** [comment]
#530 is meant to solve the same issue. Closing this PR to focus work on that one.

**Pull request closed without merging**
