### PR TITLE
Update Picnic to 3.0.14 (fixes #1212)

### LINKED ISSUE #1212: scan-build warnings in Picnic
@christianpaquin Running scan-build (inspired by the very old #193; see #1211 for details on how to run scan-build now) yields the following.

```
/Users/dstebila/Dev/OQS/liboqs/src/sig/picnic/external/picnic3_types.c:37:19: warning: Potential leak of memory pointed to by 'slab' [unix.Malloc]
  tape->pos     = 0;
                  ^
/Users/dstebila/Dev/OQS/liboqs/src/sig/picnic/external/picnic3_types.c:153:10: warning: Potential leak of memory pointed to by 'slab' [unix.Malloc]
  return msgs;
         ^~~~
/Users/dstebila/Dev/OQS/liboqs/src/sig/picnic/external/picnic3_types.c:198:10: warning: Potential leak of memory pointed to by 'slab' [unix.Malloc]
  return commitments;
         ^~~~~~~~~~~
3 warnings generated.

/Users/dstebila/Dev/OQS/liboqs/src/sig/picnic/external/picnic3_impl.c:221:14: warning: Use of zero-allocated memory [unix.Malloc]
      setBit(tapes->tape[last], params->lowmc.n + params->lowmc.n * 2 * (j) + i,
             ^~~~~~~~~~~
/Users/dstebila/Dev/OQS/liboqs/src/sig/picnic/external/picnic3_impl.c:271:38: warning: Division by zero [core.DivideZero]
      calloc(params->digest_size * 8 / MIN(bitsPerChunkP, bitsPerChunkC), sizeof(uint16_t));
             ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/dstebila/Dev/OQS/liboqs/src/sig/picnic/external/picnic3_impl.c:477:12: warning: Use of zero-allocated memory [unix.Malloc]
    memset(tapes[t].tape[unopened], 0, 2 * params->view_size);
           ^~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/secure/_string.h:77:27: note: expanded from macro 'memset'
                __builtin___memset_chk (dest, __VA_ARGS__, __darwin_obsz0 (dest))
                                        ^~~~
3 warnings generated.

/Users/dstebila/Dev/OQS/liboqs/src/sig/picnic/external/picnic3_tree.c:322:22: warning: Dereference of undefined pointer value [core.NullDereference]
    pathSets[pos][i] = node;
    ~~~~~~~~~~~~~~~~~^~~~~~
/Users/dstebila/Dev/OQS/liboqs/src/sig/picnic/external/picnic3_tree.c:325:24: warning: Dereference of undefined pointer value [core.NullDereference]
      pathSets[pos][i] = node;
      ~~~~~~~~~~~~~~~~~^~~~~~
/Users/dstebila/Dev/OQS/liboqs/src/sig/picnic/external/picnic3_tree.c:353:3: warning: 1st function call argument is an uninitialized value [core.CallAndMessage]
  free(pathSets[0]);
  ^~~~~~~~~~~~~~~~~
/Users/dstebila/Dev/OQS/liboqs/src/sig/picnic/external/oqs_picnic_macros.h:12:14: note: expanded from macro 'free'
#define free OQS_MEM_insecure_free
             ^
3 warnings generated.
```

### PR DESCRIPTION
**Pull request by sebastinas**
This commit also corrects incorrect information in picnic.yml

* [no] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

### CODE REVIEW

**Review by christianpaquin — APPROVED** [review]
Thanks Sebastian!

**Review by dstebila — APPROVED** [review]

**Comment by dstebila** [comment]
Looks good to me. Are you planning any other changes, @sebastinas, or is it okay to merge?

**Comment by sebastinas** [comment]
I don't have any other changes lined up. It's ready to be merged.

**Review by baentsch — COMMENTED** [review]
Sorry to be the killjoy: This PR indeed corrects the documentation and improves the `scan-build` report, but does not fully resolve #1212:
```
~/git/oqs/liboqs/build$ scan-build ninja
scan-build: Using '/usr/lib/llvm-6.0/bin/clang' for static analysis
[0/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mib/git/oqs/liboqs/build
[84/1275] Building C object src/sig/picnic/CMakeFiles/picnic.dir/external/picnic3_types.c.o
../src/sig/picnic/external/picnic3_types.c:153:10: warning: Potential leak of memory pointed to by 'slab'
  return msgs;
         ^~~~
../src/sig/picnic/external/picnic3_types.c:176:10: warning: Potential leak of memory pointed to by 'slab'
  return msgs;
         ^~~~
../src/sig/picnic/external/picnic3_types.c:204:10: warning: Potential leak of memory pointed to by 'slab'
  return commitments;
         ^~~~~~~~~~~
3 warnings generated.
[138/1275] Building C object src/sig/picnic/CMakeFiles/picnic.dir/external/picnic3_tree.c.o
../src/sig/picnic/external/picnic3_tree.c:381:7: warning: Assigned value is garbage or undefined
      unsigned int node = pathSets[d * hideListSize + i];
      ^~~~~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
[1275/1275] Linking C executable tests/speed_common
scan-build: 4 bugs found.
scan-build: Run 'scan-view /tmp/scan-build-2022-06-28-073042-12866-1' to examine bug reports.
~/git/oqs/liboqs/build$ git status
Auf Branch ds-picnic-3.0.14
```
CI is "green" as `scan-build` is currently not part of CI. My suggestion would be to first do #1239, rebasing and completing this PR before merge.

**Pull request merged**
