### PR TITLE
Improved argument passing for cpu_features

### PR DESCRIPTION
**Pull request by gadoofou87**
Addition for PR https://github.com/open-quantum-safe/liboqs/pull/681 . Removes warnings like this
```
CMake Warning (dev) at C:/projects/liboqs/build/cpu_features-build/CMakeFiles/3.16.5/CMakeRCCompiler.cmake:1:
  Syntax Warning in cmake code at column 25
  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/Platform/Windows-GNU.cmake:138 (enable_language)
  C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/Platform/Windows-GNU-C.cmake:2 (__windows_compiler_gnu)
  C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/CMakeCInformation.cmake:48 (include)
  CMakeLists.txt:9 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe
CMake Warning (dev) at C:/projects/liboqs/build/cpu_features-build/CMakeFiles/3.16.5/CMakeRCCompiler.cmake:1:
  Syntax Warning in cmake code at column 25
  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/Platform/Windows-GNU.cmake:138 (enable_language)
  C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/Platform/Windows-GNU-C.cmake:2 (__windows_compiler_gnu)
  C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/CMakeCInformation.cmake:48 (include)
  C:/projects/liboqs/build/cpu_features-build/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe -- works
-- Detecting C compiler ABI info
CMake Warning (dev) at C:/projects/liboqs/build/cpu_features-build/CMakeFiles/3.16.5/CMakeRCCompiler.cmake:1:
  Syntax Warning in cmake code at column 25
  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/Platform/Windows-GNU.cmake:138 (enable_language)
  C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/Platform/Windows-GNU-C.cmake:2 (__windows_compiler_gnu)
  C:/Program Files (x86)/CMake/share/cmake-3.16/Modules/CMakeCInformation.cmake:48 (include)
  C:/projects/liboqs/build/cpu_features-build/CMakeFiles/CMakeTmp/CMakeLists.txt:2 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

### CODE REVIEW

**Comment by baentsch** [comment]
Reading through the changes, this looks good to me. @xvzcf Would you agree this is good to merge?

**Comment by baentsch** [comment]
@gadoofou87 One question regarding understanding the `cpu_features` integration: If I'm not mistaken, `cpu_features` should build position independent code if we set `-DBUILD_SHARED_LIBS=ON` flag (set in the main `liboqs` build) as per `cpu_features-src/CMakeLists.txt`:
```
if(BUILD_SHARED_LIBS AND UNIX)
  set(BUILD_PIC ON)
endif()
```
Is that correct? Now, when doing that, can you explain why am I'm now getting this error message:
```
/usr/bin/ld: test_kem: hidden symbol `GetX86Info' in ../cpu_features-build/libcpu_features.a(cpuinfo_x86.c.o) is referenced by DSO
/usr/bin/ld: final link failed: Bad value
```

Am I declaring `cpu_features` somewhere incorrectly in the "consuming" targets? I'm doing this
```
if(DEFINED CPUFEATURES_LIBRARY)
    target_link_libraries(test_kem PUBLIC ${CPUFEATURES_LIBRARY})
endif()
```
with the goal to only load the PIC symbols (but not the reference to a shared lib/`cpu_features`).

Or am I making a mistake in thinking (that linking in symbols from static, but PIC-built objects into an executable or other [shared] library should be possible -- such as to drop the need to carry forward the shared library version of `cpu_features`)?

**Comment by gadoofou87** [comment]
@baentsch I found a potential mistake. `cpu_features` uses parameter `BUILD_PIC` instead of `CMAKE_POSITION_INDEPENDENT_CODE`. Fixed it in the last commit. Can you try it again?

**Comment by baentsch** [comment]
@gadoofou87 Thanks for the quick reaction. But the real error was mine: I didn't add `cpu_features` to the `oqs` lib build instruction like this
```
if(DEFINED CPUFEATURES_LIBRARY)
    target_link_libraries(oqs PRIVATE ${CPUFEATURES_LIBRARY})
endif()
```
but only to its apps. After adding the above, all was fine: Linker linked, functionality... functioned :-)

**Pull request merged**
