### PR TITLE
Document Fix

### PR DESCRIPTION
**Pull request by pi-314159**
Update links, fix typos, and make the README clearer

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Review by baentsch — APPROVED** [review]
LGTM. This change IMO brings back BoringSSL as a supported sub project: Thanks for that committment,  @pi-314159 !

**Comment by pi-314159** [comment]
@dstebila Could you take a look at this doc update? Thank you!

**Review by dstebila — APPROVED** [review]

**Comment by pi-314159** [comment]
@baentsch Could you retry the merge? DCO should be fixed now.

**Comment by baentsch** [comment]
> @baentsch Could you retry the merge? DCO should be fixed now.

Thanks for the DCO fix. Will merge after https://github.com/open-quantum-safe/liboqs/pull/1743 landed (I hate CI failing during PR).

**Comment by baentsch** [comment]
[Github CI seems to be in pretty bad shape right now](https://downdetector.com/status/github/). Would anyone in a non-EU timezone please retry as/when fixed, e.g., @praveksharma ?

**Review by SWilson4 — APPROVED** [review]
Thanks very much, @pi-314159!

**Comment by pi-314159** [comment]
@SWilson4 Could you retry the merge?

**Pull request merged**
