### PR TITLE
Adding multiple upstream support to doc generation

### PR DESCRIPTION
**Pull request by Martyrshot**
This PR fixes an issue discovered by  Michael (https://github.com/open-quantum-safe/liboqs/pull/1117#issuecomment-969116802).

This will update legacy yaml files so that the new format is followed, and when a yaml file is updated the script it indicate it has done so. When this happens I recommend double checking the yaml file to make sure the ordering "makes sense" to human eyes.

I also manually patched the yaml files of schemes that the copy_from_upstream.py script doesn't manage.

### CODE REVIEW

**Review by baentsch — CHANGES_REQUESTED** [review]
Thanks for this update! The litmus test this passes is successful execution of `python3 copy_from_upstream.py copy`, right? There is one step missing though (and I wonder why we have not automated that): Running `python3 update_docs_from_yaml.py` to generate the .MD files: Those should be the files we read/check (treating the YML files only as intermediate/machine representations). If you rightfully want to go to bed now I'll manually run this from your repo to check things. Before merge, however, please amend the PR with the results of running that script too. Also I wonder why this PR contains so many commits (?)

**Comment by Martyrshot** [comment]
Hm, that's really odd. Did scripts/update_docs_from_yaml.py get updated when you pulled? The version in the PR doesn't have the line that is causing the error: https://github.com/open-quantum-safe/liboqs/blob/aa4beb1b394e34c35f76ceac7456a790079a34e5/scripts/update_docs_from_yaml.py#L44

I just tried re-cloning my main branch and running the scripts from scratch and it works on my local machine.

**Comment by Martyrshot** [comment]
> Thanks for this update! The litmus test this passes is successful execution of `python3 copy_from_upstream.py copy`, right? There is one step missing though (and I wonder why we have not automated that): Running `python3 update_docs_from_yaml.py` to generate the .MD files: Those should be the files we read/check (treating the YML files only as intermediate/machine representations). 

I can add this no problem, I wasn't sure if there was a reason it was handled in to separate steps or not so I left it as is. :)


> Before merge, however, please amend the PR with the results of running that script too.

Would this cause an issue for git commits? I think there are a few schemes we have pulled in that are on a different commit than what the doc scripts will update to.

**Comment by baentsch** [comment]
> I can add this no problem, I wasn't sure if there was a reason it was handled in to separate steps or not so I left it as is. :)

I don't know either :( Maybe @xvzcf might know (?)

> Would this cause an issue for git commits? I think there are a few schemes we have pulled in that are on a different commit than what the doc scripts will update to.

I was of the opinion that `copy_from_upstream.yml` is _the_ master file defining _all_ upstream (origins) without exception (beyond those algorithms that are manually added to `liboqs`) and that `update_docs_from_yaml.py` simply is converting all (machine-readable) YMLs to (human-readable) MDs (absolutely independently of algorithm provenance). Both should have no commit-dependency (or maybe I misunderstand the question).

**Comment by Martyrshot** [comment]
> I was of the opinion that `copy_from_upstream.yml` is _the_ master file defining _all_ upstream (origins) without exception (beyond those algorithms that are manually added to `liboqs`) and that `update_docs_from_yaml.py` simply is converting all (machine-readable) YMLs to (human-readable) MDs (absolutely independently of algorithm provenance). Both should have no commit-dependency (or maybe I misunderstand the question).

That is my understanding as well. The concern I have though is it looks like a few of our schemes aren't haven't been updated to the latest version of pqclean.

Example: Kyber is on commit faf5c3fe33e0b61c7c8a7888dd862bf5def17ad2 and hqc is on commit 5b8ef3baea3ffdfbf688a3a1bb8f02de44a67ec0.

If we run the script to update everything then the commits will be lost along the way and (some of) our updated docs will referencing the wrong commit.

**Comment by baentsch** [comment]
> I just tried re-cloning my main branch and running the scripts from scratch and it works on my local machine.

Sorry, I wasn't clear what I tried: I wanted to check that (only) the scripts are running OK on the current `liboqs` (main). I thus only copied over the files `copy_from_upstream.py`, `update_upstream_alg_docs.py` and `update_docs_from_yaml.py` (from martyrshot/updating-docs-for-multiple-upstreams) and then executed those in liboqs main, but to no avail:

```
$ python3 copy_from_upstream.py copy
Traceback (most recent call last):
  File "copy_from_upstream.py", line 658, in <module>
    copy_from_upstream()
  File "copy_from_upstream.py", line 587, in copy_from_upstream
    update_upstream_alg_docs.do_it(os.environ['LIBOQS_DIR'])
  File "/home/mib/git/oqs/liboqs/scripts/copy_from_upstream/update_upstream_alg_docs.py", line 305, in do_it
    update_upstream_kem_alg_docs(liboqs_root, instructions['kems'], instructions['upstreams'], write_changes)
  File "/home/mib/git/oqs/liboqs/scripts/copy_from_upstream/update_upstream_alg_docs.py", line 117, in update_upstream_kem_alg_docs
    oqs_yaml['primary-upstream']['source'] = rhs_if_not_equal(oqs_yaml['primary-upstream']['source'], ("{}/commit/{}"+patches_done).format(upstream_base_url, ui['git_commit']), "primary-upstream")
KeyError: 'primary-upstream'
```

Now --not cutting corners any more-- I just cloned martyrshot/liboqs and moved to branch "updating-docs-for-multiple-upstreams" and ran these in their respective directories:
```
$ python3 copy_from_upstream.py copy
$ python3 update_docs_from_yaml.py
``` 
--> As you stated, no errors. So my corner-cutting (by just copying the scripts from your PR) was wrong. But what surprises me now is that git status is not empty at all (running these scripts should not result in anything new on this branch, right?) but rather:
```
$ git status
Auf Branch updating-docs-for-multiple-upstreams
Ihr Branch ist auf demselben Stand wie 'origin/updating-docs-for-multiple-upstreams'.

Änderungen, die nicht zum Commit vorgemerkt sind:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)
  (benutzen Sie "git checkout -- <Datei>...", um die Änderungen im Arbeitsverzeichnis zu verwerfen)

	geändert:       docs/algorithms/kem/kyber.md
	geändert:       docs/algorithms/kem/kyber.yml
	geändert:       docs/algorithms/sig/falcon.md
	geändert:       docs/algorithms/sig/rainbow.md
	geändert:       docs/algorithms/sig/sphincs.md
	geändert:       src/kem/classic_mceliece/kem_classic_mceliece_348864.c
	geändert:       src/kem/classic_mceliece/kem_classic_mceliece_348864f.c
	geändert:       src/kem/classic_mceliece/kem_classic_mceliece_460896.c
	geändert:       src/kem/classic_mceliece/kem_classic_mceliece_460896f.c
	geändert:       src/kem/classic_mceliece/kem_classic_mceliece_6688128.c
	geändert:       src/kem/classic_mceliece/kem_classic_mceliece_6688128f.c
	geändert:       src/kem/classic_mceliece/kem_classic_mceliece_6960119.c
	geändert:       src/kem/classic_mceliece/kem_classic_mceliece_6960119f.c
	geändert:       src/kem/classic_mceliece/kem_classic_mceliece_8192128.c
	geändert:       src/kem/classic_mceliece/kem_classic_mceliece_8192128f.c
	geändert:       src/kem/hqc/kem_hqc_128.c
	geändert:       src/kem/hqc/kem_hqc_192.c
	geändert:       src/kem/hqc/kem_hqc_256.c
	geändert:       src/kem/kyber/kem_kyber_1024.c
	geändert:       src/kem/kyber/kem_kyber_1024_90s.c
	geändert:       src/kem/kyber/kem_kyber_512.c
	geändert:       src/kem/kyber/kem_kyber_512_90s.c
	geändert:       src/kem/kyber/kem_kyber_768.c
	geändert:       src/kem/kyber/kem_kyber_768_90s.c
	geändert:       src/kem/ntru/kem_ntru_hps2048509.c
	geändert:       src/kem/ntru/kem_ntru_hps2048677.c
	geändert:       src/kem/ntru/kem_ntru_hps4096821.c
	geändert:       src/kem/ntru/kem_ntru_hrss701.c
	geändert:       src/kem/ntruprime/kem_ntruprime_ntrulpr1277.c
	geändert:       src/kem/ntruprime/kem_ntruprime_ntrulpr653.c
	geändert:       src/kem/ntruprime/kem_ntruprime_ntrulpr761.c
	geändert:       src/kem/ntruprime/kem_ntruprime_ntrulpr857.c
	geändert:       src/kem/ntruprime/kem_ntruprime_sntrup1277.c
	geändert:       src/kem/ntruprime/kem_ntruprime_sntrup653.c
	geändert:       src/kem/ntruprime/kem_ntruprime_sntrup761.c
	geändert:       src/kem/ntruprime/kem_ntruprime_sntrup857.c
	geändert:       src/kem/saber/CMakeLists.txt
	geändert:       src/kem/saber/kem_saber_firesaber.c
	geändert:       src/kem/saber/kem_saber_lightsaber.c
	geändert:       src/kem/saber/kem_saber_saber.c

Unversionierte Dateien:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)

	src/kem/saber/pqclean_firesaber_aarch64/
	src/kem/saber/pqclean_lightsaber_aarch64/
	src/kem/saber/pqclean_saber_aarch64/

keine Änderungen zum Commit vorgemerkt (benutzen Sie "git add" und/oder "git commit -a")
```
(Sorry for the German, but my Linux just feels "like it" :)

So: I can confirm your PR is OK -- but don't understand why it changes files when (re-)running the copy/doc-update commands.

**Comment by Martyrshot** [comment]
All of the src/* files will be copy from upstream using the new template format, which looks like it has an indenting issue. I've fixed that issue as part of this PR.

The docs/algorithms/sigs getting updated to the pqclean commit specified in copy_from_upstream.yml

The docs/algorithms/kems will be a combination of an updated pqclean commit and the new yaml and markdown format.

No worries about the german. Maybe more exposure to it will encourage me to start taking lessons again. :-)

**Review by baentsch — CHANGES_REQUESTED** [review]
Thanks again for the improvements: Some issues observed in the previous review are gone. 
However IMO this PR --like any PR touching these scripts and config files-- should
- contain the algorithm documentation MDs corresponding to the changed YMLs (i.e., as resultant from running `scripts/update_docs_from_yaml.py`)
- ensure that running `scripts/copy_from_upstream/copy_from_upstream.py` (followed by `scripts/update_docs_from_yaml.py`) does not result in any changes to the git repo's local state (such as to ensure further changes to `scripts/copy_from_upstream/copy_from_upstream.yml` do not lead to any changes other than those driven by changes to that file).

When running the first command on `martyrshot/main`, this happens:
```
~/git/martyrshot/liboqs$ git status
Auf Branch main
Ihr Branch ist auf demselben Stand wie 'origin/main'.

nichts zu committen, Arbeitsverzeichnis unverändert
~/git/martyrshot/liboqs$ python3 scripts/update_docs_from_yaml.py 
Updating ./docs/algorithms/kem/bike.md
Updating ./docs/algorithms/kem/classic_mceliece.md
Traceback (most recent call last):
  File "scripts/update_docs_from_yaml.py", line 45, in <module>
    out_md.write('  - **Source**: {}\n'.format(kem_yaml['primary-upstream']['source']))
KeyError: 'primary-upstream'
~/git/martyrshot/liboqs$ git status
Auf Branch main
Ihr Branch ist auf demselben Stand wie 'origin/main'.

Änderungen, die nicht zum Commit vorgemerkt sind:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)
  (benutzen Sie "git checkout -- <Datei>...", um die Änderungen im Arbeitsverzeichnis zu verwerfen)

	geändert:       docs/algorithms/kem/bike.md
	geändert:       docs/algorithms/kem/classic_mceliece.md

keine Änderungen zum Commit vorgemerkt (benutzen Sie "git add" und/oder "git commit -a")

```

When doing a dry-run for the second command, this happens:
```
~/git/martyrshot/liboqs/scripts/copy_from_upstream$ python3 copy_from_upstream.py verify
diff: /home/mib/git/martyrshot/liboqs/src/kem/kyber/pqcrystals-kyber_kyber512_aarch64: Datei oder Verzeichnis nicht gefunden
diff: verify_from_upstream/src/kem/kyber/pqcrystals-kyber_kyber512_aarch64: Datei oder Verzeichnis nicht gefunden
diff: /home/mib/git/martyrshot/liboqs/src/kem/kyber/pqcrystals-kyber_kyber768_aarch64: Datei oder Verzeichnis nicht gefunden
diff: verify_from_upstream/src/kem/kyber/pqcrystals-kyber_kyber768_aarch64: Datei oder Verzeichnis nicht gefunden
diff: /home/mib/git/martyrshot/liboqs/src/kem/kyber/pqcrystals-kyber_kyber1024_aarch64: Datei oder Verzeichnis nicht gefunden
diff: verify_from_upstream/src/kem/kyber/pqcrystals-kyber_kyber1024_aarch64: Datei oder Verzeichnis nicht gefunden
diff: /home/mib/git/martyrshot/liboqs/src/kem/saber/pqclean_lightsaber_aarch64: Datei oder Verzeichnis nicht gefunden
diff: /home/mib/git/martyrshot/liboqs/src/kem/saber/pqclean_saber_aarch64: Datei oder Verzeichnis nicht gefunden
diff: /home/mib/git/martyrshot/liboqs/src/kem/saber/pqclean_firesaber_aarch64: Datei oder Verzeichnis nicht gefunden
-----
Total schemes: 171 - 165 match upstream up to local patches, 6 differ
-----
Patches applied:
	pqclean-sphincs.patch
	pqclean-kyber-armneon-yml.patch
	pqclean-kyber-armneon-shake.patch
	pqcrystals-kyber-yml.patch
	pqcrystals-kyber-ref-shake.patch
	pqcrystals-kyber-avx2-shake.patch
	pqcrystals-dilithium-yml.patch
	pqcrystals-dilithium-ref-shake.patch
	pqcrystals-dilithium-avx2-shake.patch
-----
Schemes that differ from upstream:
Name: pqcrystals-kyber_kyber512_aarch64, expected upstream: https://github.com/pq-crystals/kyber.git - commit: faf5c3fe33e0b61c7c8a7888dd862bf5def17ad2
Name: pqcrystals-kyber_kyber768_aarch64, expected upstream: https://github.com/pq-crystals/kyber.git - commit: faf5c3fe33e0b61c7c8a7888dd862bf5def17ad2
Name: pqcrystals-kyber_kyber1024_aarch64, expected upstream: https://github.com/pq-crystals/kyber.git - commit: faf5c3fe33e0b61c7c8a7888dd862bf5def17ad2
Name: pqclean_lightsaber_aarch64, expected upstream: https://github.com/PQClean/PQClean.git - commit: 7eb978b4a733696bd7197278aa84216095674524
Name: pqclean_saber_aarch64, expected upstream: https://github.com/PQClean/PQClean.git - commit: 7eb978b4a733696bd7197278aa84216095674524
Name: pqclean_firesaber_aarch64, expected upstream: https://github.com/PQClean/PQClean.git - commit: 7eb978b4a733696bd7197278aa84216095674524
-----

```

Accordingly, an actual execution yields massive changes to the git repo's state:

```
~/git/martyrshot/liboqs/scripts/copy_from_upstream$ python3 copy_from_upstream.py copy
Updating format of Classic-McEliece-348864. Please double check ordering of yaml file
Updating format of HQC-128. Please double check ordering of yaml file
Updating format of NTRU-HPS-2048-509. Please double check ordering of yaml file
Updating format of ntrulpr653. Please double check ordering of yaml file
Updating format of LightSaber-KEM. Please double check ordering of yaml file
~/git/martyrshot/liboqs/scripts/copy_from_upstream$ git status
Auf Branch main
Ihr Branch ist auf demselben Stand wie 'origin/main'.

Änderungen, die nicht zum Commit vorgemerkt sind:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)
  (benutzen Sie "git checkout -- <Datei>...", um die Änderungen im Arbeitsverzeichnis zu verwerfen)

	geändert:       ../../docs/algorithms/kem/bike.md
	geändert:       ../../docs/algorithms/kem/classic_mceliece.md
	geändert:       ../../docs/algorithms/kem/classic_mceliece.yml
	geändert:       ../../docs/algorithms/kem/hqc.yml
	geändert:       ../../docs/algorithms/kem/ntru.yml
	geändert:       ../../docs/algorithms/kem/ntruprime.yml
	geändert:       ../../docs/algorithms/kem/saber.yml
	geändert:       ../../src/kem/kyber/kem_kyber_1024.c
	geändert:       ../../src/kem/kyber/kem_kyber_512.c
	geändert:       ../../src/kem/kyber/kem_kyber_768.c
	geändert:       ../../src/kem/saber/CMakeLists.txt
	geändert:       ../../src/kem/saber/kem_saber_firesaber.c
	geändert:       ../../src/kem/saber/kem_saber_lightsaber.c
	geändert:       ../../src/kem/saber/kem_saber_saber.c

Unversionierte Dateien:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)

	../../src/kem/saber/pqclean_firesaber_aarch64/
	../../src/kem/saber/pqclean_lightsaber_aarch64/
	../../src/kem/saber/pqclean_saber_aarch64/

keine Änderungen zum Commit vorgemerkt (benutzen Sie "git add" und/oder "git commit -a")

```

**Comment by baentsch** [comment]
@Martyrshot Thanks for the latest commits: They resolve the errors reported above. 

However, the execution of `copy_from_upstream.py copy` on a "clean slate" 'martyrshort/liboqs/main' still causes `git status` to report many changed files; also the MD files are still not part of the PR.

In turn, when I do a test-commit on your latest changes (and after running `python3 scripts/update_docs_from_yaml.py` to create the MD files), everything behaves as I'd expect it: Further runs of these scripts don't yield changes to the repo's files, so I wonder whether all that's missing now is a `git add -A` on your side to complete the PR (?).

**Comment by Martyrshot** [comment]
I'm just fixing one issue where copy_from_upstream copies in implementations that are *new* to upstream but haven't been integrated into liboqs yet (the aarch64 implementations in pqclean for the sabre family). Once that's done then I think it's safe to do a git add -A. Shouldn't be too much longer. Sorry about the wait...

**Comment by Martyrshot** [comment]
I haven't removed the need for the second step (`python3 scripts/update_docs_from_yaml.py`) yet, but I need to run to a meeting. I think once that's done then this PR is ready to go. Sorry about all the problems.

**Review by baentsch — COMMENTED** [review]
This is pretty operating system specific code. But then again I don't recall whether we ever run these scripts on Windows...

**Comment by Martyrshot** [comment]
We using `subprocess.run` (via `shell()`) in several places, so I think it's ok if this script is unix only?

**Comment by Martyrshot** [comment]
Assuming the arm64 test is some random docker issue (and all other tests pass) this pr should be ready for final review.

tests pass on my arm based mac, so it should be ok.

**Comment by dstebila** [comment]
> We using `subprocess.run` (via `shell()`) in several places, so I think it's ok if this script is unix only?

We only need to be able to run the upstream code on Unix; preferably it would run on both Linux and macOS.

**Comment by Martyrshot** [comment]
> > We using `subprocess.run` (via `shell()`) in several places, so I think it's ok if this script is unix only?
> 
> We only need to be able to run the upstream code on Unix; preferably it would run on both Linux and macOS.

I just tested that the script runs both on macOS and linux. But I found one small issue I need to fix with ignore before merging.

**Comment by Martyrshot** [comment]
> But I found one small issue I need to fix with ignore before merging.

I fixed this issue, and we should be good to go now.

**Review by baentsch — APPROVED** [review]

**Pull request merged**
