### PR TITLE
Fix SIKE exports in DLL

### PR DESCRIPTION
**Pull request by mcoret**
Following the discussion in #1222, this PR addresses the SIKE functions export issue, by introducing a new directive `set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)` in the CMakeLists.txt file.

* [no] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

### CODE REVIEW

**Review by baentsch — APPROVED** [review]
Thanks for your contribution! LGTM. Before merging, @christianpaquin may want to comment, too: DLL size increased from 9.09MB to 9.36MB and instead of 358 symbols, a grand total of 4565 symbols are now exported by the DLL (including all SIKE-subroutine symbols, obviously). So instead of merging we could also add the one-liner to https://github.com/open-quantum-safe/liboqs/wiki/Platform-specific-notes-for-building-liboqs#using-msvc to not grow the DLL by default....

**Comment by christianpaquin** [comment]
I'm not sure what are the implications (and side effects) of using this directive (we are not using it elsewhere in the library). The impact on the DLL feels like a big change, so that might be better for the next OQS version update. Seems like the SIKE code might need to export the required symbols explicitly; documenting the issue might be a good solution for now.

**Comment by dstebila** [comment]
The ideal solution would be to just fix the visibility of these particular SIKE symbols.

We use the macros `OQS_API` to indicate which symbols should be exported; it's defined in https://github.com/open-quantum-safe/liboqs/blob/main/src/common/common.h#L73.  Is there something in the SIKE code where `OQS_API` is not being properly attached to the missing SIKE functions?

**Comment by christianpaquin** [comment]
> The ideal solution would be to just fix the visibility of these particular SIKE symbols.

Correct. We'd need to look into what is missing.

**Comment by baentsch** [comment]
> Is there something in the SIKE code where OQS_API is not being properly attached to the missing SIKE functions?

At first glance, no: All SIKE APIs are "adorned" in the same way as the properly exported SIDH functions. A bit of a mystery...

> The impact on the DLL feels like a big change, 

Completely agree. So then I would suggest closing this PR without merge, add a comment pointing to this `cmake`variable in https://github.com/open-quantum-safe/liboqs/wiki/Platform-specific-notes-for-building-liboqs#building-on-windows as a "workaround" and leave #1222 unresolved until the SIKE symbols get properly exported. OK for everyone?

**Comment by baentsch** [comment]
Thanks again for the contribution. The underlying issue will be resolved for real in #1227 and the workaround is documented for now in https://github.com/open-quantum-safe/liboqs/wiki/Platform-specific-notes-for-building-liboqs#using-msvc

**Pull request closed without merging**
