### PR TITLE
Don't hardcode OPENSSL_ROOT_DIR to /usr on Linux

### LINKED ISSUE #1748: LibOQS CMake fails with cmake 3.28.3
CMake of liboqs fails on Kali Linux VM images and Kali Linux WSL

On a clean image I ran:
1) sudo apt install astyle cmake gcc ninja-build libssl-dev python3-pytest python3-pytest-xdist unzip xsltproc doxygen graphviz python3-yaml valgrind libgmp3-dev git libssl-dev
2) git clone https://github.com/open-quantum-safe/liboqs.git
3) cd liboqs
4) cmake -GNinja -DOQS_USE_OPENSSL=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr

It throws this error which I don't understand since it finds the library v3.1.5?:
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- The C compiler identification is GNU 13.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test CC_SUPPORTS_WA_NOEXECSTACK
-- Performing Test CC_SUPPORTS_WA_NOEXECSTACK - Success
-- Performing Test LD_SUPPORTS_WL_Z_NOEXECSTACK
-- Performing Test LD_SUPPORTS_WL_Z_NOEXECSTACK - Success
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Alg enablement unchanged
CMake Error at /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  suitable version "3.1.5", minimum required is "1.1.1")
Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.28/Modules/FindOpenSSL.cmake:668 (find_package_handle_standard_args)
  CMakeLists.txt:135 (find_package)

Environment:
 - WSL: Linux 4.4.0-19041-Microsoft #3996-Microsoft x86_64 GNU/Linux
 - Kali VM: Linux 6.6.9-amd64 Kali 6.6.9-1kali1 x86_64 GNU/Linux
 - liboqs main branch
 - which make -> /urs/bin/cmake
 - cmake v.3.28.3

Not sure if this is a bug or a Kali issue but, any help would be appreciated.

### PR DESCRIPTION
**Pull request by SWilson4**
Recent versions of CMake search only `OPENSSL_ROOT_DIR` if defined, so if OpenSSL is installed in a location other than `/usr` (e.g., `/usr/lib/x86_64-linux-gnu`), the build will fail.

Fixes #1748.

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Review by baentsch — APPROVED** [review]
Thanks for this improvement @SWilson4 . Conceptually LGTM. Don't understand why we did this hardcoding. As this was 4 years ago, most likely no negative impact to downstreams, but a "trigger-downstream" tag would be good, no?

**Comment by SWilson4** [comment]
> Thanks for this improvement @SWilson4 . Conceptually LGTM. Don't understand why we did this hardcoding. As this was 4 years ago, most likely no negative impact to downstreams, but a "trigger-downstream" tag would be good, no?

It never hurts :)

**Comment by SWilson4** [comment]
Pinging @open-quantum-safe/liboqs-committers for a second review here.

**Review by ashman-p — APPROVED** [review]

**Comment by SWilson4** [comment]
Given that the Travis tests passed on this branch previously, and the only commit since then is the empty downstream trigger, I think it's safe to say this change will not break Travis whenever that CI system is working again (created #1888 to track). Hence I will go ahead and merge.

**Pull request merged**
