### PR TITLE
Pull round 3 Dilithium from PQClean

### PR DESCRIPTION
**Pull request by jschanck**
This PR copies round 3 Dilithium from PQClean. An alternative is to wait for #883 to land and copy Dilithium directly from upstream. It's not clear to me how close #883 is to completion, hence this PR.

> Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)

Yes, there are significant changes between round 2 and round 3 Dilithium.

> Does this PR change the the list of algorithms available -- either adding or removing?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

Yes, it removes dilithium4, adds dilithium5, and adds the "_aes" variants of dilithium2, dilithium3, and dilithium5.

### CODE REVIEW

**Comment by bhess** [comment]
Looks good to me, and a good alternative to accelerate having Dilithium round 3 in.

I believe #880 isn't far from completion though. There is also #891 to preview a version where #880 pulls Dilithium round 3 (and Kyber) from upstream.

**Comment by baentsch** [comment]
> I believe #880 isn't far from completion though. 

As discussed, we're all agreed on this point. @jschanck Thus, we thank you very much for your work on this PR but prefer doing a direct "highest upstream" import in favour of a pull from PQClean/this PR. So, can we ask you to either close this PR or provide reasons why #890 should be prioritized over #880+#891?

**Comment by jschanck** [comment]
My preference is also for pulling from the "highest upstream", but in most cases (including kyber and dilithium) we need to patch the upstream code before it will hook into our common code.

#891 imports redundant AES and fips202 code instead of doing this patching.

PQClean does the patching for reference implementations, but imports redundant AES and fips202 for platform specific implementations.

Neither is perfect.

I think we should extend copy_from_upstream with a patching mechanism, and deal with the common code issue. But I have no objection to merging #891 in the meantime, so I'll close this PR.

**Comment by baentsch** [comment]
> I think we should extend copy_from_upstream with a patching mechanism, and deal with the common code issue.

Fully agree. Documented in #894

**Pull request closed without merging**
