### PR TITLE
fixing #779

### PR DESCRIPTION
**Pull request by baentsch**
As discussed in #779 , 
@xvzcf please advise whether you know a way to make compile dependent on `OPENSSL_NO_EC2M` being defined
@christianpaquin please check whether you agree with the Darwin-specific non-compilation of `cpu.c`

CI results accessible [here](https://app.circleci.com/pipelines/github/baentsch/liboqs/290/workflows/69a1517d-c284-4487-b3e8-691a49a8cb64)

### CODE REVIEW

**Comment by christianpaquin** [comment]
So, what was the specific issue with picnic? On Darwin, the `cpu.c` filed would be empty creating a warning? Wouldn't that have caused a build failure? This fix looks ok to me in the picnic CMakeFile assuming the above is correct.

I have PR #771 ready, updating picnic, so that should be replicated there as well.

**Comment by baentsch** [comment]
> On Darwin, the cpu.c filed would be empty creating a warning? 

Yes

> Wouldn't that have caused a build failure?  

No: It was/is just a warning.

**Comment by christianpaquin** [comment]
> > On Darwin, the cpu.c filed would be empty creating a warning?
> 
> Yes
> 
> > Wouldn't that have caused a build failure?
> 
> No: It was/is just a warning.

Ok, picnic changes are fine by me, but as I said, perhaps after PR #771 gets merged so it can be applied to the new code.

**Comment by xvzcf** [comment]
Could you try using https://cmake.org/cmake/help/latest/module/CheckSymbolExists.html to detect `OPENSSL_NO_EC2M`?

**Comment by baentsch** [comment]
> Could you try using https://cmake.org/cmake/help/latest/module/CheckSymbolExists.html to detect `OPENSSL_NO_EC2M`?

@xvzcf Thanks very much for the pointer!

**Comment by baentsch** [comment]
Replacing with #782 to ease review.

**Pull request closed without merging**
