### PR TITLE
Add Android CircleCI config

### PR DESCRIPTION
**Pull request by dstebila**
Reproduces #875 on a branch inside OQS repository to trigger CI.

Adds Android CI/CD config for the CircleCI pipeline. Tests whether building library is successful.

Partially addresses Android cross-compilation (#594)

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the the list of algorithms available -- either adding or removing?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

### CODE REVIEW

**Comment by nicholasfulton** [comment]
The issue is with invalid permissions, so I'm adding `bash` before the script execution.

**Comment by dstebila** [comment]
> The issue is with invalid permissions, so I'm adding `bash` before the script execution.

Is this in a branch somewhere? Or do I need to do this directly?

**Comment by baentsch** [comment]
@nicholasfulton does the error message below ring a bell?
```
./scripts/build-android.sh $NDK_HOME -a arm64-v8a -s 30

Directory for NDK doesn't exist at -a
```

**Comment by baentsch** [comment]
NDK seems to be present in the specified circleci docker image (`circleci/android:api-30-ndk`) but surprisingly only at `r20`:
```
ls /opt/android/
android-ndk-r20  sdk
```

resulting in:
```
./scripts/build-android.sh $NDK_HOME -a armeabi-v7a -s 30
Valid directory for NDK at /opt/android/android-ndk-r20
Compiling for ABI armeabi-v7a
Invalid SDK level of 30
```

If switching to 20 this is the result:
```
circleci@3d2a0845727a:~/liboqs$ ./scripts/build-android.sh $NDK_HOME -a armeabi-v7a -s 20
Valid directory for NDK at /opt/android/android-ndk-r20
Compiling for ABI armeabi-v7a
Compiling for SDK 20
Cleaning up previous build
Building in directory build
./scripts/build-android.sh: line 106: cmake: command not found
```

--> I'd be inclined to close this PR until all these things get corrected. OK with you @dstebila ?

@nicholasfulton : You now will not get permission errors any more when trying to run CI tests as part of a PR but we strongly suggest you first run the new code/tests locally as per [this guidance](https://github.com/open-quantum-safe/liboqs/wiki/Contributing-guide#continuous-integration-ci-testing).

**Comment by dstebila** [comment]
Closing for now since it's been open for a while. A revived PR is definitely welcome, and as Michael notes permissions on running CI should no longer be a problem.

**Comment by nicholasfulton** [comment]
> Closing for now since it's been open for a while. A revived PR is definitely welcome, and as Michael notes permissions on running CI should no longer be a problem.

Thank you! I should be able to focus more on this in the coming months, at which point I can get a more polished solution set up for CI.

**Pull request closed without merging**
