### PR TITLE
Add XMSS-SHA256_{10, 16, 20}_192 parameters

### PR DESCRIPTION
**Pull request by cothan**
Signed-off-by: Duc Tri Nguyen <dnguye69@gmu.edu>

- Add additional XMSS parameters to meet NIST SP 800 208. 
- Add emoji to Table parameters `sig_stfl_xmss.h`, I hope it's helpful and save developer time. 
- Add KATs. 
- Add tests. 

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Comment by cothan** [comment]
So the 1 failed check because it's timeout :((

**Review by baentsch — CHANGES_REQUESTED** [review]
If I'm not mistaken (?) the second question checkbox needs to be checked as this adds algs. If you'd agree, please activate downstream testing: I'm pretty certain it won't pass (as the current `liboqs` "main" breaks `oqsprovider` building) -- still undecided whether this should be fixed in `liboqs` or `oqsprovider`. Opinions welcome.

Add: See https://github.com/open-quantum-safe/oqs-demos/issues/281 and https://github.com/open-quantum-safe/oqs-provider/issues/427 (same problem)

**Review by ashman-p — COMMENTED** [review]
Probably should update docs/algorithms/sig_stfl/xmss.md etc?

**Comment by cothan** [comment]
@ashman-p , thank you. I forgot to update the doc. I will make an update soon.

**Review by ashman-p — APPROVED** [review]

**Comment by cothan** [comment]
Thanks @ashman-p , I've updated `README.md, xmss.yml`, and `xmss.md`.

**Comment by cothan** [comment]
@baentsch . I think I miss something, I check the downstream oqs-provider and I don't see XMSS/LMS to be inserted like https://github.com/open-quantum-safe/oqs-provider/pull/413 . 
This PR add additional parameters to XMSS, so it changes the algorithms list (if we count the parameters in). 
And it doesn't change APIs. So I think I will remove the 2nd checkbox. 
What do you think?

**Comment by ashman-p** [comment]
> Thanks @ashman-p , I've updated `README.md, xmss.yml`, and `xmss.md`.

@cothan Thanks.

**Comment by SWilson4** [comment]
This looks good to me, but I'll hold off on approving until CI is green. Also, it's probably a good idea to trigger the `oqs-provider` tests by putting "[trigger downstream]" in a commit message in case of a subtle bug like https://github.com/open-quantum-safe/liboqs/issues/1815.

**Comment by cothan** [comment]
@SWilson4 , Fixed the [trigger downstream] test. All CIs are green. I'll merge when I have your approval.

**Review by SWilson4 — APPROVED** [review]
LGTM! Thanks, Duc.

**Pull request merged**
