### PR TITLE
Fixed build issue on arm based macs when using gcc11

### LINKED ISSUE #1164: Build failures with gcc on Apple M1
Building liboqs with gcc-11 on an Apple M1 Mac yields build failures related to Kyber and Saber NTT code.

Reproduce by checking out 0.7.1, and then running `cmake -GNinja -DCMAKE_C_COMPILER=gcc-11 ..`.  (Note that there are other build failures on HEAD when building with gcc-11 on macOS which are independent of this which I'll create a separate issue for.)

```
[667/1230] Building ASM object src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_base_mul.S.o
FAILED: src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_base_mul.S.o 
/opt/homebrew/bin/gcc-11  -I/Users/dstebila/Dev/OQS/liboqs/build/include -I/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64 -I/Users/dstebila/Dev/OQS/liboqs/src/common/pqclean_shims -arch arm64 -fPIC -mcpu=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,-dead_strip -MD -MT src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_base_mul.S.o -MF src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_base_mul.S.o.d -o src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_base_mul.S.o -c /Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_base_mul.S
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_base_mul.S:10:3: error: unknown directive
  .type PQCLEAN_KYBER1024_AARCH64_asm_point_mul_extended, %function
  ^
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_base_mul.S:77:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_asymmetric_mul, %function
^
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_base_mul.S:232:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_asymmetric_mul_montgomery, %function
^
[668/1230] Building ASM object src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_iNTT.S.o
FAILED: src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_iNTT.S.o 
/opt/homebrew/bin/gcc-11  -I/Users/dstebila/Dev/OQS/liboqs/build/include -I/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64 -I/Users/dstebila/Dev/OQS/liboqs/src/common/pqclean_shims -arch arm64 -fPIC -mcpu=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,-dead_strip -MD -MT src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_iNTT.S.o -MF src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_iNTT.S.o.d -o src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_iNTT.S.o -c /Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_iNTT.S
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_iNTT.S:8:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_intt_SIMD_bot, %function
^
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_iNTT.S:94:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_intt_SIMD_top, %function
^
[669/1230] Building ASM object src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_NTT.S.o
FAILED: src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_NTT.S.o 
/opt/homebrew/bin/gcc-11  -I/Users/dstebila/Dev/OQS/liboqs/build/include -I/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64 -I/Users/dstebila/Dev/OQS/liboqs/src/common/pqclean_shims -arch arm64 -fPIC -mcpu=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,-dead_strip -MD -MT src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_NTT.S.o -MF src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_NTT.S.o.d -o src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_NTT.S.o -c /Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_NTT.S
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_NTT.S:8:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_ntt_SIMD_top, %function
^
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_NTT.S:177:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_ntt_SIMD_bot, %function
^
[671/1230] Building ASM object src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_poly.S.o
FAILED: src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_poly.S.o 
/opt/homebrew/bin/gcc-11  -I/Users/dstebila/Dev/OQS/liboqs/build/include -I/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64 -I/Users/dstebila/Dev/OQS/liboqs/src/common/pqclean_shims -arch arm64 -fPIC -mcpu=native -Werror -Wall -Wextra -Wpedantic -Wstrict-prototypes -Wshadow -Wformat=2 -Wfloat-equal -Wwrite-strings -O3 -fomit-frame-pointer -fdata-sections -ffunction-sections -Wl,-dead_strip -MD -MT src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_poly.S.o -MF src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_poly.S.o.d -o src/kem/kyber/CMakeFiles/kyber_1024_aarch64.dir/pqclean_kyber1024_aarch64/__asm_poly.S.o -c /Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_poly.S
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_poly.S:8:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_add_reduce, %function
^
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_poly.S:72:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_sub_reduce, %function
^
/Users/dstebila/Dev/OQS/liboqs/src/kem/kyber/pqclean_kyber1024_aarch64/__asm_poly.S:136:1: error: unknown directive
.type PQCLEAN_KYBER1024_AARCH64_asm_add_add_reduce, %function
^
[676/1230] Building C object src/kem/classic_mceliece/CMakeFiles/classic_mceliece_6960119f_vec.dir/pqclean_mceliece6960119f_vec/controlbits.c.o
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by Martyrshot**
This resolves #1164. This pr also updates the CMakeLists.txt template for copy_from_upstream so that all KEM implementations we pull from pqclean define `old_gas_syntax` when run on Darwin. This is so that in the future, as more aarch64 optimized implementations are added to pqclean and eventually liboqs, the assembly files will need to be updated such that all instances of `#ifndef __clang__` become `#if !defined(__clang__) && !defined(old_gas_syntax)`.

As a result, some non-saber/kyber CMakeLists.txt's are also updated in this PR to define `old_gas_syntax` on darwin.

### CODE REVIEW

**Review by baentsch — DISMISSED** [review]
Thanks very much for this improvement. I can't claim to understand (hence, approve) everything, but I took the liberty to add our brand-new Apple M1 CI to check whether everything tests OK on that platform with gcc-11 -- and it seems it still doesn't: It's [picnic --not coming from PQClean failing](https://github.com/open-quantum-safe/liboqs/pull/1177/checks?check_run_id=4863789372), though. @christianpaquin : Do you know whether it should work on ARM64 compiled with gcc-11?

**Comment by Martyrshot** [comment]
I should have mentioned that I was also experiencing an issue with picnic tests on my m1 mac. My mac's build environment has been pretty scrambled having transitioned from x86, so I assumed that was the issue since I didn't change anything that would affect picnic (at least I think that's true?).

**Comment by Martyrshot** [comment]
I just built and ran tests both on a fresh clone of main, and my branch using clang and picnic returns the correct results. I haven't been able to test the fresh clone of main with gcc-11 yet, but it will likely require disabling the kyber and saber families since they will still cause build issues.

**Comment by Martyrshot** [comment]
Looks like the issue persists on our main branch when we build with gcc-11 rather than appleclang. So it looks like this is indeed a pre-existing issue.

**Comment by dstebila** [comment]
> Looks like the issue persists on our main branch when we build with gcc-11 rather than appleclang. So it looks like this is indeed a pre-existing issue.

Thanks. I'd be inclined to merge this PR as is with the Picnic gcc M1 KATs failing, and create a separate issue for resolving that.

**Review by dstebila — APPROVED** [review]

**Comment by baentsch** [comment]
> I'd be inclined to merge this PR as is with the Picnic gcc M1 KATs failing, and create a separate issue for resolving that.

Fine with me.

**Pull request merged**
