### PR TITLE
Exporting liboqs target in CMake and some CI refactoring.

### PR DESCRIPTION
**Pull request by xvzcf**
@christianpaquin could you verify OQS-OpenSSL still builds on Windows with this PR?

### CODE REVIEW

**Review by baentsch — APPROVED** [review]
Looks good to me.

**Comment by baentsch** [comment]
@xvzcf Is anything speaking against rebasing this PR and merging it to get to a "PR free state" for liboqs? Let me know if you don't find time to do it. BTW, is this also resolving issue #763?

**Comment by xvzcf** [comment]
> @xvzcf Is anything speaking against rebasing this PR and merging it to get to a "PR free state" for liboqs? Let me know if you don't find time to do it. BTW, is this also resolving issue #763?

There isn't, and I'm working on merging this in.

**Comment by baentsch** [comment]
@xvzcf Thanks! Fewer PRs, fewer issues: A good day.

**Pull request merged**
