### PR TITLE
Run the test_kem and test_sig tests on a thread when possible

### PR DESCRIPTION
**Pull request by dstebila**
Algorithms with large stack usage cause problems when running in threads (e.g., #608, https://travis-ci.com/github/open-quantum-safe/liboqs-cpp/jobs/299650240).  This PR moves the tests in `test_kem` and `test_sig` onto a thread when compiling with clang or gcc, so as to detect these failures at the liboqs level, rather than leaving it to downstream sub-projects.

Note that the following schemes are currently failing:
```
Classic-McEliece-348864
Classic-McEliece-348864f
Classic-McEliece-460896
Classic-McEliece-460896f
Classic-McEliece-6688128
Classic-McEliece-6688128f
Classic-McEliece-6960119
Classic-McEliece-6960119f
Classic-McEliece-8192128
Classic-McEliece-8192128f
LEDAcryptKEM-LT52
Rainbow-IIIc-Classic
Rainbow-IIIc-Cyclic
Rainbow-IIIc-Cyclic-Compressed
Rainbow-Vc-Classic
Rainbow-Vc-Cyclic
Rainbow-Vc-Cyclic-Compressed
```

I'm not sure how to approach solving this.  Do we disable these algorithms by default?  Try to rewrite them so they're on the heap, rather than the stack?  Try to enlarge the stack in how all our subprojects are compiled so that they can be run (but then people might encounter this bad behaviour outside of our build)?

Advice welcome, @vsoftco @xvzcf @christianpaquin @thomwiggers @baentsch.

### CODE REVIEW

**Comment by baentsch** [comment]
My immediate reaction: Disable them until they "behave"... (... incl. under pthreads). But then again, the great thing about `liboqs` and all libs/apps building on top is the availability to run all these algorithms (in different stages of "implementation hardening") side-by-side.

So what about this compromise: 
- Keep all algorithms in
- Keep adding them to downstream libs/apps like openssl
- Exclude the list above from pthread testing
- Document that exclusion clearly on the OQS website/git repo.
- Make the algorithm implementors aware of this problem so they can fix it (if they want to do that)

--> This way, we (OQS) can focus on what matters to all users: people can keep using any PQC they want courtesy `liboqs` -- until they hit such "snag". Fixing those "snags" can/and should be done upstream (it's not only "us"/`liboqs`-enabled SW stacks failing on this). E.g., wouldn't it be a nice addition to the PQClean project to require such 'pthreads' safety (and test for it) adding to the [prerequisites documented by PQClean](https://github.com/PQClean/PQClean#requirements-on-c-implementations-that-are-automatically-checked).

**Comment by thomwiggers** [comment]
The large stack-usage of some implementations is a long-known problem but I also don't know how to get around it (without large amounts of engineering effort). It sometimes helps to put the public keys/secret keys on the heap themselves; this allows the stack-based implementations that much more room on the stack. However, it's still going to be a problem.

> E.g., wouldn't it be a nice addition to the PQClean project to require such 'pthreads' safety (and test for it) adding to the prerequisites documented by PQClean.

I'm afraid that's not possible. PQClean bans any use of the heap to allow running implementations on platforms that don't offer an allocator. I'd prefer having more reference implementations, even if they have these kinds of problems.

**Comment by vsoftco** [comment]
@dstebila will review by Friday

**Comment by vsoftco** [comment]
@dstebila Is https://github.com/open-quantum-safe/liboqs/pull/671/commits/306d5f974754f1ddde35d362e425636b3a39b630 ok with you?

**Comment by dstebila** [comment]
> @dstebila Is [306d5f9](https://github.com/open-quantum-safe/liboqs/commit/306d5f974754f1ddde35d362e425636b3a39b630) ok with you?

Fancier than we need, but that's fine.

> We most likely need to add `pthread` to the linker for test_kem/sig, @xvzcf ?

I just added it, we'll see if it works.

**Comment by vsoftco** [comment]
@dstebila Seems to be working, I'll merge once AppVeyor passes

**Pull request merged**
