### PR TITLE
Suppress constant time check for public matrix generation on Kyber AVX2

### LINKED ISSUE #1187: Constant time checks for Kyber on AVX2 failing
This was picked up by the weekly builds: https://github.com/open-quantum-safe/liboqs/runs/5080898885?check_suite_focus=true#step:6:339

Not sure what changed -- no changes to the Kyber Intel code in a few months, as far as I can tell.

### PR DESCRIPTION
**Pull request by dstebila**
Fixes #1187.

* [No] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [No] Does this PR change the the list of algorithms available -- either adding, removing, or renaming?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

### CODE REVIEW

**Comment by dstebila** [comment]
I think this fixes it, but I couldn't reproduce locally, so I'm not certain. I've temporarily added a Github actions job that will run the test immediately rather than waiting for the weekly job; that should be removed from `.github/workflows/linux.yml` before merging.

**Review by baentsch — COMMENTED** [review]
FWIW, LGTM. Amazing to see this test passes in 8sec when just testing Kyber* (as opposed to 2h when testing most algs...). Thanks also for updating to the "focal" image.

**Comment by bhess** [comment]
Thanks @dstebila. I'll double check it locally.

**Review by bhess — CHANGES_REQUESTED** [review]
I ran it a few times and the new rule works fine. In the suggested change I added one more rule that captures the related Memcheck:Value8 exception, which was also reported in the failed weekly run.

**Review by bhess — APPROVED** [review]

**Pull request merged**
