### PR TITLE
adding scan-build test

### LINKED ISSUE #1239: Add scan-build to CI
To avoid regressions and confirm closure of #1212.

### PR DESCRIPTION
**Pull request by baentsch**
Fixes #1239. Avoid recurrence of #1212 ~(which arguably should be re-opened)~.

@dstebila : Please decide how/when to merge this. My suggestion would be after @sebastinas and @bhess had a chance to review the [run log](https://circleci.com/api/v1.1/project/github/open-quantum-safe/liboqs/17515/output/103/0?file=true&allocation-id=62bb17df947e861ada3206ce-0-build%2F54D6229E) for the picnic and kyber issues listed.

* [no] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [no] Does this PR change the the list of algorithms available -- either adding, removing, or renaming?  (If so, PRs in OQS-OpenSSL, OQS-BoringSSL, and OQS-OpenSSH will also be required by the time this is merged.)

### CODE REVIEW

**Comment by bhess** [comment]
Thanks for adding the check. I opened a PR in Kyber upstream, the reported nonce update isn't necessary.

**Comment by sebastinas** [comment]
A fix for Picnic is available in #1241.

**Comment by baentsch** [comment]
Just noticed that --if OK-- this also fixes #194.

Thanks, @sebastinas for eliminating most picnic issues. [Latest run showing](https://circleci.com/api/v1.1/project/github/open-quantum-safe/liboqs/17572/output/103/0?file=true&allocation-id=62bc1571207b9944c3439c8e-0-build%2F54243244) only 3 Kyber and 3 Picnic warnings blocking a clean pass.

**Comment by baentsch** [comment]
> FWIW, the remaining issues in Picnic are false positives that have been fixed in llvm 14.

Thanks! That indeed explains why I locally only saw Kyber issues (I am running clang/llvm-14)... Let's see how to move the CCI container to that version then.

**Comment by baentsch** [comment]
@sebastinas : Thanks again for the quick updates and the pointer to llvm-14. (Picnic) case closed.
@bhess: In order to make headway this PR now excludes Kyber from the test. Suggest to update this exclusion as and when this gets fixed upstream and merged to liboqs (didn't find issue to link to in either [PQClean](https://github.com/PQClean/PQClean/issues) or [PQCrystals](https://github.com/pq-crystals/kyber/issues)).
@dstebila : Please review and merge. Due to some inter-dependencies in the CI config, #1234 will then be rebased and moved to conclusion too.

**Comment by bhess** [comment]
> In order to make headway this PR now excludes Kyber from the test. Suggest to update this exclusion as and when this gets fixed upstream and merged to liboqs (didn't find issue to link to in either [PQClean](https://github.com/PQClean/PQClean/issues) or [PQCrystals](https://github.com/pq-crystals/kyber/issues)).

Sounds good. Will update Kyber once the PR in pqcrystals is merged, see https://github.com/pq-crystals/kyber/pull/47.

**Review by dstebila — APPROVED** [review]

**Pull request merged**
