### PR TITLE
Mingw-w64 support

### PR DESCRIPTION
**Pull request by gadoofou87**
Builds successfully on Arch Linux and passes tests in Wine

### CODE REVIEW

**Comment by xvzcf** [comment]
Hi @gadoofou87, we are in the process of moving the build system to CMake and dropping support for autotools (PR #556). Would it be possible to update your PR once the switch is made?

**Comment by gadoofou87** [comment]
Yes, sure. You can drop these files

>  config/detect_host_and_cpu.m4
>  scripts/x86_64-w64-mingw32-cross-compile.sh

And apply the patch below

```
diff --git a/tests/CMakeLists.txt b/tests/CMakeLists.txt
index 3b59e1d..7cab5c5 100644
--- a/tests/CMakeLists.txt
+++ b/tests/CMakeLists.txt
@@ -3,6 +3,10 @@ if(USE_OPENSSL)
     set(LIBS ${OPENSSL_CRYPTO_LIBRARY})
 endif()
 
+if(MINGW OR MSYS OR CYGWIN)
+    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D__USE_MINGW_ANSI_STDIO=1 -Wno-unknown-pragmas -Wno-unused-parameter")
+endif()
+
 if(NOT WIN32)
     set(LIBS ${LIBS} m)
     execute_process(COMMAND ${PROJECT_SOURCE_DIR}/scripts/git_commit.sh OUTPUT_VARIABLE GIT_COMMIT)

```

I tested on cmake branch and it works correctly

```
[archie@archlinux tests]$ ./example_kem.exe
[example_stack] OQS_KEM_frodokem_640_aes operations completed.
[example_heap]  OQS_KEM_frodokem_640_aes operations completed.
[archie@archlinux tests]$ ./example_sig.exe
[example_stack] OQS_SIG_dilithium_2 operations completed.
[example_heap]  OQS_SIG_dilithium_2 operations completed.
[archie@archlinux tests]$ ./test_kem.exe DEFAULT
Configuration info
==================
Target platform:  x86_64-Linux-5.5.3-1-ck
Compiler:         gcc (9.2.0)
OQS version:      0.2.1-dev
OpenSSL enabled:  No
AES:              C
SHA-2:            C
SHA-3:            C

================================================================================
Sample computation for KEM FrodoKEM-640-AES
================================================================================
shared secrets are equal
[archie@archlinux tests]$ ./test_sig.exe DEFAULT
Configuration info
==================
Target platform:  x86_64-Linux-5.5.3-1-ck
Compiler:         gcc (9.2.0)
OQS version:      0.2.1-dev
OpenSSL enabled:  No
AES:              C
SHA-2:            C
SHA-3:            C

================================================================================
Sample computation for signature DILITHIUM_2
================================================================================
verification passes as expected
```

**Comment by gadoofou87** [comment]
Yes, sure. You can drop these files

>  config/detect_host_and_cpu.m4
>  scripts/x86_64-w64-mingw32-cross-compile.sh

And apply the patch below

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 9710c45..5c7a6a7 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -50,6 +50,16 @@ endif()
 
 include(config/config-oqs-alg-support.cmake)
 
+if(MINGW OR MSYS OR CYGWIN)
+    if(USE_OPENSSL)
+        set(BUILD_SHARED_LIBS OFF)
+        set(CMAKE_EXE_LINKER_FLAGS "-static")
+        set(OPENSSL_USE_STATIC_LIBS TRUE)
+        add_compile_options("-lssp -lws2_32")
+        link_libraries("-lssp -lws2_32")
+    endif()
+endif()
+
 if(USE_OPENSSL)
     if(NOT DEFINED OPENSSL_ROOT_DIR)
         if(${CMAKE_HOST_SYSTEM_NAME} STREQUAL "Darwin")
diff --git a/tests/CMakeLists.txt b/tests/CMakeLists.txt
index 3b59e1d..7cab5c5 100644
--- a/tests/CMakeLists.txt
+++ b/tests/CMakeLists.txt
@@ -3,6 +3,10 @@ if(USE_OPENSSL)
     set(LIBS ${OPENSSL_CRYPTO_LIBRARY})
 endif()
 
+if(MINGW OR MSYS OR CYGWIN)
+    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D__USE_MINGW_ANSI_STDIO=1 -Wno-unknown-pragmas -Wno-unused-parameter")
+endif()
+
 if(NOT WIN32)
     set(LIBS ${LIBS} m)
     execute_process(COMMAND ${PROJECT_SOURCE_DIR}/scripts/git_commit.sh OUTPUT_VARIABLE GIT_COMMIT)

```

I tested on cmake branch and it works correctly

```
[archie@archlinux tests]$ ./example_kem.exe
[example_stack] OQS_KEM_frodokem_640_aes operations completed.
[example_heap]  OQS_KEM_frodokem_640_aes operations completed.
[archie@archlinux tests]$ ./example_sig.exe
[example_stack] OQS_SIG_dilithium_2 operations completed.
[example_heap]  OQS_SIG_dilithium_2 operations completed.
[archie@archlinux tests]$ ./test_kem.exe DEFAULT
Configuration info
==================
Target platform:  x86_64-Linux-5.5.3-1-ck
Compiler:         gcc (9.2.0)
OQS version:      0.2.1-dev
OpenSSL enabled:  Yes (OpenSSL 1.1.1d  10 Sep 2019)
AES:              C
SHA-2:            C
SHA-3:            C

================================================================================
Sample computation for KEM FrodoKEM-640-AES
================================================================================
shared secrets are equal
[archie@archlinux tests]$ ./test_sig.exe DEFAULT
Configuration info
==================
Target platform:  x86_64-Linux-5.5.3-1-ck
Compiler:         gcc (9.2.0)
OQS version:      0.2.1-dev
OpenSSL enabled:  Yes (OpenSSL 1.1.1d  10 Sep 2019)
AES:              C
SHA-2:            C
SHA-3:            C

================================================================================
Sample computation for signature DILITHIUM_2
================================================================================
verification passes as expected
```

**Comment by gadoofou87** [comment]
@xvzcf It is done!

**Comment by gadoofou87** [comment]
Conflict resolved

**Comment by dstebila** [comment]
Thanks @gadoofou87, looks good. Can I ask you to also add a short write-up on our wiki page about [building](https://github.com/open-quantum-safe/liboqs/wiki/Building) noting how to build on Mingw-w64?  If we were able to create a continuous integration test to ensure that the build you've created continues to work, that would be great, but I don't know if any of our CI platforms support non-Visual Studio builds on Windows -- do you know anything about that?

**Pull request merged**
