### PR TITLE
 LMS H5_W1

### PR DESCRIPTION
**Pull request by ashman-p**
Add support for LMS key generation, LMS sign, and verify. LMS variant H=5, W=1.

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [Y] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in [oqs-provider](https://github.com/open-quantum-safe/oqs-provider), [OQS-OpenSSL](https://github.com/open-quantum-safe/openssl), [OQS-BoringSSL](https://github.com/open-quantum-safe/boringssl), and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Comment by ashman-p** [comment]
Any idea what changed in this PR to cause static analysis errors in XMSS tests. Any ideas anyone?

**Comment by ducnguyen-sb** [comment]
Let me convert the `uint64_t` to `unsigned long long`. Somehow I think it's safer to use uint64_t instead of `unsigned long long`.

**Comment by ducnguyen-sb** [comment]
@ashman-p , I've fixed all the problem with XMSS. 
Thank you for letting me know. 
There is a minor bug in LMS `scan-build`, I can fix it for you if you want.

**Comment by ashman-p** [comment]
> 

Thanks Duc, Can you just post the diffs here and i can update and clean up the branch.
Thanks.

**Comment by ducnguyen-sb** [comment]
@ashman-p , so I revert my commit, and generate a patch below. 


[patch.txt](https://github.com/open-quantum-safe/liboqs/files/12163815/patch.txt)

**Review by ducnguyen-sb — APPROVED** [review]
Thanks for committing my PR to fix XMSS syntax.

**Pull request merged**
