### PR TITLE
Fix windows-x86 and arm compiling error.

### PR DESCRIPTION
**Pull request by ducnguyen-sb**
This PR improved XMSS compiling error in Windows-x86 and Windows ARM. 
- Use malloc instead of dynamic stack array. 
- Fixed astyle
- Fixed a typo in sha2_armv8. 

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) and [OQS-OpenSSH](https://github.com/open-quantum-safe/openssh) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Review by ashman-p — APPROVED** [review]

**Comment by ducnguyen-sb** [comment]
@ashman-p  Can you update LMS to read public/private key from KAT file? I have timeout generating the key H15_w8 and H20_w1, I didn't test further.

**Comment by ducnguyen-sb** [comment]
@ashman-p , yes, feel free.

**Comment by ducnguyen-sb** [comment]
Okay only the README is left.

**Comment by baentsch** [comment]
> Okay only the README is left.

This is what I mentioned in the call on Tuesday: The generator removes manually changed text: This PR adds apparently manually curated algorithm lists into the code generation template brackets: Either you keep maintaining this manually, but then have to move your changes outside the "OQS_TEMPLATE_FRAGMENT_...START ...END" brackets _or_ add logic for adding the new algorithms into the `copy_from_upstream` logic (if you take LMS/XMSS from some upstream location) to make this CI test pass.

**Comment by ducnguyen-sb** [comment]
Now, all the tests have passed. 
To fix the `copy_from_upstream` error, I moved the `OQS_TEMPLATE_FRAGMENT_...START ...END` outside of XMSS/LMS location. 

I know that I won't add any additional parameters for XMSS. 
For LMS, if you've finalized all the parameters you need @ashman-p , I can merge this PR now. 
Otherwise, next time you add a parameter, you have to edit the README.md manually to update the additional LMS parameters. 

What do you think?

**Review by ashman-p — APPROVED** [review]

**Pull request merged**
