### PR TITLE
Add SPHINCS+ from PQClean

### LINKED ISSUE #482: Add SPHINCS+ from PQClean

### PR DESCRIPTION
**Pull request by thomwiggers**
This PR adds all SPHINCS+ signature schemes from PQClean.

I have some scripts that generated the major files, I don't suggest maintaining any of these files by hand. (Where) should I store those?

Also adds an incremental hashing API to FIPS202 and adds SHA2 + the accompanying pqclean shims.

Closes #482

### CODE REVIEW

**Comment by thomwiggers** [comment]
Someone not being me will have to update the Windows build files.

**Comment by dstebila** [comment]
Thanks Thom.  Over the weekend I was also working on automating bringing schemes from PQClean to liboqs, and in PR #484 have built some scripts and templates for automatically adding KEMs.  My inclination would be to try to extend that to deal with signature schemes.  Give me a few days to get the KEM stuff sorted out, and then I'll take a look at this PR and signature schemes.

**Comment by thomwiggers** [comment]
The SHA256 and Haraka implementations in this PR are not thread-safe. If this is a concern, we would need to fix that in PQClean.

**Comment by dstebila** [comment]
Yes, we do need thread-safe because our consuming applications (OpenSSL, OpenSSH) are multi-threaded.

Seems to me that "clean" in PQClean should include "thread-safe"...

**Comment by thomwiggers** [comment]
Agreed, it's super annoying because it's also a very nasty side effect for my Rust library (needed to disable multi-threaded tests, which are enabled by default).

**Comment by dstebila** [comment]
#521 replaces this PR.

**Pull request closed without merging**
