### PR TITLE
Added assembly optimization for sike

### PR DESCRIPTION
**Pull request by christianpaquin**
Added assembly optimization for sike. Added detection of the bmi2 instruction set to enable MULX. The adx set however cannot be detected using the same mechanism; not sure why (perhaps I need to switch to [this script](https://github.com/autoconf-archive/autoconf-archive/blob/master/m4/ax_ext.m4) instead.)

### CODE REVIEW

**Comment by christianpaquin** [comment]
@dstebila, I compiled this with clang and it worked. Can you try to reproduce the travis build failure (clang on macOS?) Thanks.

**Comment by dstebila** [comment]
Got the same error on my Mac: 

```
/bin/sh ./libtool  --tag=CC   --mode=link gcc -std=gnu11 -Wall -Wextra -Werror  -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized  -Wshadow -Wformat-security -Wwrite-strings  -Wno-missing-braces -Wno-missing-field-initializers -g  -fPIC  -fvisibility=hidden  -I/Users/dstebila/Desktop/OQS/cp-liboqs/include -I.  -I/usr/local/opt/openssl@1.1/include  -O3  -fomit-frame-pointer  -DCONSTANT_TIME  -g -O2  -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -mbmi2 -maes -I/usr/local/opt/openssl@1.1/include  -L/usr/local/opt/openssl@1.1/lib -o liboqs.la -rpath /usr/local/lib  src/common/libcommon.la src/crypto/aes/libaes.la src/crypto/sha2/libsha2.la src/crypto/sha3/libsha3.la src/kem/libkem.la src/sig/libsig.la src/sig/picnic/libpicnic_i.la src/sig/qtesla/libqtesla.la  src/kem/kyber/libkemkyber.la src/kem/newhope/libkemnewhope.la src/kem/ntru/libkemntru.la src/kem/saber/libkemsaber.la src/sig/dilithium/libsigdilithium.la src/sig/mqdss/libsigmqdss.la src/sig/sphincs/libsigsphincs.la src/kem/frodokem/libkemfrodokem.la src/kem/sike/libkemsike.la -L/usr/local/opt/openssl@1.1/lib -lcrypto 
libtool: link: gcc -dynamiclib -Wl,-undefined -Wl,dynamic_lookup -o .libs/liboqs.0.dylib   -Wl,-force_load,src/common/.libs/libcommon.a -Wl,-force_load,src/crypto/aes/.libs/libaes.a -Wl,-force_load,src/crypto/sha2/.libs/libsha2.a -Wl,-force_load,src/crypto/sha3/.libs/libsha3.a -Wl,-force_load,src/kem/.libs/libkem.a -Wl,-force_load,src/sig/.libs/libsig.a -Wl,-force_load,src/sig/picnic/.libs/libpicnic_i.a -Wl,-force_load,src/sig/qtesla/.libs/libqtesla.a -Wl,-force_load,src/kem/kyber/.libs/libkemkyber.a -Wl,-force_load,src/kem/newhope/.libs/libkemnewhope.a -Wl,-force_load,src/kem/ntru/.libs/libkemntru.a -Wl,-force_load,src/kem/saber/.libs/libkemsaber.a -Wl,-force_load,src/sig/dilithium/.libs/libsigdilithium.a -Wl,-force_load,src/sig/mqdss/.libs/libsigmqdss.a -Wl,-force_load,src/sig/sphincs/.libs/libsigsphincs.a -Wl,-force_load,src/kem/frodokem/.libs/libkemfrodokem.a -Wl,-force_load,src/kem/sike/.libs/libkemsike.a  -L/usr/local/opt/openssl@1.1/lib -lcrypto  -g -O3 -g -O2 -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mavx2 -mfma -mbmi -mbmi2 -maes   -install_name  /usr/local/lib/liboqs.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module
ld: illegal text reloc in 'oqs_kem_sike_fpadd434_asm' to 'p434x2' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by christianpaquin** [comment]
OK, thanks @dstebila for the confirmation, I'll investigate further.

**Comment by christianpaquin** [comment]
@dstebila (and @xvzcfj, if you know), I'm testing on a mac mini, and I'm getting a different error. Do you know how to check the supported computer flags on a mac, the equivalent to the linux `cat /proc/cpuinfo | grep flags` ?

**Comment by dstebila** [comment]
> @dstebila (and @xvzcfj, if you know), I'm testing on a mac mini, and I'm getting a different error. Do you know how to check the supported computer flags on a mac, the equivalent to the linux `cat /proc/cpuinfo | grep flags` ?

No, I don't know, other than using the C function `__builtin_cpu_supports` as used in https://github.com/open-quantum-safe/liboqs/blob/master/config/ax_x86_cpu_supports.m4

**Comment by dstebila** [comment]
If you try rebasing on #597 you will get the macOS CI switched over to CircleCI, and then you should be able to get SSH access for a debug job on that.

**Comment by christianpaquin** [comment]
Ah, great @dstebila. Will #597 be merged with master soon? If so, I'll sync-up (otherwise I can pull changes from that PR).

**Comment by dstebila** [comment]
> Ah, great @dstebila. Will #597 be merged with master soon? If so, I'll sync-up (otherwise I can pull changes from that PR).

Merged now.

**Comment by christianpaquin** [comment]
> > Ah, great @dstebila. Will #597 be merged with master soon? If so, I'll sync-up (otherwise I can pull changes from that PR).
> 
> Merged now.

CircleCI's macOS test fails; can you point me to debugging information for CircleCI?

**Comment by dstebila** [comment]
> CircleCI's macOS test fails; can you point me to debugging information for CircleCI?

Click through to the failed job in CircleCI, then in the top right look at the "Rerun workflow" dropdown and there will be an alternative to "Rerun job with SSH".

**Comment by christianpaquin** [comment]
> Click through to the failed job in CircleCI, then in the top right look at the "Rerun workflow" dropdown and there will be an alternative to "Rerun job with SSH".

It says: "you need write permissions to trigger builds". Can't you give me access?

**Comment by dstebila** [comment]
Can we close this PR? As I understand it, #632 replaces it.

**Comment by christianpaquin** [comment]
> Can we close this PR? As I understand it, #632 replaces it.

Yes

**Pull request closed without merging**
