### PR TITLE
Updated to SIKE v3.5.1

### LINKED ISSUE #1227: Integrate SIKE v3.5.1
https://github.com/microsoft/PQCrypto-SIDH/releases/tag/v3.5.1  ([diff](https://github.com/microsoft/PQCrypto-SIDH/compare/effa607f244768cdd38f930887076373604eaa78...v3.5.1))

### PR DESCRIPTION
**Pull request by christianpaquin**
Updated SIKE to v3.5.1. Fixes #1227.

### CODE REVIEW

**Comment by bhess** [comment]
A working workaround should be to configure p503 and p751 the same way as p434 and p610:

https://github.com/open-quantum-safe/liboqs/blob/f88b9c96bff455e8a76b3e51dcf6bb1027120b76/src/kem/sike/CMakeLists.txt#L59-L75

https://github.com/open-quantum-safe/liboqs/blob/f88b9c96bff455e8a76b3e51dcf6bb1027120b76/src/kem/sike/CMakeLists.txt#L106-L122

**Comment by baentsch** [comment]
Thanks, @bhess -- would you mind updating the branch and getting the PR to pass CI/merge readiness as @christianpaquin is on vacation?

**Comment by bhess** [comment]
> @bhess -- would you mind updating the branch and getting the PR to pass CI

Updated accordingly to pass CI.

**Comment by baentsch** [comment]
> Updated accordingly to pass CI.

Thanks very much, @bhess ! Anything missing to move this to Review and merge? I'd personally be glad to release 0.7.2 finally to bring some "order" to upstream OpenSSL...

**Review by dstebila — APPROVED** [review]
Thaks @bhess and @baentsch for figuring this out!

**Comment by christianpaquin** [comment]
Thanks for the help, @bhess! Too bad we had to pull the code in #1272.

**Pull request merged**
