### PR TITLE
Update kem_saber.md

### PR DESCRIPTION
**Pull request by vsoftco**
typo

### CODE REVIEW

**Comment by dstebila** [comment]
@christianpaquin Any idea what this build failure in AppVeyor means?  I'm at a loss on how changing a text file could have triggered a build failure...

**Comment by christianpaquin** [comment]
appveyor shouldn't run on the nist-branch, since there are no VS projects...

**Comment by dstebila** [comment]
Oh right, of course.  appveyor.yml disables it for all branches that contain the word "nist", but this patch's branch doesn't.

**Comment by dstebila** [comment]
@vsoftco why do you think this is a typo?  The assumption is Module Learning with Rounding, MLWR seems like the right abbreviation.  (In the NIST submission documentation, they use Module-LWR.)

**Comment by vsoftco** [comment]
> @vsoftco why do you think this is a typo? The assumption is Module Learning with Rounding, MLWR seems like the right abbreviation. (In the NIST submission documentation, they use Module-LWR.)

My bad, sorry, I read it as "module learning with errors"... Please ignore.

**Pull request closed without merging**
