### PR TITLE
Use valgrind to check for secret-dependent branching on 'audit' branches

### PR DESCRIPTION
**Pull request by jschanck**
This PR should run the full set of constant-time checks on #881.

### CODE REVIEW

**Review by dstebila — APPROVED** [review]

**Comment by dstebila** [comment]
Thanks John! To make sure I understand: The "issues" files log places that don't pass Valgrind's checks.  For each of these we've checked with the authors that they believe these are not problematic from a security perspective.  But an ideal version would have no issues files.

**Review by baentsch — APPROVED** [review]
LGTM. Should `OQS_ENABLE_TEST_CONSTANT_TIME` also be documented in https://github.com/open-quantum-safe/liboqs/wiki/Customizing-liboqs ? Leave it to you -- maybe too much documentation also confuses too many people :-)

**Comment by jschanck** [comment]
> Thanks John! To make sure I understand: The "issues" files log places that don't pass Valgrind's checks. For each of these we've checked with the authors that they believe these are not problematic from a security perspective. But an ideal version would have no issues files.

Almost. The "issues" files log errors that are either awaiting review or are known to be actual problems. Once we have review of an "issue" it should be moved to "passes".

Here's the current status.

The open issues for SIDH/SIKE are:
* sidh_vartime_bingcd_final_C24 
* sike_vartime_bingcd_final_C24
* sike_compressed_verify_ladder
* sike_memcmp

The first two can be moved to "passes" based on reviews from #888. The second two will be fixed by #914. I'll resolve all four issues once #914 merges.

Bike and HQC have genuine non-constant time behaviour, documented by:
* bike_has_no_timing_protections
* hqc_fast_convolution_mult
* hqc_gf_mul
* hqc_vect_set_random_fixed_weight

And there's one falcon issue that can be fixed by pulling from pqclean.
* falcon_hash_to_point_vartime

**Comment by jschanck** [comment]
BIKE failed on the last run---rather than try to whitelist the entire implementation I'm just disabling test_constant_time for BIKE.

**Comment by dstebila** [comment]
Thanks John. I made #917 to track updating Falcon (and others) from PQClean.

**Comment by baentsch** [comment]
> BIKE failed on the last run---rather than try to whitelist the entire implementation I'm just disabling test_constant_time for BIKE.

If we decide to merge in this state to move forward, may I suggest to create an issue to track such test-disablements (and/or document them in the algorithm-review-yml if we don't get this fixed before a release) to not forget this?

**Comment by jschanck** [comment]
This is failing with a new type of timeout.

Options:
* Move this out of CI.
* Split into kem and sig jobs that run in separate containers.
* Skip some of the heavy schemes.

I'm happy to wait until after 0.5.0.

**Comment by baentsch** [comment]
FWIW, I'd vote for 

> Skip some of the heavy schemes.

and merge now (plus create an issue to fix this long-term -- I'd suggest outside of CI, e.g., using a github action on release).

**Comment by jschanck** [comment]
This is ready to go.

**Review by dstebila — APPROVED** [review]

**Pull request merged**
