### PR TITLE
Add cpp linking test

### PR DESCRIPTION
**Pull request by aidenfoxivey**
Accidentally deleted #1944 and as a result I've remade the PR. I'll make sure to clean up the commits prior to merging if there's any desire to change what I've written here.

I've applied the advice from earlier to move the C++ example to `.github` and added a workflow to `basic.yml`.

### CODE REVIEW

**Comment by aidenfoxivey** [comment]
I think I'll need to run CI to test whether basic.yml runs with changes - but I assume that's only something the code owners can do.

**Comment by Martyrshot** [comment]
Hm. @dstebila It seems like I lost the ability to unblock ci.

**Comment by aidenfoxivey** [comment]
@Martyrshot Just to be certain, this is the location you had in mind for the C++ file, right?

**Comment by Martyrshot** [comment]
Yes that's what I meant! Once CI is able to be run, I will give this a review. Initial scim looks good though!

**Comment by dstebila** [comment]
> Hm. @dstebila It seems like I lost the ability to unblock ci.

You're still listed on the liboqs-committers team so I would think you have the ability to unblock. @ryjones, any ideas?  Could it be cause Aiden's PR is in his own fork?

**Comment by SWilson4** [comment]
For what it's worth, I'm also not seeing any pending CI jobs here, and I certainly have perms to unblock them. I wonder if it's because there's a merge conflict in the basic workflow file?

**Comment by aidenfoxivey** [comment]
> For what it's worth, I'm also not seeing any pending CI jobs here, and I certainly have perms to unblock them. I wonder if it's because there's a merge conflict in the basic workflow file?

Maybe I can amend the commit to avoid having the merge conflict.

**Comment by aidenfoxivey** [comment]
Alright, we have a rather predictable issue with the path lol. I'll sort that out.

**Comment by ryjones** [comment]
Screenshot 2024-10-24 at 11 24 51
I clicked this button - did nobody else see it?

**Comment by ryjones** [comment]
I might rebase your commit on top of main instead of having a merge commit

**Comment by ryjones** [comment]
I tried a rebase but there is a merge conflict

**Comment by aidenfoxivey** [comment]
> I tried a rebase but there is a merge conflict

Yeah, I had the same exact experience unfortunately. My git knowledge is not that good if I'm being honest.

**Comment by ryjones** [comment]
OK I re-wrote the commit let's see how it goes. I suspect the test cpp file needs to live elsewhere

**Comment by ryjones** [comment]
OK @aidenfoxivey I think you can drive from here, I'll stop messing about

**Comment by aidenfoxivey** [comment]
> OK @aidenfoxivey I think you can drive from here, I'll stop messing about

Sounds good!

**Comment by aidenfoxivey** [comment]
I suspect the issue is the prepended /.

**Comment by ryjones** [comment]
@aidenfoxivey I restored the empty file

**Comment by aidenfoxivey** [comment]
> @aidenfoxivey I restored the empty file

awesome! let's see how this run goes

**Comment by ryjones** [comment]
@aidenfoxivey are you able to build this locally?

**Comment by aidenfoxivey** [comment]
> @aidenfoxivey are you able to build this locally?

yeah, locally it seems fine - that's what's confusing me.

**Comment by aidenfoxivey** [comment]
CleanShot 2024-10-25 at 12 47 48@2x

I'm honestly a little bit confused. From what I can tell, this is the current name of the c++ file. Perhaps I'm misunderstanding what the current directory is in Github actions?

**Comment by ryjones** [comment]
maybe do an `ls -lR .*` at the top?

**Comment by aidenfoxivey** [comment]
let's give this a go

**Comment by aidenfoxivey** [comment]
Whoops!

**Comment by aidenfoxivey** [comment]
Okay, sorted it out.

**Comment by aidenfoxivey** [comment]
Hmm, so, if I understand correctly this is running from `build`, but somehow the header file isn't being found.

**Comment by ryjones** [comment]
@aidenfoxivey let me know when it is safe to rewrite your commit tree to make it shorter :)

**Comment by ryjones** [comment]
Please see #1963

**Pull request closed without merging**
