### PR TITLE
Add minimal c++ example and check

### LINKED ISSUE #1770: Add C++ test to ci
There was an issue compiling the `stateful-sigs` branch for `C++`, but CI was passing. We should probably add a simple c++ test to CI to prevent issues like this in the future.

### PR DESCRIPTION
**Pull request by aidenfoxivey**
Adding a simple C++ test to CI.

Fixes #1770.

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
Doesn't change any cryptographic algorithms.

* [ ] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for review and merge by the time this is merged.)
Doesn't change any cryptographic algorithms.

### CODE REVIEW

**Comment by vsoftco** [comment]
@aidenfoxivey We have a C++ wrapper that provides all the required RAII , https://github.com/open-quantum-safe/liboqs-cpp

**Comment by aidenfoxivey** [comment]
@vsoftco Would it be fair to rework this with the C++ bindings and then continue working on the PR?

**Comment by aidenfoxivey** [comment]
Absolutely fine to close the PR too, but I feel like it should probably be addressed in the issue first, just to make the procedure clear.

**Comment by Martyrshot** [comment]
@vsoftco The purpose of this is to catch syntax errors in C++. For example when the stateful-sigs PR was in progress we almost merged something that compiled for C but failed to link against a C++ target.

Since we have #ifdef CPLUSPLUS blocks in our headers I think this check needs to be done

**Comment by aidenfoxivey** [comment]
@Martyrshot Do we want to compile and run the resulting example file? (and/or use valgrind to check it for leaks?) in my existing implementation I'm just compiling and linking it.

**Comment by Martyrshot** [comment]
I think valgrind for this is overkill, but running it is a good idea. It could catch weird runtime linking errors. Sorry I should have thought about this sooner. Would it be much work for you to add this test to the ninja `run_tests` rule? Then it would always be run rather then having a specific ci job.

If it's too much work, I can take a look into doing this later in the week.

**Comment by aidenfoxivey** [comment]
Oh no, don't worry about it! I can absolutely sort it out later tonight or tomorrow.

**Comment by aidenfoxivey** [comment]
@Martyrshot I thought about it a bit and, if I understand you correctly, this requires modifying the CMakeLists.txt to add C++ as a LANGUAGE. Are you cool with that?

**Comment by Martyrshot** [comment]
Would we be able to isolate that to _just_ this test?

**Comment by aidenfoxivey** [comment]
The `ninja` run-tests is generated based on CMakeLists.txt right? I think in that case, you pretty much have to change the CMake infrastructure to allow it to build whenever you call `ninja run-tests`. The reason I didn't have to earlier was because I was just hardcoding a call to `g++` in the Github action.

**Comment by Martyrshot** [comment]
That's fair. Then in that case I think we should avoid modifying `CMakeLists.txt`. Let's relocate the `.cpp` file you created into the `.github` folder somewhere so that it's not mistaken as a core liboqs test. Then have the c++ action run the test and enforce that it doesn't error.

**Comment by aidenfoxivey** [comment]
Should have this sorted by end of next week. Apologies about the delay - midterms :)

**Comment by baentsch** [comment]
> midterms :)

Good luck!

**Comment by Martyrshot** [comment]
> Should have this sorted by end of next week. Apologies about the delay - midterms :)

No worries! Good luck!

**Pull request closed without merging**
