### PR TITLE
Adding separate AVX2 runtime-checked common/sha3

### PR DESCRIPTION
**Pull request by baentsch**
In pursuit of #624 provide clean and RT-protected AVX2 optimised variant(s) of SHA3.

### CODE REVIEW

**Comment by dstebila** [comment]
A few of the files look like they are duplicated in both src/common and src/common\_avx2, such as sha3\_ossl.c and sha3\_c.c.  Is that true? (If so, why?) Or are there differences? (If so, then we should make a note about those differences so they can be preserved if the different versions of the files get updated.)

**Comment by baentsch** [comment]
Indeed, `sha3_ossl.c` is an oversight and could be deleted (as for all I know it has no AVX2 dependency). `sha3_c.c` in the AVX2 case does carry a few stubs necessary/worth retaining (the redundant stuff I deleted). What is true, though, is that the core "functionality" files are exact copies and get different "functionality" only by #defines putting them into a different symbol namespace. I'm just not sure whether symlinks are possible across platforms (Windows?)

**Comment by xvzcf** [comment]
I'll take a look at this once the fix for https://github.com/open-quantum-safe/liboqs/issues/695 goes in.

**Comment by baentsch** [comment]
> I'll take a look at this once the fix for #695 goes in.

Thanks in advance. If you don't get around to it this week, please let me know -- I'll then update this based on the current defines incl. `OQS_PORTABLE_BUILD` (which I like, btw). I'd probably try to copy the `common/sha3/* files into the `common_avx2` tree to avoid the actual duplication. But if you have a better idea, @xvzcf please post a comment (or just do a PR obviating this one -- whatever is easier for you).

**Comment by xvzcf** [comment]
I'm not sure I understand how the runtime feature detection and dynamic dispatch is happening here.

**Comment by baentsch** [comment]
I once learned from a wise man "If they didn't hear it, you didn't say it". In this case, I need to rework this to make it clear(er). The base idea was to create 'avx2'-tagged SHA3 entry points via #defines and compile those separately from the "normal" (clean/non-avx2) code base. Runtime-switching occurred in `sha3_c.c`. Let me take another stab at this, hopefully reducing the amount of files involved.

**Comment by xvzcf** [comment]
Hmm I see. I was looking into the possibility of having a `sha3_portable.c` file, in which, for example, there is a `OQS_SHA3_cshake128_optimized_portable` that switches between `OQS_SHA3_cshake128_simple4x` and `OQS_SHA3_cshake128_simple` much the same way as the `kem_{{ scheme }}.c` files for the PQClean algorithms. 

There are only 2 public `4x` functions, so the work shouldn't be that much.

**Comment by baentsch** [comment]
Well, it's not only the `4x` functions -- many other parts of what (seems to be) "clean" C code benefits from (& get compiled into) AVX2 instructions, too.

**Comment by baentsch** [comment]
Withdrawing in favour of integrating XKCP

**Pull request closed without merging**
