### PR TITLE
Set ML-KEM alg_version to "FIPS203"

### LINKED ISSUE #1996: Update ML-KEM alg_version to "FIPS203"
I assume we will want to do this for consistency with ML-DSA as per discussion here: https://github.com/open-quantum-safe/liboqs/pull/1919#discussion_r1844299975

### PR DESCRIPTION
**Pull request by SWilson4**
To bring ML-KEM in line with the upcoming ML-DSA update.

Fixes #1996 

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Review by baentsch — COMMENTED** [review]
Pretty massive changes for 3 lines of code... Ideas why this is so?

**Comment by SWilson4** [comment]
> Pretty massive changes for 3 lines of code... Ideas why this is so?

I did wonder about this also. I generated the patch using `git diff-tree` [as documented here](https://github.com/open-quantum-safe/liboqs/wiki/Patching-upstream-sources). It looks to me as if the original patch was generated with `git diff`—when I update the patch using `git diff` the diff (of the diff) is much smaller, as I would have expected.

I'm fine to update the patch with `git diff` instead to make the changes easier to view.

**Review by dstebila — APPROVED** [review]

**Comment by dstebila** [comment]
Looking for one more review @open-quantum-safe/liboqs-committers

**Review by Martyrshot — APPROVED** [review]
LGTM!

**Pull request merged**
