### PR TITLE
Add OpenSSL's PRNG as default on nist-branch

### PR DESCRIPTION
**Pull request by dstebila**

### CODE REVIEW

**Comment by dstebila** [comment]
Previously we were implementing randombytes by reading directly from `/dev/urandom`.  When looking at the `speed_kem` results (first table), notice that keygen and encaps operations are quite slow with little variation between algorithms; this is because a lot of time is spent opening and reading from the `/dev/urandom` file on every call.

I think it is more realistic if we use something like OpenSSL's `RAND_bytes` as the PRNG, because it doesn't have to read from file on every call. The `speed_kem` results (second table) seem much more appropriate.

## `speed_kem` results with `/dev/urandom`

Operation                      | Iterations | Total time (s) | Time (us): mean | pop. stdev | CPU cycles: mean | pop. stdev
------------------------------ | ----------:| --------------:| ---------------:| ----------:| ----------------:| ----------:
NewHope1024-CCA-KEM            |            |                |                 |            |                  |           
keygen                         |        301 |          3.007 |        9988.854 |   1175.787 |         25911471 |    3049850
encaps                         |        593 |          3.001 |        5061.513 |    658.041 |         13129536 |    1706943
decaps                         |      17923 |          3.000 |         167.384 |     43.782 |           433997 |     112015
FrodoKEM-640-AES               |            |                |                 |            |                  |           
keygen                         |        142 |          3.004 |       21154.986 |   1715.938 |         54877166 |    4451114
encaps                         |        136 |          3.009 |       22123.632 |   1738.369 |         57390029 |    4509444
decaps                         |        181 |          3.004 |       16594.486 |   1296.351 |         43046785 |    3362847
FrodoKEM-976-AES               |            |                |                 |            |                  |           
keygen                         |         72 |          3.034 |       42132.292 |   1698.605 |        109294373 |    4406359
encaps                         |         71 |          3.032 |       42709.239 |   1854.989 |        110791051 |    4812167
decaps                         |         81 |          3.035 |       37474.802 |   1977.157 |         97212302 |    5128803
FrodoKEM-640-cSHAKE            |            |                |                 |            |                  |           
keygen                         |        342 |          3.000 |        8772.757 |    979.108 |         22756788 |    2539892
encaps                         |        336 |          3.005 |        8944.571 |    946.162 |         23202575 |    2454398
decaps                         |        722 |          3.004 |        4160.271 |    570.685 |         10791659 |    1480297
FrodoKEM-976-cSHAKE            |            |                |                 |            |                  |           
keygen                         |        229 |          3.002 |       13109.389 |   1317.653 |         34006217 |    3418005
encaps                         |        221 |          3.000 |       13575.765 |   1311.844 |         35216066 |    3402922
decaps                         |        334 |          3.004 |        8994.024 |    986.093 |         23330548 |    2557625
NewHope512-CCA-KEM             |            |                |                 |            |                  |           
keygen                         |        304 |          3.005 |        9885.405 |   1011.222 |         25643063 |    2623011
encaps                         |        604 |          3.004 |        4974.240 |    610.528 |         12903194 |    1583664
decaps                         |      38601 |          3.000 |          77.720 |     14.245 |           201502 |      36863
NewHope1024-CCA-KEM            |            |                |                 |            |                  |           
keygen                         |        302 |          3.002 |        9941.599 |   1041.102 |         25788906 |    2700581
encaps                         |        580 |          3.005 |        5181.041 |    735.566 |         13439544 |    1908040
decaps                         |      18496 |          3.000 |         162.204 |     28.887 |           420620 |      74847
Kyber512                       |            |                |                 |            |                  |           
keygen                         |        296 |          3.008 |       10162.301 |   1212.968 |         26361287 |    3146239
encaps                         |        589 |          3.002 |        5097.587 |    726.571 |         13223161 |    1884632
decaps                         |      29128 |          3.000 |         102.996 |     18.344 |           267069 |      47515
Kyber768                       |            |                |                 |            |                  |           
keygen                         |        295 |          3.009 |       10198.563 |   1174.778 |         26455410 |    3047272
encaps                         |        578 |          3.004 |        5197.822 |    685.557 |         13483073 |    1778287
decaps                         |      20104 |          3.000 |         149.228 |     25.008 |           386957 |      64758
Kyber1024                      |            |                |                 |            |                  |           
keygen                         |        303 |          3.003 |        9911.842 |    759.190 |         25711562 |    1969150
encaps                         |        584 |          3.003 |        5141.885 |    599.924 |         13338056 |    1556193
decaps                         |      14163 |          3.000 |         211.823 |     33.375 |           549302 |      86439
Sike-p503                      |            |                |                 |            |                  |           
keygen                         |         68 |          3.007 |       44227.191 |   2393.831 |        114728836 |    6209890
encaps                         |         49 |          3.016 |       61544.163 |   2325.185 |        159650555 |    6031573
decaps                         |         50 |          3.044 |       60880.080 |   2766.753 |        157927842 |    7177286
Sike-p751                      |            |                |                 |            |                  |           
keygen                         |         24 |          3.004 |      125179.458 |   3842.640 |        324726996 |    9967887
encaps                         |         16 |          3.102 |      193903.563 |   5064.576 |        503004079 |   13137738
decaps                         |         15 |          3.048 |      203176.067 |   5947.569 |        527058503 |   15428101
BIG_QUAKE_1                    |            |                |                 |            |                  |           
keygen                         |          8 |          3.051 |      381345.375 |   6814.785 |        989247455 |   17678839
encaps                         |       2064 |          3.002 |        1454.422 |    209.867 |          3772622 |     544332
decaps                         |       1567 |          3.001 |        1915.235 |    277.700 |          4967913 |     720296
BIG_QUAKE_3                    |            |                |                 |            |                  |           
keygen                         |          1 |          3.353 |     3353320.000 |      0.000 |        108917388 |          0
encaps                         |        868 |          3.003 |        3459.240 |    495.257 |          8973193 |    1284607
decaps                         |        286 |          3.002 |       10495.664 |   1527.304 |         27225785 |    3961865
BIG_QUAKE_5                    |            |                |                 |            |                  |           
keygen                         |          1 |          6.240 |     6239589.000 |      0.000 |       3301227975 |          0
encaps                         |        594 |          3.001 |        5051.808 |    640.188 |         13104234 |    1660523
decaps                         |        178 |          3.005 |       16879.528 |   2866.094 |         43786165 |    7434969
BIKE1-L1                       |            |                |                 |            |                  |           
keygen                         |        533 |          3.004 |        5636.580 |    792.903 |         14620911 |    2056762
encaps                         |        560 |          3.005 |        5365.557 |    655.028 |         13918974 |    1699226
decaps                         |       1477 |          3.001 |        2031.958 |    277.495 |          5271086 |     719774
BIKE1-L3                       |            |                |                 |            |                  |           
keygen                         |        523 |          3.004 |        5744.226 |    653.978 |         14901652 |    1696482
encaps                         |        477 |          3.004 |        6298.671 |    815.038 |         16339802 |    2114265
decaps                         |        506 |          3.003 |        5934.868 |    621.092 |         15395804 |    1611180
BIKE1-L5                       |            |                |                 |            |                  |           
keygen                         |        427 |          3.000 |        7026.520 |    845.277 |         18227582 |    2192676
encaps                         |        387 |          3.004 |        7762.274 |    758.740 |         20136297 |    1968179
decaps                         |        202 |          3.005 |       14876.376 |   1371.666 |         38591261 |    3558290
BIKE2-L1                       |            |                |                 |            |                  |           
keygen                         |        289 |          3.005 |       10398.768 |   1104.647 |         26975402 |    2865570
encaps                         |        580 |          3.004 |        5179.510 |    667.274 |         13435939 |    1730960
decaps                         |       1663 |          3.002 |        1804.895 |    240.951 |          4681690 |     624964
BIKE2-L3                       |            |                |                 |            |                  |           
keygen                         |        122 |          3.003 |       24614.361 |   1912.524 |         63851759 |    4961436
encaps                         |        522 |          3.005 |        5755.946 |    784.945 |         14931117 |    2036158
decaps                         |        558 |          3.004 |        5382.930 |    675.032 |         13963460 |    1751014
BIKE2-L5                       |            |                |                 |            |                  |           
keygen                         |         51 |          3.030 |       59409.059 |   2504.057 |        154113358 |    6495444
encaps                         |        435 |          3.004 |        6906.418 |    906.083 |         17915542 |    2350376
decaps                         |        208 |          3.008 |       14459.803 |   1461.639 |         37509730 |    3791451
BIKE3-L1                       |            |                |                 |            |                  |           
keygen                         |        584 |          3.003 |        5142.885 |    699.539 |         13340748 |    1814568
encaps                         |        558 |          3.005 |        5385.565 |    730.135 |         13970202 |    1893972
decaps                         |       1499 |          3.001 |        2001.728 |    275.274 |          5192293 |     713976
BIKE3-L3                       |            |                |                 |            |                  |           
keygen                         |        551 |          3.002 |        5448.461 |    742.076 |         14133402 |    1924909
encaps                         |        478 |          3.003 |        6282.814 |    765.834 |         16297673 |    1986617
decaps                         |        448 |          3.003 |        6703.489 |    696.878 |         17388949 |    1807557
BIKE3-L5                       |            |                |                 |            |                  |           
keygen                         |        490 |          3.003 |        6129.229 |    718.743 |         15899285 |    1864420
encaps                         |        356 |          3.003 |        8434.351 |    879.176 |         21878887 |    2280672
decaps                         |        179 |          3.012 |       16824.860 |   1443.049 |         43644632 |    3743276

## `speed_kem` results with OpenSSL RAND_bytes

Operation                      | Iterations | Total time (s) | Time (us): mean | pop. stdev | CPU cycles: mean | pop. stdev
------------------------------ | ----------:| --------------:| ---------------:| ----------:| ----------------:| ----------:
NewHope1024-CCA-KEM            |            |                |                 |            |                  |           
keygen                         |      31649 |          3.000 |          94.792 |     18.240 |           245747 |      47217
encaps                         |      21125 |          3.000 |         142.012 |     24.334 |           368259 |      63048
decaps                         |      18120 |          3.000 |         165.566 |     28.378 |           429356 |      73527
FrodoKEM-640-AES               |            |                |                 |            |                  |           
keygen                         |        188 |          3.001 |       15962.431 |   1416.922 |         41407273 |    3675554
encaps                         |        187 |          3.016 |       16126.487 |   1400.000 |         41832904 |    3631701
decaps                         |        182 |          3.000 |       16485.005 |   1569.459 |         42762826 |    4071300
FrodoKEM-976-AES               |            |                |                 |            |                  |           
keygen                         |         81 |          3.012 |       37180.691 |   2865.841 |         96449344 |    7434199
encaps                         |         79 |          3.028 |       38325.316 |   2578.831 |         99418823 |    6689812
decaps                         |         80 |          3.006 |       37576.537 |   2213.429 |         97476331 |    5741638
FrodoKEM-640-cSHAKE            |            |                |                 |            |                  |           
keygen                         |        773 |          3.001 |        3881.793 |    542.428 |         10069214 |    1406867
encaps                         |        735 |          3.001 |        4082.924 |    469.303 |         10590949 |    1217227
decaps                         |        716 |          3.004 |        4196.032 |    554.800 |         10884408 |    1439105
FrodoKEM-976-cSHAKE            |            |                |                 |            |                  |           
keygen                         |        360 |          3.004 |        8344.511 |    989.800 |         21645707 |    2567424
encaps                         |        336 |          3.009 |        8954.399 |   1080.824 |         23227786 |    2803487
decaps                         |        332 |          3.009 |        9064.102 |   1115.427 |         23512281 |    2893158
NewHope512-CCA-KEM             |            |                |                 |            |                  |           
keygen                         |      63414 |          3.000 |          47.309 |      9.464 |           122617 |      24460
encaps                         |      41719 |          3.000 |          71.910 |     21.478 |           186403 |      55556
decaps                         |      37367 |          3.000 |          80.286 |     14.590 |           208157 |      37750
NewHope1024-CCA-KEM            |            |                |                 |            |                  |           
keygen                         |      31474 |          3.000 |          95.320 |     18.851 |           247114 |      48786
encaps                         |      21266 |          3.000 |         141.074 |     25.017 |           365821 |      64803
decaps                         |      17997 |          3.000 |         166.698 |     29.020 |           432272 |      75168
Kyber512                       |            |                |                 |            |                  |           
keygen                         |      49318 |          3.000 |          60.831 |     12.961 |           157674 |      33498
encaps                         |      35701 |          3.000 |          84.032 |     15.139 |           217813 |      39146
decaps                         |      29714 |          3.000 |         100.965 |     17.807 |           261792 |      46091
Kyber768                       |            |                |                 |            |                  |           
keygen                         |      31157 |          3.000 |          96.287 |     17.487 |           249665 |      45287
encaps                         |      22813 |          3.000 |         131.506 |     24.862 |           340981 |      64368
decaps                         |      19903 |          3.000 |         150.733 |     25.666 |           390883 |      66505
Kyber1024                      |            |                |                 |            |                  |           
keygen                         |      21478 |          3.000 |         139.681 |     24.893 |           362222 |      64490
encaps                         |      16806 |          3.000 |         178.512 |     29.644 |           462932 |      76801
decaps                         |      14550 |          3.000 |         206.200 |     34.193 |           534772 |      88621
Sike-p503                      |            |                |                 |            |                  |           
keygen                         |         85 |          3.016 |       35483.200 |   2115.836 |         92045754 |    5488919
encaps                         |         54 |          3.055 |       56581.963 |   6206.796 |        146778130 |   16101170
decaps                         |         51 |          3.012 |       59066.157 |   3368.180 |        153222343 |    8737382
Sike-p751                      |            |                |                 |            |                  |           
keygen                         |         26 |          3.070 |      118078.077 |   4741.943 |        306305178 |   12301038
encaps                         |         16 |          3.030 |      189403.312 |   6598.867 |        491330312 |   17118467
decaps                         |         15 |          3.055 |      203675.400 |   5135.541 |        528353818 |   13322224
BIG_QUAKE_1                    |            |                |                 |            |                  |           
keygen                         |          8 |          3.170 |      396255.875 |  21668.008 |       1027927154 |   56209063
encaps                         |       2008 |          3.001 |        1494.618 |    233.642 |          3876835 |     605969
decaps                         |       1610 |          3.002 |        1864.385 |    276.479 |          4835894 |     716998
BIG_QUAKE_3                    |            |                |                 |            |                  |           
keygen                         |          1 |          3.263 |     3263172.000 |      0.000 |       4170033420 |          0
encaps                         |        883 |          3.001 |        3398.894 |    413.632 |          8816459 |    1072839
decaps                         |        267 |          3.002 |       11242.618 |   2384.137 |         29163351 |    6184561
BIG_QUAKE_5                    |            |                |                 |            |                  |           
keygen                         |          1 |          6.081 |     6080571.000 |      0.000 |       2888719989 |          0
encaps                         |        621 |          3.006 |        4840.293 |    595.361 |         12555644 |    1544293
decaps                         |        183 |          3.008 |       16436.847 |   2691.950 |         42637804 |    6982975
BIKE1-L1                       |            |                |                 |            |                  |           
keygen                         |      12341 |          3.000 |         243.101 |     44.512 |           630448 |     115384
encaps                         |       8041 |          3.000 |         373.132 |     71.653 |           967690 |     185777
decaps                         |       1357 |          3.000 |        2211.027 |    374.982 |          5735044 |     972600
BIKE1-L3                       |            |                |                 |            |                  |           
keygen                         |       3922 |          3.000 |         764.937 |     99.948 |          1984021 |     259087
encaps                         |       2655 |          3.000 |        1129.957 |    131.198 |          2930880 |     340190
decaps                         |        540 |          3.002 |        5558.770 |    492.308 |         14419381 |    1276916
BIKE1-L5                       |            |                |                 |            |                  |           
keygen                         |       1591 |          3.000 |        1885.843 |    152.258 |          4891650 |     394886
encaps                         |       1053 |          3.000 |        2849.247 |    266.939 |          7390731 |     692376
decaps                         |        229 |          3.006 |       13125.459 |   1168.659 |         34048000 |    3031548
BIKE2-L1                       |            |                |                 |            |                  |           
keygen                         |        589 |          3.001 |        5094.463 |    507.726 |         13215029 |    1316952
encaps                         |      13335 |          3.000 |         224.981 |     32.326 |           583416 |      83771
decaps                         |       1439 |          3.000 |        2085.106 |    267.664 |          5408538 |     694252
BIKE2-L3                       |            |                |                 |            |                  |           
keygen                         |        152 |          3.010 |       19799.822 |   1336.921 |         51361607 |    3468183
encaps                         |       3886 |          3.000 |         772.115 |    133.564 |          2002666 |     346389
decaps                         |        568 |          3.007 |        5294.039 |    669.793 |         13732613 |    1737354
BIKE2-L5                       |            |                |                 |            |                  |           
keygen                         |         55 |          3.016 |       54844.473 |   2578.545 |        142270772 |    6688950
encaps                         |       1580 |          3.002 |        1899.781 |    251.831 |          4927702 |     653178
decaps                         |        219 |          3.005 |       13723.580 |   1273.785 |         35599476 |    3304259
BIKE3-L1                       |            |                |                 |            |                  |           
keygen                         |      19184 |          3.000 |         156.382 |     27.166 |           405525 |      70387
encaps                         |       7430 |          3.000 |         403.773 |     65.179 |          1047210 |     168996
decaps                         |       1218 |          3.001 |        2463.803 |    317.870 |          6390834 |     824503
BIKE3-L3                       |            |                |                 |            |                  |           
keygen                         |       5869 |          3.000 |         511.192 |     85.328 |          1325850 |     221203
encaps                         |       2266 |          3.000 |        1324.134 |    170.321 |          3434542 |     441703
decaps                         |        418 |          3.006 |        7190.904 |    516.631 |         18653124 |    1340115
BIKE3-L5                       |            |                |                 |            |                  |           
keygen                         |       2378 |          3.001 |        1262.050 |    175.761 |          3273449 |     455849
encaps                         |        863 |          3.003 |        3479.655 |    479.443 |          9026067 |    1243652
decaps                         |        198 |          3.008 |       15193.121 |   1404.086 |         39411719 |    3642381

**Comment by dstebila** [comment]
I'd appreciate thoughts/discussion on this pull request.  @vsoftco @christianpaquin @tlepoint @smashra @crockeea @drucker-nir

**Comment by tlepoint** [comment]
I think this is indeed much more accurate and a necessary PR. I approve.

**Comment by dstebila** [comment]
Thanks Tancrède!  Just wanted to make sure there wasn't a reason to keep the other one.

**Pull request merged**
