### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vsoftco**
fixed typo in link

* [ ] Does this PR change the input/output behaviour of a cryptographic algorithm (i.e., does it change known answer test values)?  (If so, a version bump will be required from *x.y.z* to *x.(y+1).0*.)
* [ ] Does this PR change the list of algorithms available -- either adding, removing, or renaming? Does this PR otherwise change an API? (If so, PRs in fully supported downstream projects dependent on these, i.e., [oqs-provider](https://github.com/open-quantum-safe/oqs-provider) will also need to be ready for review and merge by the time this is merged.)

### CODE REVIEW

**Review by Martyrshot — APPROVED** [review]

**Review by praveksharma — APPROVED** [review]

**Comment by baentsch** [comment]
Gentlemen, this reverts #1715: Why? This triggers again a failure in doc-gen with a recent doxygen (that we apparently do not have in CI: Created https://github.com/open-quantum-safe/ci-containers/issues/75 to track).

**Comment by Martyrshot** [comment]
100% my fault Michael. Apologies. The edit made sense to me and I defaulted to "the ci will catch any doc generation errors". I can work on reverting this if you'd like.

**Comment by baentsch** [comment]
NP--And at least 70% my fault for not ensuring CI _can_ catch this.

**Comment by vsoftco** [comment]
> Gentlemen, this reverts #1715: Why? This triggers again a failure in doc-gen with a recent doxygen (that we apparently do not have in CI: Created [open-quantum-safe/ci-containers#75](https://github.com/open-quantum-safe/ci-containers/issues/75) to track).

@baentsch No idea it'll trigger an error, thanks for catching it!

**Pull request merged**
